//! **Stage 6: a place is detailed inside the box the whole gave it**
//! (spec-0050).
//!
//! # Why the pieces here are cut out of the massing
//!
//! Every detail piece in this file is generated by **taking the cells the
//! derivation would have written inside that place's frame and shipping them as
//! a `.nbt`**. That is not a shortcut, it is the sharpest instrument available
//! for the property stage 6 has to hold: *detailing a place must not change
//! whether the map is walkable*. A piece cut from the massing makes the built
//! world byte-for-byte the world the walk judged — so the whole stage-5 battery
//! runs over it unchanged, and if the fabric split were off by a single cell on
//! any face, the substituted world would differ from the massed one and
//! `DW0836`/`DW0837`/`DW0838` would say so.
//!
//! It also means every red below is produced by **perturbing a piece that was
//! green**, never by hand-authoring a broken one: the same discipline
//! `tests/blockout.rs` applies to the derivation, one layer out.
//!
//! The generator is fed by `delvec allocation` and nothing else — the frame, the
//! seams, the answering-face classes and the owed names all come from the
//! handing. So the file doubles as the demonstration that the handing is
//! *sufficient*: a piece written against it alone satisfies every gate.

mod common;

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use delvewright_compiler::blockout::{self, Perturb};
use delvewright_compiler::detail::{self, Allocation};
use delvewright_compiler::plan::Plan;
use delvewright_compiler::registry::PrefabRegistry;
use delvewright_dsl::{Campaign, NodeId, Severity};

// ---------------------------------------------------------------------------
// The fixture, and the pieces cut out of its massing
// ---------------------------------------------------------------------------

fn blockout_dir() -> PathBuf {
    common::repo_root().join("crates/compiler/tests/fixtures/blockout")
}

fn campaign_at(dir: &Path) -> Campaign {
    let loaded =
        delvewright_compiler::load::load_campaign_dir(dir).expect("the campaign is readable");
    delvewright_dsl::parse_campaign(&loaded.raw).expect("the campaign parses")
}

fn walk_record_at(dir: &Path) -> Option<String> {
    delvewright_compiler::load::load_campaign_dir(dir)
        .expect("the campaign is readable")
        .walk_record
}

/// The whole map's massing as a cell map, replayed in write order exactly as the
/// world applies it.
fn massing(c: &Campaign) -> BTreeMap<[i64; 3], String> {
    let mut reads = delvewright_dsl::metrics::Reads::new();
    let fills = blockout::walked_massing(c, &mut reads).expect("a site-plan campaign has massing");
    let mut out: BTreeMap<[i64; 3], String> = BTreeMap::new();
    for f in &fills {
        let lo = [
            i64::from(f.from[0]),
            i64::from(f.from[1]),
            i64::from(f.from[2]),
        ];
        let hi = [i64::from(f.to[0]), i64::from(f.to[1]), i64::from(f.to[2])];
        for cell in blockout::cells_of(lo, hi) {
            if f.block == "minecraft:air" {
                out.remove(&cell);
            } else {
                out.insert(cell, f.block.clone());
            }
        }
    }
    out
}

/// A place's cells, piece-local, with air stated rather than omitted — which is
/// what a real exported piece does, and what makes the substitution total.
///
/// **Plus its own light**, and that is not decoration: spec-0050 §3 takes a bound
/// frame out of the whole's fixture pass, because the whole hanging torches
/// inside a building somebody designed would be the whole writing inside a bound
/// frame. A bound place lights itself and the existing gate judges it — so a
/// piece cut from the massing alone is a dark room, `DW0210` says so, and the
/// repair is the one a real detail piece makes. Torches on a four-cell grid over
/// the walk plane, never inside a seam's own cells.
fn piece_cells(
    c: &Campaign,
    a: &Allocation,
    mass: &BTreeMap<[i64; 3], String>,
) -> Vec<([i32; 3], String)> {
    let _ = c;
    let in_a_seam = |p: [i64; 3]| {
        a.seams.iter().any(|s| {
            (0..3).all(|i| {
                p[i] >= s.cells[0][i].min(s.cells[1][i]) && p[i] <= s.cells[0][i].max(s.cells[1][i])
            })
        })
    };
    let mut out = Vec::new();
    for x in 0..a.extent[0] {
        for y in 0..a.extent[1] {
            for z in 0..a.extent[2] {
                let world = [a.world_min[0] + x, a.world_min[1] + y, a.world_min[2] + z];
                let mut block = mass
                    .get(&world)
                    .cloned()
                    .unwrap_or_else(|| "minecraft:air".to_string());
                let lit_here = y == 1 && x % 4 == 1 && z % 4 == 1;
                if lit_here && block == "minecraft:air" && !in_a_seam([x, y, z]) {
                    block = "minecraft:torch".to_string();
                }
                out.push(([x as i32, y as i32, z as i32], block));
            }
        }
    }
    out
}

/// The first cell a body can stand in, in piece-local coordinates: own cell and
/// the one above clear, the one below solid. Scanned in a fixed order so two
/// runs choose the same cell.
fn standing_cell(a: &Allocation, cells: &[([i32; 3], String)]) -> [i32; 3] {
    let solid: std::collections::BTreeSet<[i32; 3]> = cells
        .iter()
        .filter(|(_, b)| b != "minecraft:air")
        .map(|(p, _)| *p)
        .collect();
    for y in 1..a.extent[1] as i32 {
        for x in 0..a.extent[0] as i32 {
            for z in 0..a.extent[2] as i32 {
                if !solid.contains(&[x, y, z])
                    && !solid.contains(&[x, y + 1, z])
                    && solid.contains(&[x, y - 1, z])
                {
                    return [x, y, z];
                }
            }
        }
    }
    panic!("`{}` offers nowhere to stand", a.place);
}

/// Write the piece a place's allocation asks for, cut out of the massing.
///
/// Everything the metadata claims comes from the allocation: the size is the
/// frame's extent, one face per allocated seam at the cells and class the
/// handing named, and one point anchor standing in the piece's own declared
/// space.
fn write_piece(dir: &Path, id: &str, a: &Allocation, cells: &[([i32; 3], String)]) {
    std::fs::create_dir_all(dir).unwrap();
    let refs: Vec<([i32; 3], &str)> = cells.iter().map(|(p, b)| (*p, b.as_str())).collect();
    let size = [a.extent[0] as i32, a.extent[1] as i32, a.extent[2] as i32];
    std::fs::write(
        dir.join(format!("{id}.nbt")),
        common::structure_nbt(size, &refs),
    )
    .unwrap();
    let seat = standing_cell(a, cells);
    let faces: Vec<serde_json::Value> = a
        .seams
        .iter()
        .map(|s| {
            serde_json::json!({
                "space": "room",
                "class": s.answer_with[0],
                "dir": s.face,
                "opening": { "from": s.cells[0], "to": s.cells[1] },
            })
        })
        .collect();
    let anchors: serde_json::Map<String, serde_json::Value> = a
        .owed_anchors
        .iter()
        .enumerate()
        .map(|(i, _)| {
            (
                format!("seat{i}"),
                serde_json::json!({
                    "pos": seat,
                    "facing": "north",
                    "resolves_to": "space:room",
                }),
            )
        })
        .collect();
    let meta = serde_json::json!({
        "prefab_id": format!("prefab/{id}"),
        "structure": {
            "file": format!("{id}.nbt"),
            "id": id,
            "size": size,
            "data_version": 4671,
            "generator": "crates/compiler/tests/detail.rs",
        },
        "anchors": anchors,
        "connectors": [],
        "lighting": { "profile": "lit", "measured_min_light": 8, "measured": "2026-08-21" },
        "license": {
            "source": "original",
            "spdx": "GPL-3.0-or-later",
            "note": "Test fixture.",
            "provenance": "Cut out of the derived massing by crates/compiler/tests/detail.rs."
        },
        "spatial_contract": {
            "entry": "room",
            "spaces": {
                "room": {
                    "envelope": "enclosed",
                    "boxes": [{ "from": [0, 1, 0], "to": [size[0] - 1, size[1] - 1, size[2] - 1] }],
                },
            },
            "no_body": {},
            "edges": [],
            "faces": faces,
        },
    });
    std::fs::write(
        dir.join(format!("{id}.json")),
        serde_json::to_string_pretty(&meta).unwrap() + "\n",
    )
    .unwrap();
}

/// What a green stage-6 campaign looks like on disk.
struct Detailed {
    campaign: PathBuf,
    prefabs: PathBuf,
}

/// Materialise the blockout fixture with `nodes` bound to pieces cut from its own
/// massing, and a fresh passed walk record.
fn detailed(root: &Path, nodes: &[&str]) -> Detailed {
    let campaign = root.join("campaign");
    let prefabs = root.join("prefabs");
    std::fs::create_dir_all(&prefabs).unwrap();
    common::copy_dir_all(&blockout_dir(), &campaign);
    let c = campaign_at(&campaign);
    let mass = massing(&c);

    let mut details = Vec::new();
    for node in nodes {
        let id = node.split('/').nth(1).unwrap();
        let a = detail::allocation(&c, &NodeId((*node).to_string()))
            .unwrap_or_else(|| panic!("`{node}` is a place this map has"));
        let cells = piece_cells(&c, &a, &mass);
        write_piece(&prefabs, id, &a, &cells);
        let anchors: serde_json::Map<String, serde_json::Value> = a
            .owed_anchors
            .iter()
            .enumerate()
            .map(|(i, name)| (name.clone(), serde_json::json!(format!("seat{i}"))))
            .collect();
        details.push(serde_json::json!({
            "place": node,
            "piece": format!("prefab/{id}"),
            "anchors": anchors,
        }));
    }
    write_detail_plan(&campaign, &details);
    rerecord_walk(&campaign);
    Detailed { campaign, prefabs }
}

fn write_detail_plan(dir: &Path, details: &[serde_json::Value]) {
    let doc = serde_json::json!({
        "campaign_id": "blockout",
        "content": {
            "palette": { "role/wall": "minecraft:stone_bricks", "role/floor": "minecraft:tuff" },
            "details": details,
        },
        "dsl_version": "0.15.0",
        "stage": "detail-plan",
    });
    std::fs::write(
        dir.join("detail-plan.json"),
        delvewright_dsl::to_canonical_string(&doc).unwrap(),
    )
    .unwrap();
}

/// Write the record a passed walk of THIS plan would have produced.
fn rerecord_walk(dir: &Path) {
    let c = campaign_at(dir);
    let h = detail::Hashes::of(&c).expect("a site-plan campaign hashes");
    let rec = serde_json::json!({
        "site_plan_sha256": h.site_plan,
        "layout_graph_sha256": h.layout_graph,
        "blockout_sha256": h.blockout,
        "engine_revision": detail::engine_revision(),
        "verdict": "passed",
        "findings": [],
    });
    std::fs::write(
        dir.join("walk-record.json"),
        delvewright_dsl::to_canonical_string(&rec).unwrap(),
    )
    .unwrap();
}

/// Run the validation-tier detail checks over a materialised campaign.
fn check_at(d: &Detailed) -> (Vec<delvewright_dsl::Diagnostic>, detail::DetailBinding) {
    let c = campaign_at(&d.campaign);
    let reg = PrefabRegistry::load_dir(&d.prefabs).expect("the piece library loads");
    let record = walk_record_at(&d.campaign);
    detail::check(&c, &reg, record.as_deref())
}

fn codes(d: &[delvewright_dsl::Diagnostic]) -> Vec<String> {
    d.iter().map(|x| x.code.clone()).collect()
}

fn errors(d: &[delvewright_dsl::Diagnostic]) -> Vec<&delvewright_dsl::Diagnostic> {
    d.iter().filter(|x| x.severity == Severity::Error).collect()
}

/// Edit a bound piece's metadata in place.
fn patch_piece(d: &Detailed, id: &str, f: impl FnOnce(&mut serde_json::Value)) {
    common::patch_file(&d.prefabs.join(format!("{id}.json")), f);
}

fn patch_detail_plan(d: &Detailed, f: impl FnOnce(&mut serde_json::Value)) {
    common::patch_file(&d.campaign.join("detail-plan.json"), f);
}

const EVERY_PLACE: [&str; 5] = [
    "node/landing",
    "node/hall",
    "node/loft",
    "node/cell",
    "node/exit",
];

// ---------------------------------------------------------------------------
// The green case, and what it binds
// ---------------------------------------------------------------------------

#[test]
fn a_bound_place_validates_and_states_its_binding() {
    let tmp = tempdir("green");
    let d = detailed(&tmp, &["node/exit"]);
    let (diags, binding) = check_at(&d);
    assert!(
        errors(&diags).is_empty(),
        "a piece cut from the massing satisfies every stage-6 gate: {:?}",
        codes(&diags)
    );
    assert_eq!(binding.rows, 1, "one row read");
    assert_eq!(binding.bound, 1, "and it bound a place");
    assert_eq!(binding.boxes, 5, "against the plan's five boxes");
    assert_eq!(binding.records, 1, "over one walk record");
    assert_eq!(
        binding.compared, 2,
        "whose plan hash AND layout-graph hash were both compared — the whole a walk \
         judges is derived from both documents"
    );
    assert_eq!(binding.measured, 1, "one piece measured against its frame");
    assert_eq!(binding.seams_required, 1, "`node/exit` has one seam");
    assert_eq!(binding.faces_examined, 1, "and the piece declares one face");
    assert_eq!(binding.owed, 1, "and owes one anchor name");
    assert!(
        binding
            .line()
            .contains("1 of 5 place(s) bound over 1 `details[]` row(s)"),
        "the count states its denominator: {}",
        binding.line()
    );
    assert!(
        binding
            .line()
            .contains("walk gate: 1 record(s) read, 2 of 2 freshness hash(es) compared"),
        "and the walk gate states its own count WITH its denominator, rather than being \
         a check that reports nothing — or a number about a smaller population than the \
         one it covers: {}",
        binding.line()
    );
}

/// A campaign that carries no detail plan runs every check zero times **and says
/// so** — the standing treatment for a binding of zero.
#[test]
fn a_campaign_with_no_detail_plan_binds_zero_and_states_it() {
    let c = campaign_at(&blockout_dir());
    let reg = PrefabRegistry::load_dir(&common::prefabs_dir()).unwrap();
    let (diags, binding) = detail::check(&c, &reg, None);
    assert!(diags.is_empty(), "{:?}", codes(&diags));
    assert_eq!(binding.rows, 0);
    assert_eq!(binding.records, 0, "and no walk record was asked for");
    assert!(
        binding
            .line()
            .contains("0 of 0 place(s) bound over 0 `details[]` row(s)"),
        "{}",
        binding.line()
    );
}

// ---------------------------------------------------------------------------
// DW0841 — the walk gate, at both entry points
// ---------------------------------------------------------------------------

#[test]
fn dw0841_refuses_a_detail_plan_with_no_walk_record() {
    let tmp = tempdir("dw0841-missing");
    let d = detailed(&tmp, &["node/exit"]);
    std::fs::remove_file(d.campaign.join("walk-record.json")).unwrap();
    let (diags, _) = check_at(&d);
    let e = errors(&diags);
    assert_eq!(e.len(), 1, "{:?}", codes(&diags));
    assert_eq!(e[0].code, "DW0841");
    assert!(
        e[0].message.contains("ZERO records read"),
        "the zero is stated: {}",
        e[0].message
    );
}

#[test]
fn dw0841_refuses_a_record_of_a_different_plan_and_prints_both_hashes() {
    let tmp = tempdir("dw0841-stale");
    let d = detailed(&tmp, &["node/exit"]);
    let before = detail::site_plan_sha256(&campaign_at(&d.campaign)).unwrap();
    // Move the PLAN — the one edit that is supposed to re-open this gate.
    common::patch_file(&d.campaign.join("site-plan.json"), |v| {
        v["content"]["boxes"][0]["min"] = serde_json::json!([5, 8]);
    });
    let after = detail::site_plan_sha256(&campaign_at(&d.campaign)).unwrap();
    assert_ne!(before, after, "a plan edit moves the plan hash");
    let (diags, _) = check_at(&d);
    let e: Vec<_> = diags
        .iter()
        .filter(|x| x.code == "DW0841" && x.severity == Severity::Error)
        .collect();
    assert_eq!(e.len(), 1, "{:?}", codes(&diags));
    assert!(e[0].message.contains(&before), "names the recorded hash");
    assert!(e[0].message.contains(&after), "and the current one");
}

/// A reformat is not a re-walk: the hash is over the plan's CANONICAL bytes.
#[test]
fn dw0841_survives_a_reformat_of_the_plan() {
    let tmp = tempdir("dw0841-reformat");
    let d = detailed(&tmp, &["node/exit"]);
    let path = d.campaign.join("site-plan.json");
    let text = std::fs::read_to_string(&path).unwrap();
    let value: serde_json::Value = serde_json::from_str(&text).unwrap();
    // Serde's own pretty form, which is NOT canonical form: keys in declaration
    // order rather than sorted.
    std::fs::write(&path, serde_json::to_string(&value).unwrap()).unwrap();
    assert_ne!(
        std::fs::read_to_string(&path).unwrap(),
        text,
        "the bytes on disk moved"
    );
    let (diags, _) = check_at(&d);
    assert!(
        errors(&diags).is_empty(),
        "and the walk still stands: {:?}",
        codes(&diags)
    );
}

/// Reach one edge of the fixture's graph BY ID — never by index, so a fixture
/// that gains an edge cannot silently move which one a perturbation lands on.
fn patch_edge(dir: &Path, id: &str, f: impl FnOnce(&mut serde_json::Value)) {
    common::patch_file(&dir.join("layout-graph.json"), |v| {
        let edges = v["content"]["edges"]
            .as_array_mut()
            .expect("the graph declares edges");
        let e = edges
            .iter_mut()
            .find(|e| e["id"] == serde_json::json!(id))
            .unwrap_or_else(|| panic!("`{id}` is an edge this fixture has"));
        f(e);
    });
}

/// **The whole a walk judges is derived from TWO authored documents**, and this
/// is the escape that proves it, in the form that moves real placed bytes.
///
/// `edge/cell-exit` goes from an open archway to a quest-locked bar — a
/// `layout-graph.json` edit and nothing else. The derivation writes
/// `palette::BAR` where it wrote air, so the map a body walks is a different
/// map. The site plan is untouched, so a freshness key over the plan alone reads
/// as fresh and the human walk this record exists to gate is escaped.
#[test]
fn dw0841_refuses_a_graph_edit_that_moves_the_walked_massing() {
    let tmp = tempdir("dw0841-graph-bytes");
    let d = detailed(&tmp, &["node/exit"]);
    let before = detail::Hashes::of(&campaign_at(&d.campaign)).unwrap();

    patch_edge(&d.campaign, "edge/cell-exit", |e| {
        assert_eq!(e["class"], serde_json::json!("walk"), "the way was open");
        e["class"] = serde_json::json!("barred");
        e["opens_from"] = serde_json::json!("a");
        e["gating"] = serde_json::json!({ "flags": ["flag/keeper-yields"] });
    });

    let after = detail::Hashes::of(&campaign_at(&d.campaign)).unwrap();
    assert_eq!(
        after.site_plan, before.site_plan,
        "the site plan was never touched, which is the whole point"
    );
    assert_ne!(
        after.blockout, before.blockout,
        "and the walked massing MOVED: bar stands where air stood"
    );
    assert_ne!(
        after.layout_graph, before.layout_graph,
        "so the half of the key that sees it moved too"
    );

    let (diags, binding) = check_at(&d);
    let e: Vec<_> = errors(&diags)
        .into_iter()
        .filter(|x| x.code == "DW0841")
        .collect();
    assert_eq!(e.len(), 1, "exactly one walk refusal: {:?}", codes(&diags));
    assert!(
        e[0].message.contains(&before.layout_graph),
        "naming the graph the walk was recorded against: {}",
        e[0].message
    );
    assert!(
        e[0].message.contains(&after.layout_graph),
        "and the graph this campaign now has: {}",
        e[0].message
    );
    assert_eq!(binding.compared, 2, "both halves of the key were compared");

    // **And the drift advisory stays silent underneath it.** Its text says what
    // has moved is the TOOLCHAIN. A campaign edit reaching it would make that
    // sentence a lie — which is exactly what this escape used to do, and it is
    // the worse half of the defect, because a warning that denies the state it
    // is reporting trains its reader to wave the state through.
    let c = campaign_at(&d.campaign);
    let rec = walk_record_at(&d.campaign);
    assert!(
        detail::blockout_drift(&c, rec.as_deref()).is_none(),
        "a campaign edit never reaches the advisory that says the toolchain moved"
    );
}

/// **The same escape with no signal of any kind**, and it is the one a
/// derived-geometry key could never have caught.
///
/// `edge/hall-cell` is a one-side-openable door; flipping `opens_from` moves the
/// side its `anchor/unlock-…` stands on, so the door the walk was judged with now
/// opens from the other side. It moves neither the plan hash nor a single placed
/// byte — which is why the key is over the graph's own bytes and not over the
/// derivation: `PlacedSeam` carries a seam's `class`, and carries nothing at all
/// of `opens_from`, `gating`, `one_way` or `falls`.
#[test]
fn dw0841_refuses_a_graph_edit_that_moves_no_byte_at_all() {
    let tmp = tempdir("dw0841-graph-silent");
    let d = detailed(&tmp, &["node/exit"]);
    let before = detail::Hashes::of(&campaign_at(&d.campaign)).unwrap();

    patch_edge(&d.campaign, "edge/hall-cell", |e| {
        assert_eq!(
            e["opens_from"],
            serde_json::json!("a"),
            "it opened from `a`"
        );
        e["opens_from"] = serde_json::json!("b");
    });

    let after = detail::Hashes::of(&campaign_at(&d.campaign)).unwrap();
    assert_eq!(after.site_plan, before.site_plan, "the plan did not move");
    assert_eq!(
        after.blockout, before.blockout,
        "and not one placed byte moved either — this edit is invisible to every \
         hash taken over geometry"
    );
    assert_ne!(
        after.layout_graph, before.layout_graph,
        "the graph's own bytes are the only thing that saw it"
    );

    let (diags, binding) = check_at(&d);
    let e: Vec<_> = errors(&diags)
        .into_iter()
        .filter(|x| x.code == "DW0841")
        .collect();
    assert_eq!(e.len(), 1, "exactly one walk refusal: {:?}", codes(&diags));
    assert!(
        e[0].message.contains("DIFFERENT layout graph"),
        "and it says which document went stale, because the plan and the graph are \
         different edits with different repairs: {}",
        e[0].message
    );
    assert_eq!(binding.compared, 2);
}

/// A reformat is not a re-walk on the graph either — the same rule the plan's
/// half already holds, because the hash is over the document's CANONICAL bytes,
/// written by the writer `delvec fmt --check` accepts.
#[test]
fn dw0841_survives_a_reformat_of_the_layout_graph() {
    let tmp = tempdir("dw0841-graph-reformat");
    let d = detailed(&tmp, &["node/exit"]);
    let path = d.campaign.join("layout-graph.json");
    let text = std::fs::read_to_string(&path).unwrap();
    let value: serde_json::Value = serde_json::from_str(&text).unwrap();
    std::fs::write(&path, serde_json::to_string(&value).unwrap()).unwrap();
    assert_ne!(
        std::fs::read_to_string(&path).unwrap(),
        text,
        "the bytes on disk moved"
    );
    let (diags, _) = check_at(&d);
    assert!(
        errors(&diags).is_empty(),
        "and the walk still stands: {:?}",
        codes(&diags)
    );
}

/// A record that names only the plan is **not a walk record**, and it is refused
/// as one rather than passing on the half it does name.
///
/// This is the hatch question asked of the record's own form: the escape hatch a
/// missing field would open — *a record written before the key was whole is
/// judged by the half of the key it happens to carry* — is precisely what an
/// author with a stale graph would produce, so the field is required and its
/// absence is a refusal that names the form.
#[test]
fn dw0841_refuses_a_record_that_names_no_layout_graph() {
    let tmp = tempdir("dw0841-half-record");
    let d = detailed(&tmp, &["node/exit"]);
    common::patch_file(&d.campaign.join("walk-record.json"), |v| {
        v.as_object_mut().unwrap().remove("layout_graph_sha256");
    });
    let (diags, binding) = check_at(&d);
    let e = errors(&diags);
    assert_eq!(e.len(), 1, "{:?}", codes(&diags));
    assert_eq!(e[0].code, "DW0841");
    assert!(
        e[0].message.contains("layout_graph_sha256"),
        "the refusal names the field the form requires: {}",
        e[0].message
    );
    assert_eq!(binding.records, 1, "the record was read");
    assert_eq!(
        binding.compared, 0,
        "and nothing was compared against it, which is the honest count"
    );
}

#[test]
fn dw0841_refuses_a_record_whose_verdict_is_findings() {
    let tmp = tempdir("dw0841-findings");
    let d = detailed(&tmp, &["node/exit"]);
    common::patch_file(&d.campaign.join("walk-record.json"), |v| {
        v["verdict"] = serde_json::json!("findings");
        v["findings"] = serde_json::json!([
            { "subject": "node/hall", "note": "the hub reads as a corridor" }
        ]);
    });
    let (diags, _) = check_at(&d);
    let e = errors(&diags);
    assert_eq!(e.len(), 1, "{:?}", codes(&diags));
    assert_eq!(e[0].code, "DW0841");
    assert!(
        e[0].message.contains("the hub reads as a corridor"),
        "the walker's own words travel to the refusal: {}",
        e[0].message
    );
}

/// **Both entry points, demonstrated.** The handing refuses on the same rule and
/// the same code — and it refuses a campaign that has no `detail-plan` yet,
/// which is exactly the campaign asking for its first allocation.
#[test]
fn dw0841_guards_the_handing_too() {
    let c = campaign_at(&blockout_dir());
    let d = detail::allocation_walk_gate(&c, None).expect("no record, no allocation");
    assert_eq!(d.code, "DW0841");
    assert!(
        c.detail_plan.is_none(),
        "and the campaign it refused has no detail plan at all — the gate fires \
         BEFORE the work it guards, not after"
    );

    let tmp = tempdir("dw0841-handing");
    let dd = detailed(&tmp, &["node/exit"]);
    let c = campaign_at(&dd.campaign);
    let rec = walk_record_at(&dd.campaign);
    assert!(
        detail::allocation_walk_gate(&c, rec.as_deref()).is_none(),
        "and a fresh passed record opens it"
    );
}

/// The blockout-drift advisory: the same two authored documents, different
/// massing. Reachable only by toolchain movement — because BOTH documents the
/// derivation reads are in the freshness key and have been compared equal by the
/// time it runs — so it is provoked by re-recording a blockout hash no campaign
/// edit could have produced. The sibling test above holds the other direction:
/// a campaign edit that does move the massing refuses at `DW0841` and never
/// reaches this warning.
#[test]
fn a_blockout_that_moved_under_an_unchanged_plan_is_a_warning_not_a_refusal() {
    let tmp = tempdir("drift");
    let d = detailed(&tmp, &["node/exit"]);
    common::patch_file(&d.campaign.join("walk-record.json"), |v| {
        v["blockout_sha256"] = serde_json::json!("0".repeat(64));
        v["engine_revision"] = serde_json::json!("aaaaaaa");
    });
    let c = campaign_at(&d.campaign);
    let rec = walk_record_at(&d.campaign);
    let w = detail::blockout_drift(&c, rec.as_deref()).expect("the drift is reported");
    assert_eq!(w.code, "DW0841");
    assert_eq!(w.severity, Severity::Warning, "and refuses nothing");
    assert!(
        w.message.contains("aaaaaaa"),
        "names both engines: {}",
        w.message
    );
    let (diags, _) = check_at(&d);
    assert!(
        errors(&diags).is_empty(),
        "the refusing half stays green: {:?}",
        codes(&diags)
    );
}

// ---------------------------------------------------------------------------
// DW0842 — the binding does not bind
// ---------------------------------------------------------------------------

#[test]
fn dw0842_refuses_a_place_bound_twice() {
    let tmp = tempdir("dw0842-twice");
    let d = detailed(&tmp, &["node/exit"]);
    patch_detail_plan(&d, |v| {
        let row = v["content"]["details"][0].clone();
        v["content"]["details"].as_array_mut().unwrap().push(row);
    });
    let e = check_and_expect(&d, "DW0842");
    assert!(e.contains("more than one"), "{e}");
}

#[test]
fn dw0842_refuses_a_place_the_graph_does_not_have() {
    let tmp = tempdir("dw0842-place");
    let d = detailed(&tmp, &["node/exit"]);
    patch_detail_plan(&d, |v| {
        v["content"]["details"][0]["place"] = serde_json::json!("node/nowhere");
    });
    let e = check_and_expect(&d, "DW0842");
    assert!(e.contains("node/nowhere"), "{e}");
}

#[test]
fn dw0842_refuses_a_piece_the_library_does_not_hold() {
    let tmp = tempdir("dw0842-piece");
    let d = detailed(&tmp, &["node/exit"]);
    patch_detail_plan(&d, |v| {
        v["content"]["details"][0]["piece"] = serde_json::json!("prefab/nothing");
    });
    let e = check_and_expect(&d, "DW0842");
    assert!(e.contains("prefab/nothing"), "{e}");
}

#[test]
fn dw0842_refuses_an_anchor_key_the_place_does_not_owe() {
    let tmp = tempdir("dw0842-owe");
    let d = detailed(&tmp, &["node/exit"]);
    patch_detail_plan(&d, |v| {
        v["content"]["details"][0]["anchors"]["anchor/seam-cell-exit"] = serde_json::json!("seat0");
    });
    let e = check_and_expect(&d, "DW0842");
    assert!(e.contains("is not a name"), "{e}");
}

/// The limiting case, named rather than inferred.
#[test]
fn dw0842_refuses_a_detail_plan_with_no_site_plan() {
    let tmp = tempdir("dw0842-nosite");
    let d = detailed(&tmp, &["node/exit"]);
    std::fs::remove_file(d.campaign.join("site-plan.json")).unwrap();
    let (diags, binding) = check_at(&d);
    let e = errors(&diags);
    assert!(e.iter().any(|x| x.code == "DW0842"), "{:?}", codes(&diags));
    assert_eq!(binding.boxes, 0, "and the zero denominator is stated");
}

/// **A row that is READ and a place that gets BOUND are different numbers**, and
/// collapsing them let the first exceed its own denominator.
///
/// Two rows naming one place: two rows read, one place bound, five boxes. Said
/// as one number it would have printed "2 of 5 place(s) bound" over a map with
/// one detailed place.
#[test]
fn a_row_read_and_a_place_bound_are_counted_apart() {
    let tmp = tempdir("counts");
    let d = detailed(&tmp, &["node/exit"]);
    patch_detail_plan(&d, |v| {
        let row = v["content"]["details"][0].clone();
        v["content"]["details"].as_array_mut().unwrap().push(row);
    });
    let (_, binding) = check_at(&d);
    assert_eq!(binding.rows, 2, "both rows were read");
    assert_eq!(binding.bound, 1, "and one place was bound");
    assert!(
        binding.bound <= binding.boxes,
        "a count never exceeds its denominator"
    );
}

/// **A piece that is not its frame suspends the FACE check and nothing else.**
///
/// The owed anchors and the declared class depend on neither the extent nor the
/// contract, so a wrong size must not suppress them — fixing the size would then
/// produce a crop of refusals nobody had been shown, and the place's owed names
/// would have been missing from the binding count while it happened.
#[test]
fn a_wrong_extent_suspends_the_face_check_and_no_other() {
    let tmp = tempdir("no-truncation");
    let d = detailed(&tmp, &["node/exit"]);
    patch_piece(&d, "exit", |v| {
        v["structure"]["size"][0] = serde_json::json!(12);
        v["footprint_class"] = serde_json::json!("expanse");
    });
    patch_detail_plan(&d, |v| {
        v["content"]["details"][0]["anchors"] = serde_json::json!({});
    });
    let (diags, binding) = check_at(&d);
    let found = codes(&diags);
    assert!(found.contains(&"DW0843".to_string()), "{found:?}");
    assert!(
        found.contains(&"DW0845".to_string()),
        "the owed anchor is still asked for: {found:?}"
    );
    assert!(
        found.contains(&"DW0848".to_string()),
        "and the declared class is still judged: {found:?}"
    );
    assert!(
        !found.contains(&"DW0844".to_string()),
        "while the face check is suspended, because its cells come from a frame \
         this piece is not: {found:?}"
    );
    assert_eq!(binding.owed, 1, "and the owed name is IN the denominator");
    assert_eq!(binding.classed, 1, "as is the declared class");
    assert_eq!(
        binding.seams_required, 0,
        "while the suspended check honestly says it examined nothing"
    );
}

// ---------------------------------------------------------------------------
// DW0843 — the piece is not the shape of its allocation
// ---------------------------------------------------------------------------

/// **Undersize refuses exactly as oversize does**, on every axis.
#[test]
fn dw0843_refuses_a_piece_one_cell_off_in_either_direction_on_any_axis() {
    for axis in 0..3 {
        for delta in [1i64, -1] {
            let tmp = tempdir(&format!("dw0843-{axis}-{delta}"));
            let d = detailed(&tmp, &["node/exit"]);
            patch_piece(&d, "exit", |v| {
                let n = v["structure"]["size"][axis].as_i64().unwrap();
                v["structure"]["size"][axis] = serde_json::json!(n + delta);
            });
            let e = check_and_expect(&d, "DW0843");
            assert!(
                e.contains(if delta > 0 { "1 too many" } else { "1 too few" }),
                "the refusal names the direction and the amount: {e}"
            );
            assert!(
                e.contains("undersize refuses exactly as oversize does"),
                "and says why they are the same finding: {e}"
            );
        }
    }
}

#[test]
fn dw0843_refuses_a_detail_piece_that_declares_no_contract() {
    let tmp = tempdir("dw0843-contract");
    let d = detailed(&tmp, &["node/exit"]);
    patch_piece(&d, "exit", |v| {
        v.as_object_mut().unwrap().remove("spatial_contract");
    });
    let e = check_and_expect(&d, "DW0843");
    assert!(e.contains("declares no spatial contract"), "{e}");
}

// ---------------------------------------------------------------------------
// DW0844 — the piece's openings are not the plan's seams, both directions
// ---------------------------------------------------------------------------

#[test]
fn dw0844_refuses_a_seam_the_piece_seals() {
    let tmp = tempdir("dw0844-sealed");
    let d = detailed(&tmp, &["node/exit"]);
    patch_piece(&d, "exit", |v| {
        v["spatial_contract"]["faces"] = serde_json::json!([]);
    });
    let e = check_and_expect(&d, "DW0844");
    assert!(e.contains("leaves the seam"), "{e}");
    assert!(e.contains("no face on that side at all"), "{e}");
}

#[test]
fn dw0844_refuses_a_face_answering_no_seam() {
    let tmp = tempdir("dw0844-discovered");
    let d = detailed(&tmp, &["node/exit"]);
    patch_piece(&d, "exit", |v| {
        let extra = serde_json::json!({
            "space": "room",
            "class": "walk",
            "dir": "north",
            "opening": { "from": [3, 1, 0], "to": [4, 3, 0] },
        });
        v["spatial_contract"]["faces"]
            .as_array_mut()
            .unwrap()
            .push(extra);
    });
    let e = check_and_expect(&d, "DW0844");
    assert!(e.contains("DISCOVERED rather than designed"), "{e}");
}

#[test]
fn dw0844_refuses_a_face_of_the_wrong_class() {
    let tmp = tempdir("dw0844-class");
    let d = detailed(&tmp, &["node/exit"]);
    patch_piece(&d, "exit", |v| {
        v["spatial_contract"]["faces"][0]["class"] = serde_json::json!("barred");
    });
    let e = check_and_expect(&d, "DW0844");
    assert!(e.contains("not the same crossing"), "{e}");
}

/// **The two observers, proven independent** (spec-0050 §16.7).
///
/// A piece that lies in its metadata — declaring the face while its BYTES seal
/// the way — passes `DW0844`, which reads declarations, and reds on the bytes
/// battery, which reads blocks. Neither could have caught it alone, and that is
/// the whole reason `DW0844` is deliberately redundant with `DW0836`/`DW0838`
/// rather than their replacement.
#[test]
fn a_piece_that_lies_in_its_metadata_passes_dw0844_and_reds_on_bytes() {
    let tmp = tempdir("independent");
    let d = detailed(&tmp, &["node/exit"]);
    // Wall the seam's own cells up in the BYTES, leaving every declaration
    // exactly as it was.
    let c = campaign_at(&d.campaign);
    let a = detail::allocation(&c, &NodeId("node/exit".into())).unwrap();
    let mass = massing(&c);
    let mut cells = piece_cells(&c, &a, &mass);
    let seam = &a.seams[0];
    for (p, b) in cells.iter_mut() {
        let inside = (0..3).all(|i| {
            i64::from(p[i]) >= seam.cells[0][i].min(seam.cells[1][i])
                && i64::from(p[i]) <= seam.cells[0][i].max(seam.cells[1][i])
        });
        if inside {
            *b = "minecraft:stone_bricks".to_string();
        }
    }
    write_piece(&d.prefabs, "exit", &a, &cells);

    let (diags, _) = check_at(&d);
    assert!(
        errors(&diags).is_empty(),
        "the declaration reader sees nothing wrong — it was not lied to about a \
         declaration: {:?}",
        codes(&diags)
    );

    let (battery, codes) = battery_at(&d);
    assert!(
        codes.iter().any(|c| c == "DW0836" || c == "DW0837"),
        "and the byte reader refuses: {codes:?}"
    );
    assert!(battery.refusal().is_some());
}

// ---------------------------------------------------------------------------
// DW0845 — an owed anchor has no standing
// ---------------------------------------------------------------------------

#[test]
fn dw0845_refuses_an_owed_name_left_unbound() {
    let tmp = tempdir("dw0845-unbound");
    let d = detailed(&tmp, &["node/exit"]);
    patch_detail_plan(&d, |v| {
        v["content"]["details"][0]["anchors"] = serde_json::json!({});
    });
    let e = check_and_expect(&d, "DW0845");
    assert!(e.contains("anchor/node-exit"), "{e}");
    assert!(e.contains("never force a quest edit"), "{e}");
}

#[test]
fn dw0845_refuses_an_anchor_a_body_cannot_be_at() {
    let tmp = tempdir("dw0845-nobody");
    let d = detailed(&tmp, &["node/exit"]);
    patch_piece(&d, "exit", |v| {
        v["anchors"]["seat0"]["resolves_to"] = serde_json::json!("no_body:rafters");
    });
    let e = check_and_expect(&d, "DW0845");
    assert!(e.contains("not play space"), "{e}");
}

#[test]
fn dw0845_refuses_a_region_anchor_where_a_place_to_stand_is_owed() {
    let tmp = tempdir("dw0845-region");
    let d = detailed(&tmp, &["node/exit"]);
    patch_piece(&d, "exit", |v| {
        let a = v["anchors"]["seat0"].as_object_mut().unwrap();
        a.remove("pos");
        a.insert(
            "region".to_string(),
            serde_json::json!({ "from": [1, 1, 1], "to": [2, 2, 2] }),
        );
        a.insert(
            "block".to_string(),
            serde_json::json!("minecraft:iron_bars"),
        );
    });
    let e = check_and_expect(&d, "DW0845");
    assert!(e.contains("declares no cell"), "{e}");
}

// ---------------------------------------------------------------------------
// DW0848 — the declared footprint class, at the consumer door
// ---------------------------------------------------------------------------

#[test]
fn dw0848_refuses_a_declared_class_the_bytes_contradict() {
    let tmp = tempdir("dw0848");
    let d = detailed(&tmp, &["node/exit"]);
    // `node/exit` is an 8x8 alcove; `expanse` starts at 64x64.
    patch_piece(&d, "exit", |v| {
        v["footprint_class"] = serde_json::json!("expanse");
    });
    let e = check_and_expect(&d, "DW0848");
    assert!(e.contains("could serve no box of that class"), "{e}");

    // And the honest claim passes, so the check is not simply always red.
    let tmp = tempdir("dw0848-green");
    let d = detailed(&tmp, &["node/exit"]);
    patch_piece(&d, "exit", |v| {
        v["footprint_class"] = serde_json::json!("alcove");
    });
    let (diags, binding) = check_at(&d);
    assert!(errors(&diags).is_empty(), "{:?}", codes(&diags));
    assert_eq!(
        binding.classed, 1,
        "and the declaration was judged, not skipped"
    );
}

#[test]
fn dw0812_refuses_a_footprint_class_the_table_does_not_define() {
    let tmp = tempdir("dw0848-unknown");
    let d = detailed(&tmp, &["node/exit"]);
    patch_piece(&d, "exit", |v| {
        v["footprint_class"] = serde_json::json!("cathedral");
    });
    let e = check_and_expect(&d, "DW0812");
    assert!(e.contains("cathedral"), "{e}");
}

// ---------------------------------------------------------------------------
// DW0821's promotion, in both directions
// ---------------------------------------------------------------------------

/// The fixture declares a vista the derived massing blocks, so the same world is
/// a warning while any box is unbound and a refusal once every node is bound.
/// Nothing is set and nothing is chosen: the severity is computed from the
/// artifact.
#[test]
fn dw0821_is_a_warning_until_every_node_is_bound_and_then_a_refusal() {
    let tmp = tempdir("dw0821-partial");
    let partial = detailed(&tmp, &EVERY_PLACE[..4]);
    assert!(!detail::fully_detailed(&campaign_at(&partial.campaign)));
    let (battery, found) = battery_at(&partial);
    assert!(found.iter().any(|c| c == "DW0821"), "{found:?}");
    assert!(
        battery
            .findings
            .iter()
            .any(|(_, d)| d.code == "DW0821" && d.severity == Severity::Warning),
        "one box still massed, so the vista is still the walk sheet's business"
    );

    let tmp = tempdir("dw0821-full");
    let full = detailed(&tmp, &EVERY_PLACE);
    let c = campaign_at(&full.campaign);
    assert!(detail::fully_detailed(&c));
    let (dd, binding) = check_at(&full);
    assert!(
        errors(&dd).is_empty(),
        "five pieces cut from the massing satisfy every stage-6 gate — including \
         the hall's hosted stair and the loft's drop: {:?}",
        codes(&dd)
    );
    assert_eq!(
        binding.bound,
        5,
        "and every place is bound: {}",
        binding.line()
    );
    assert_eq!(
        binding.seams_required, 10,
        "each of the five seams answered from both sides"
    );

    let (battery, _) = battery_at(&full);
    let sight: Vec<_> = battery
        .findings
        .iter()
        .filter(|(_, d)| d.code == "DW0821")
        .collect();
    assert_eq!(sight.len(), 1, "the same one vista");
    assert_eq!(
        sight[0].1.severity,
        Severity::Error,
        "and with nothing left to carve it is a refusal"
    );
    let refusal = battery.refusal().expect("which stops the build");
    assert_eq!(
        refusal.1.code,
        "DW0821",
        "and it is the ONLY refusal — the substituted world is otherwise the world \
         the walk judged, over every one of its five places: {:?}",
        battery
            .findings
            .iter()
            .filter(|(_, x)| x.severity == Severity::Error)
            .map(|(_, x)| x.code.clone())
            .collect::<Vec<_>>()
    );
}

// ---------------------------------------------------------------------------
// Traversal equivalence, and determinism
// ---------------------------------------------------------------------------

/// Run the stage-5 battery over the detailed world — the equivalence instrument
/// (spec-0050 §7), unchanged and reused rather than reimplemented.
fn battery_at(d: &Detailed) -> (blockout::Battery, Vec<String>) {
    let c = campaign_at(&d.campaign);
    let reg = PrefabRegistry::load_dir(&d.prefabs).expect("the piece library loads");
    let plan = Plan::build(&c, &reg).expect("the detailed campaign plans");
    let mut structures: BTreeMap<String, Vec<u8>> = BTreeMap::new();
    for area in &plan.areas {
        for piece in &area.pieces {
            for t in &piece.templates {
                if let Ok(bytes) = std::fs::read(d.prefabs.join(&t.structure_file)) {
                    structures.insert(t.structure_file.clone(), bytes);
                }
            }
        }
    }
    let blocks = delvewright_compiler::assembled::assembled_blocks(&plan, &structures);
    let battery = blockout::check(&plan, &blocks).expect("a site-plan campaign has a blockout");
    let codes = battery
        .findings
        .iter()
        .map(|(_, d)| d.code.clone())
        .collect();
    (battery, codes)
}

/// **Traversal equivalence, demonstrated as a passing battery rather than
/// asserted** (spec-0050 §16.4): the world with a piece standing where massing
/// stood answers every question the massed world answered, over the same
/// instrument.
#[test]
fn the_stage_five_battery_is_green_over_a_detailed_world() {
    let tmp = tempdir("equivalence");
    let d = detailed(&tmp, &["node/exit"]);
    let (battery, _) = battery_at(&d);
    assert!(
        battery.refusal().is_none(),
        "{:?}",
        battery
            .findings
            .iter()
            .filter(|(_, x)| x.severity == Severity::Error)
            .map(|(_, x)| x.message.clone())
            .collect::<Vec<_>>()
    );
    assert!(
        battery.binding.seams > 0 && battery.binding.nodes == 5,
        "and it bound to the whole map: {}",
        battery.binding.line()
    );
}

/// **The derivation stops writing inside a bound frame, and nowhere else.**
///
/// The world a bound campaign masses is the unbound one MINUS exactly the frame,
/// so the fabric split is measured rather than described.
#[test]
fn the_derivation_leaves_a_bound_frame_empty_and_touches_nothing_else() {
    let tmp = tempdir("holes");
    let d = detailed(&tmp, &["node/exit"]);
    let c = campaign_at(&d.campaign);
    let a = detail::allocation(&c, &NodeId("node/exit".into())).unwrap();
    let unbound = massing(&campaign_at(&blockout_dir()));

    let mut reads = delvewright_dsl::metrics::Reads::new();
    let (placement, _) = blockout::derive(&c, &mut reads).expect("the campaign derives");
    let mut bound: BTreeMap<[i64; 3], String> = BTreeMap::new();
    for f in &placement.mass {
        let lo = [
            i64::from(f.from[0]),
            i64::from(f.from[1]),
            i64::from(f.from[2]),
        ];
        let hi = [i64::from(f.to[0]), i64::from(f.to[1]), i64::from(f.to[2])];
        for cell in blockout::cells_of(lo, hi) {
            if f.block == "minecraft:air" {
                bound.remove(&cell);
            } else {
                bound.insert(cell, f.block.clone());
            }
        }
    }

    let inside = |cell: &[i64; 3]| {
        (0..3).all(|i| cell[i] >= a.world_min[i] && cell[i] < a.world_min[i] + a.extent[i])
    };
    let lost: Vec<_> = unbound.keys().filter(|k| !bound.contains_key(*k)).collect();
    assert!(
        !lost.is_empty(),
        "binding a place must actually stop the derivation writing something"
    );
    assert!(
        lost.iter().all(|k| inside(k)),
        "and every cell it stopped writing is inside the frame: {:?}",
        lost.iter().take(4).collect::<Vec<_>>()
    );
    let gained: Vec<_> = bound.keys().filter(|k| !unbound.contains_key(*k)).collect();
    assert!(gained.is_empty(), "and it writes nothing new: {gained:?}");
    for (cell, block) in &bound {
        assert_eq!(
            unbound.get(cell),
            Some(block),
            "and every cell it still writes is the block it always wrote, at {cell:?}"
        );
    }
}

/// A campaign that binds nothing masses exactly what it massed before, so the
/// whole of stage 6 is byte-invisible to every campaign below 0.15.0.
#[test]
fn a_campaign_that_binds_nothing_is_massed_byte_identically() {
    let tmp = tempdir("no-op");
    let d = detailed(&tmp, &[]);
    let bound = massing(&campaign_at(&d.campaign));
    let unbound = massing(&campaign_at(&blockout_dir()));
    assert_eq!(bound, unbound);
}

/// **Determinism (ADR-0006)**: same DSL, same seed, byte-identical output — with
/// a piece standing in a place.
#[test]
fn a_detailed_campaign_builds_byte_identically_twice() {
    let tmp = tempdir("determinism");
    let d = detailed(&tmp, &["node/exit"]);
    let a = build_into(&d, &tmp.join("out-a"));
    let b = build_into(&d, &tmp.join("out-b"));
    assert!(!a.is_empty(), "a build produced files");
    assert_eq!(
        a.keys().collect::<Vec<_>>(),
        b.keys().collect::<Vec<_>>(),
        "the same file set"
    );
    for (k, v) in &a {
        assert_eq!(b.get(k), Some(v), "and identical bytes in {k}");
    }
}

/// The seed reaches no blockout byte and no piece placement, so moving it moves
/// nothing about where a detailed place is or what is in it.
#[test]
fn the_seed_moves_no_detailed_byte() {
    let tmp = tempdir("seed");
    let d = detailed(&tmp, &["node/exit"]);
    let before = massing(&campaign_at(&d.campaign));
    common::patch_file(&d.campaign.join("world.json"), |v| {
        v["content"]["seed"] = serde_json::json!(987_654_321i64);
    });
    let after = massing(&campaign_at(&d.campaign));
    assert_eq!(before, after);
}

// ---------------------------------------------------------------------------
// The frame is unauthorable, asserted rather than described
// ---------------------------------------------------------------------------

/// The schema has no spelling for where anything goes, so the whole class of
/// "nudge the frame" edits does not parse. `delvewright_dsl::detailplan` asserts
/// this over the row and the document; here it is asserted end to end, over a
/// real campaign directory, because that is where an author would try it.
#[test]
fn a_detail_plan_cannot_state_a_coordinate() {
    let tmp = tempdir("unauthorable");
    let d = detailed(&tmp, &["node/exit"]);
    for (path, value) in [
        ("min", serde_json::json!([0, 0, 0])),
        ("offset", serde_json::json!([0, 1, 0])),
        ("extent", serde_json::json!([8, 5, 8])),
        ("datum", serde_json::json!("datum/grade")),
    ] {
        patch_detail_plan(&d, |v| {
            v["content"]["details"][0][path] = value;
        });
        let loaded =
            delvewright_compiler::load::load_campaign_dir(&d.campaign).expect("still readable");
        let Err(diags) = delvewright_dsl::parse_campaign(&loaded.raw) else {
            panic!("a detail row carrying `{path}` must not parse");
        };
        assert!(
            diags.iter().any(|x| x.code == "DW0100"),
            "the refusal is the schema's: {:?}",
            codes(&diags)
        );
        // Put it back for the next round of the loop.
        patch_detail_plan(&d, |v| {
            v["content"]["details"][0]
                .as_object_mut()
                .unwrap()
                .remove(path);
        });
    }
}

/// The version fence, on the settled shape: a campaign below 0.15.0 cannot carry
/// the document at all, so no older campaign moves by a byte.
#[test]
fn dw0141_fences_the_document_below_its_version() {
    let tmp = tempdir("fence");
    let d = detailed(&tmp, &["node/exit"]);
    patch_detail_plan(&d, |v| {
        v["dsl_version"] = serde_json::json!("0.14.0");
    });
    let loaded = delvewright_compiler::load::load_campaign_dir(&d.campaign).unwrap();
    let c = delvewright_dsl::parse_campaign(&loaded.raw).expect("it still parses");
    let diags = delvewright_dsl::validate_campaign(&c);
    assert!(
        diags.iter().any(|x| x.code == "DW0141"),
        "{:?}",
        codes(&diags)
    );
}

// ---------------------------------------------------------------------------
// The two verbs, at process level
// ---------------------------------------------------------------------------

const BIN: &str = env!("CARGO_BIN_EXE_delvec");

fn delvec(args: &[&str]) -> std::process::Output {
    std::process::Command::new(BIN)
        .args(args)
        .output()
        .expect("run delvec")
}

/// `delvec allocation` hands out the whole of what the plan gives a place, and
/// nothing a piece could give back — there is no coordinate in the SCHEMA, and
/// the world position it prints is stated as a finding aid rather than as an
/// input, because nothing reads it back.
#[test]
fn the_allocation_verb_hands_out_the_frame_the_seams_and_the_owed_names() {
    let tmp = tempdir("allocation-cli");
    let d = detailed(&tmp, &[]);
    let out = delvec(&[
        "--prefabs",
        d.prefabs.to_str().unwrap(),
        "allocation",
        d.campaign.to_str().unwrap(),
        "node/exit",
    ]);
    assert_eq!(
        out.status.code(),
        Some(0),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let v: serde_json::Value = serde_json::from_slice(&out.stdout).expect("it prints JSON");
    assert_eq!(v["place"], "node/exit");
    assert_eq!(
        v["extent"],
        serde_json::json!([8, 5, 8]),
        "the frame is the box plus its floor course"
    );
    assert_eq!(v["datum_y"], 1, "and the walk plane is one course up");
    assert_eq!(v["seams"][0]["edge"], "edge/cell-exit");
    assert_eq!(v["seams"][0]["face"], "east");
    assert_eq!(v["seams"][0]["answer_with"], serde_json::json!(["walk"]));
    assert_eq!(v["owed_anchors"], serde_json::json!(["anchor/node-exit"]));
    assert_eq!(
        v["palette"]["role/wall"], "minecraft:stone_bricks",
        "and the whole's vocabulary is handed through, gated by nothing"
    );

    let all = delvec(&[
        "--prefabs",
        d.prefabs.to_str().unwrap(),
        "allocation",
        d.campaign.to_str().unwrap(),
        "--all",
    ]);
    assert_eq!(all.status.code(), Some(0));
    let v: serde_json::Value = serde_json::from_slice(&all.stdout).unwrap();
    assert_eq!(
        v.as_array().unwrap().len(),
        5,
        "one per place, in plan order"
    );
}

/// **The second entry point, at process level.** The handing refuses on the same
/// rule and the same code as validation.
#[test]
fn the_allocation_verb_refuses_without_a_passed_fresh_record() {
    let tmp = tempdir("allocation-refuse");
    let d = detailed(&tmp, &[]);
    std::fs::remove_file(d.campaign.join("walk-record.json")).unwrap();
    let out = delvec(&[
        "--prefabs",
        d.prefabs.to_str().unwrap(),
        "allocation",
        d.campaign.to_str().unwrap(),
        "node/exit",
    ]);
    assert_eq!(out.status.code(), Some(1));
    let s = String::from_utf8_lossy(&out.stdout) + String::from_utf8_lossy(&out.stderr);
    assert!(s.contains("DW0841"), "{s}");
    assert!(
        out.stdout.is_empty() || !s.contains("\"extent\""),
        "and prints no numbers: {s}"
    );
}

/// Every build of a site-plan campaign prints all three hashes and names the
/// engine by its revision — which is what lets a walk record name its subject
/// and its instrument literally.
#[test]
fn a_detailed_build_exits_zero_and_prints_every_hash() {
    let tmp = tempdir("build-cli");
    let d = detailed(&tmp, &["node/exit"]);
    let out = delvec(&[
        "--prefabs",
        d.prefabs.to_str().unwrap(),
        "build",
        d.campaign.to_str().unwrap(),
        "--out",
        tmp.join("out").to_str().unwrap(),
    ]);
    let err = String::from_utf8_lossy(&out.stderr);
    assert_eq!(out.status.code(), Some(0), "{err}");
    let c = campaign_at(&d.campaign);
    let h = detail::Hashes::of(&c).unwrap();
    assert!(err.contains(&h.site_plan), "the plan hash: {err}");
    assert!(
        err.contains(&h.layout_graph),
        "the layout-graph hash, which is the other half of the record's key: {err}"
    );
    assert!(err.contains(&h.blockout), "the blockout hash: {err}");
    assert!(
        err.contains(detail::engine_revision()),
        "and the engine's revision"
    );
    assert!(
        err.contains("1 of 5 place(s) bound"),
        "and the detail binding count, with its denominator"
    );
}

/// **Each half of the key sees its own document and nothing else**, and the key
/// is CLOSED: the derived whole is a function of the site plan, the layout
/// graph, the metrics table and the engine, so the two authored documents are
/// hashed and the toolchain is named by revision. Nothing else in the campaign
/// reaches it.
///
/// The closure is the load-bearing claim, and it is what this test measures. A
/// key with a hole in it is not a weaker gate, it is a green one: the hole was
/// the layout graph, and a graph-only edit moved placed bytes under a record
/// that went on reading as fresh. A key that saw MORE than the derivation reads
/// would fail the other way — a gate that cries wolf is a gate somebody
/// re-records past — which is why `world.json` is measured here too.
#[test]
fn the_key_is_each_document_and_the_key_is_closed() {
    let tmp = tempdir("hashes");
    let d = detailed(&tmp, &["node/exit"]);
    let before = detail::Hashes::of(&campaign_at(&d.campaign)).unwrap();

    // An edit outside BOTH keyed documents: the campaign's own stage 1.
    common::patch_file(&d.campaign.join("world.json"), |v| {
        v["content"]["seed"] = serde_json::json!(4242);
    });
    let after = detail::Hashes::of(&campaign_at(&d.campaign)).unwrap();
    assert_eq!(
        before, after,
        "no hash sees anything but the plan, the graph, the table and the engine"
    );

    // The graph, which moves its own half and leaves the plan's alone. It is
    // hashed WHOLE — a reworded `note` re-opens the gate — because a key over a
    // hand-picked traversal projection is a list somebody has to remember to
    // extend, and the field added next release falls silently outside it. The
    // plan's half already makes the same trade over `views[].note`.
    common::patch_file(&d.campaign.join("layout-graph.json"), |v| {
        v["content"]["nodes"][0]["note"] = serde_json::json!("Reworded, and no geometry moved.");
    });
    let graph_moved = detail::Hashes::of(&campaign_at(&d.campaign)).unwrap();
    assert_ne!(
        graph_moved.layout_graph, before.layout_graph,
        "a graph edit moves the graph hash"
    );
    assert_eq!(
        graph_moved.site_plan, before.site_plan,
        "and not the plan's, because they are different documents with different repairs"
    );
    assert_eq!(
        graph_moved.blockout, before.blockout,
        "this particular graph edit moves no geometry, which is exactly the case a \
         geometry hash cannot carry"
    );

    // And the plan itself, which must move its own half and the massing with it.
    common::patch_file(&d.campaign.join("site-plan.json"), |v| {
        v["content"]["boxes"][0]["min"] = serde_json::json!([5, 8]);
    });
    let moved = detail::Hashes::of(&campaign_at(&d.campaign)).unwrap();
    assert_ne!(
        moved.site_plan, before.site_plan,
        "a plan edit moves the plan hash"
    );
    assert_ne!(
        moved.blockout, before.blockout,
        "and the massing derived from it moves too — which is why the blockout hash \
         alone could never carry this gate"
    );
}

/// **A bound place lights itself, and the existing gate judges it**
/// (spec-0050 §3).
///
/// The blockout fixture declares `lighting: {fixture: torch}`, and before stage 6
/// that pass hung torches on every dark reachable cell of the whole area. Inside
/// a bound frame it must not: the frame is the piece's, and lighting is part of
/// what a place looks like — the whole lighting a building somebody designed
/// would be the whole writing inside a bound frame, which is the one thing the
/// fabric split says it does not do.
///
/// What replaces it is not silence. The cells go to the undeclared-darkness
/// measurement, so a dark detailed place is a **finding**, and this is the
/// demonstration: take the light out of the piece and the build refuses.
#[test]
fn the_whole_does_not_light_a_bound_place_and_a_dark_one_is_a_finding() {
    let tmp = tempdir("relight");
    let d = detailed(&tmp, &["node/exit"]);
    // Green first, so what follows is measured against a piece that was lit.
    let out = delvec(&[
        "--prefabs",
        d.prefabs.to_str().unwrap(),
        "build",
        d.campaign.to_str().unwrap(),
        "--out",
        tmp.join("out-lit").to_str().unwrap(),
    ]);
    assert_eq!(
        out.status.code(),
        Some(0),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );

    // Now put the piece's own lights out, changing nothing else.
    let c = campaign_at(&d.campaign);
    let a = detail::allocation(&c, &NodeId("node/exit".into())).unwrap();
    let mass = massing(&c);
    let cells: Vec<([i32; 3], String)> = piece_cells(&c, &a, &mass)
        .into_iter()
        .map(|(p, b)| {
            if b == "minecraft:torch" {
                (p, "minecraft:air".to_string())
            } else {
                (p, b)
            }
        })
        .collect();
    assert!(
        cells.iter().all(|(_, b)| b != "minecraft:torch"),
        "the perturbation actually removed something"
    );
    write_piece(&d.prefabs, "exit", &a, &cells);

    let out = delvec(&[
        "--prefabs",
        d.prefabs.to_str().unwrap(),
        "build",
        d.campaign.to_str().unwrap(),
        "--out",
        tmp.join("out-dark").to_str().unwrap(),
    ]);
    let s = String::from_utf8_lossy(&out.stdout) + String::from_utf8_lossy(&out.stderr);
    assert_ne!(out.status.code(), Some(0), "a dark place is a finding: {s}");
    assert!(
        s.contains("DW0210"),
        "and it is the darkness gate that says so, not a silence: {s}"
    );
    assert!(
        s.contains("area/site"),
        "over the site area the piece stands in: {s}"
    );
}

/// **The UNFENCED vacuity mode, closed at the type level.**
///
/// A check whose code declares `Binds::Since(n)` is dropped by
/// `delvewright_dsl::fence` for any campaign whose stage declares less than `n`
/// — which is how a general check comes to pass on a tree it never examined.
/// Every stage-6 code binds at **every** version, and it is correct that they
/// do: each is a rule about what a `detail-plan` SAYS, and a campaign with no
/// such document reaches none of them, so there is nothing to grandfather.
///
/// Asserted rather than described, because the difference between the two is
/// exactly what the fence's own module docs say costs a staging round.
#[test]
fn every_stage_six_code_binds_at_every_version() {
    use delvewright_dsl::Binds;
    for code in [
        detail::DW_UNWALKED,
        detail::DW_BINDING,
        detail::DW_NOT_THE_FRAME,
        detail::DW_FACES,
        detail::DW_ANCHOR_STANDING,
        delvewright_dsl::prefab::DW_FOOTPRINT_CLASS,
    ] {
        assert_eq!(
            code.binds(),
            Binds::EveryVersion,
            "`{code}` is a rule about what a document says, so nothing may grandfather it"
        );
    }
}

/// **The red reaching a creator's exit code**, end to end and through the fence.
///
/// The unit checks above read `detail::check`'s raw list; this reads what
/// `delvec build` actually does with it, which is where an obligation that the
/// fence quietly dropped would show up as a green build.
#[test]
fn a_piece_that_is_not_its_frame_fails_the_build_through_the_fence() {
    let tmp = tempdir("build-red");
    let d = detailed(&tmp, &["node/exit"]);
    patch_piece(&d, "exit", |v| {
        v["structure"]["size"][0] = serde_json::json!(12);
    });
    let out = delvec(&[
        "--prefabs",
        d.prefabs.to_str().unwrap(),
        "build",
        d.campaign.to_str().unwrap(),
        "--out",
        tmp.join("out").to_str().unwrap(),
    ]);
    let s = String::from_utf8_lossy(&out.stdout) + String::from_utf8_lossy(&out.stderr);
    assert_eq!(out.status.code(), Some(1), "{s}");
    assert!(s.contains("DW0843"), "{s}");
    assert!(
        !tmp.join("out").join("manifest.json").exists(),
        "and no datapack was written"
    );
}

/// **The bot is handed the same walk** (spec-0050 §16.4).
///
/// The critical-path export is what the mineflayer harness drives, so comparing
/// it between a detailed map and its massed twin asks the playthrough's own
/// question at compile time: same objectives, same order, same completion
/// oracle. The one thing that moves is where inside the detailed place the body
/// walks to — which is §7's "anchor positions within their box" being free, and
/// is the anchor RE-BINDING working: if this were byte-identical, the piece's own
/// anchor would not have replaced the massing's footing at all.
///
/// A full playthrough needs a server and a bot and is a runtime tier; this is
/// what can be measured without one, and it is not a substitute for it.
#[test]
fn the_bot_is_handed_the_same_path_with_one_cell_moved_inside_the_detailed_place() {
    let tmp = tempdir("bot-export");
    let d = detailed(&tmp, &["node/exit"]);
    let detailed_out = build_into(&d, &tmp.join("out-detailed"));

    // The massed twin: the same campaign with the binding taken away.
    std::fs::remove_file(d.campaign.join("detail-plan.json")).unwrap();
    let massed_out = build_into(&d, &tmp.join("out-massed"));

    let path = |t: &BTreeMap<String, Vec<u8>>| -> serde_json::Value {
        serde_json::from_slice(
            t.get("critical-path.json")
                .expect("every build exports the bot's path"),
        )
        .expect("it is JSON")
    };
    let (a, b) = (path(&detailed_out), path(&massed_out));
    let (sa, sb) = (
        a["steps"].as_array().unwrap(),
        b["steps"].as_array().unwrap(),
    );
    assert!(!sa.is_empty(), "the fixture has a critical path");
    assert_eq!(sa.len(), sb.len(), "the same number of steps");

    let mut moved = 0usize;
    for (x, y) in sa.iter().zip(sb.iter()) {
        for (k, v) in x.as_object().unwrap() {
            if k == "pos" {
                if v != &y["pos"] {
                    moved += 1;
                }
                continue;
            }
            assert_eq!(
                Some(v),
                y.get(k),
                "step field `{k}` moved, and only a POSITION inside a detailed place may"
            );
        }
    }
    assert_eq!(
        moved, 1,
        "exactly one step moved — the one seated in the place a piece now stands in"
    );
    for k in a.as_object().unwrap().keys() {
        if k != "steps" {
            assert_eq!(
                a[k], b[k],
                "and nothing else about the contract moved: `{k}`"
            );
        }
    }
}

/// **Both binding lines reach a reader** — the builder's and the observer's.
///
/// `blockout::Binding::line()` had no production caller at all until stage 6:
/// the battery's count was printed and the derivation's was not, so a build
/// stated what was examined and never what was built. A line that is correct,
/// reviewable and reaches nobody is the UNRUN shape at its smallest, and the
/// repair is not a doc line — it is this assertion, over the process.
#[test]
fn a_build_states_what_it_built_as_well_as_what_it_examined() {
    let tmp = tempdir("binding-lines");
    let d = detailed(&tmp, &["node/exit"]);
    let out = delvec(&[
        "--prefabs",
        d.prefabs.to_str().unwrap(),
        "build",
        d.campaign.to_str().unwrap(),
        "--out",
        tmp.join("out").to_str().unwrap(),
    ]);
    let err = String::from_utf8_lossy(&out.stderr);
    assert_eq!(out.status.code(), Some(0), "{err}");
    assert!(
        err.contains("blockout binding:"),
        "the DERIVATION states what it bound to: {err}"
    );
    assert!(
        err.contains("(1 detailed, so 4 massed by the derivation)"),
        "and the split is the number stage 6 made load-bearing — a reader who \
         cannot see it cannot tell a fully detailed map from one binding nothing: \
         {err}"
    );
    assert!(
        err.contains("blockout battery binding:"),
        "and the OBSERVER states what it examined: {err}"
    );
    assert!(
        err.contains("detail binding:"),
        "as does the detail gate: {err}"
    );
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

fn check_and_expect(d: &Detailed, code: &str) -> String {
    let (diags, _) = check_at(d);
    let hit: Vec<_> = diags
        .iter()
        .filter(|x| x.code == code && x.severity == Severity::Error)
        .collect();
    assert_eq!(
        hit.len(),
        1,
        "expected exactly one {code}, got {:?}",
        codes(&diags)
    );
    hit[0].message.clone()
}

fn build_into(d: &Detailed, out: &Path) -> BTreeMap<String, Vec<u8>> {
    let loaded = delvewright_compiler::load::load_campaign_dir(&d.campaign).unwrap();
    let c = delvewright_dsl::parse_campaign(&loaded.raw).unwrap();
    let reg = PrefabRegistry::load_dir(&d.prefabs).unwrap();
    let plan = Plan::build(&c, &reg).expect("the detailed campaign plans");
    let mut structures: BTreeMap<String, Vec<u8>> = BTreeMap::new();
    for area in &plan.areas {
        for piece in &area.pieces {
            for t in &piece.templates {
                if let Ok(bytes) = std::fs::read(d.prefabs.join(&t.structure_file)) {
                    structures.insert(t.structure_file.clone(), bytes);
                }
            }
        }
    }
    let tree = delvewright_compiler::commands::CommandTree::v1_21_11();
    let (built, _warn) = delvewright_compiler::emit::build_with_warnings(
        &plan,
        &loaded.inputs,
        &structures,
        &tree,
        &reg,
        None,
        "test",
        &BTreeMap::new(),
    )
    .expect("the detailed campaign builds");
    let _ = out;
    built
}

/// A scratch directory of this test's own, removed and recreated so a rerun
/// never inherits the last run's files.
fn tempdir(name: &str) -> PathBuf {
    let p = std::env::temp_dir().join(format!("dw-detail-{name}"));
    let _ = std::fs::remove_dir_all(&p);
    std::fs::create_dir_all(&p).unwrap();
    p
}

/// The perturbation surface is an ARGUMENT, never a switch — asserted here for
/// the same reason `tests/blockout.rs` asserts it of the derivation: a
/// production path that could acquire a defect from a global is a production
/// path nothing can measure.
#[test]
fn the_detailed_build_runs_the_unperturbed_derivation() {
    let tmp = tempdir("unperturbed");
    let d = detailed(&tmp, &["node/exit"]);
    let c = campaign_at(&d.campaign);
    let reg = PrefabRegistry::load_dir(&d.prefabs).unwrap();
    let a = Plan::build(&c, &reg).expect("plans");
    let b = Plan::build_with(&c, &reg, Perturb::none()).expect("plans");
    let mass = |p: &Plan| -> Vec<String> {
        p.areas
            .iter()
            .flat_map(|x| x.mass.iter())
            .map(|f| format!("{:?}{:?}{}", f.from, f.to, f.block))
            .collect()
    };
    assert_eq!(mass(&a), mass(&b));
}
