//! **Which IR constructs no example exercises** (spec-0033 deliverable C).
//!
//! # What this measures, and the thing it must never be read as
//!
//! `prefab-procedure.md` §3 tells an author to *start from the corpus, never
//! from the schema*. Under that instruction the corpus **is** the language: a
//! construct no example uses does not exist in practice, whatever the IR
//! supports. So this module counts, over the rule library, how many times each
//! IR construct is written, and calls a zero what it is — a finding.
//!
//! It measures **demonstration, not expressiveness.** A green verdict means no
//! part of the language is undemonstrated by an example. It is **not** evidence
//! that an author can build any particular thing, and no document, PR or review
//! may cite it as such. Conflating the two would be this project's own recurring
//! vacuity one level up: a number printed beside the word "pass", believed to
//! have checked something it never looked at. The claim is carried in the report
//! itself ([`Report::measures`]) so it travels with the number rather than
//! living in a doc a reader of the number never opens.
//!
//! # Why the construct list is not a list
//!
//! The measurement in spec-0033 §1 was made by hand once. A hand-kept list of
//! constructs would go stale in exactly the way the hand measurement did, and
//! silently: the next `Node` variant would simply never be counted, so it would
//! read as "not a gap" rather than "not looked at".
//!
//! So the kinds are generated by [`constructs!`] from one list that produces the
//! enum *and* its `ALL` slice, and each kind is assigned by an **exhaustive
//! match** over the IR type ([`NodeKind::of`], [`CondKind::of`],
//! [`PaintKind::of`]). Adding a variant to [`Node`], [`Cond`] or [`Paint`]
//! therefore **fails to compile** until someone classifies it, and a new kind
//! begins life at zero bindings — a surface nothing demonstrates is a finding on
//! the day it lands.
//!
//! # The corpus
//!
//! [`crate::library::PROGRAMS`] — every program `delve-grammar list` names and
//! `delve-grammar show --program <id>` can hand an author. The drowned-bell zone
//! programs are deliberately *not* in it: they are one campaign's composition,
//! unreachable from `list`, so a construct used only there is not demonstrated
//! to anybody. Counting them would turn a gap into a green.

use std::collections::{BTreeMap, BTreeSet};

use serde::Serialize;

use crate::ir::{Cond, Material, Node, Paint, Program};
use crate::library::LibraryProgram;

// ---------------------------------------------------------------------------
// The construct kinds — generated, so the enum and its enumeration cannot drift
// ---------------------------------------------------------------------------

/// Declare a construct-kind enum together with the slice of all its members.
///
/// Both come from one list, so a kind that exists is a kind that is counted:
/// there is no second place to forget to update. What is left hand-written is
/// the `of()` match beside each enum, which is exhaustive over the IR type — the
/// classification the spec requires a person to make.
macro_rules! constructs {
    (
        $(#[$meta:meta])*
        $vis:vis enum $name:ident {
            $( $(#[$vmeta:meta])* $variant:ident = $id:literal ),+ $(,)?
        }
    ) => {
        $(#[$meta])*
        #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
        $vis enum $name {
            $( $(#[$vmeta])* $variant ),+
        }

        impl $name {
            /// Every kind, in declaration order. Generated from the same list as
            /// the variants themselves.
            $vis const ALL: &'static [$name] = &[ $( $name::$variant ),+ ];

            /// The stable id this kind is reported under.
            $vis fn id(self) -> &'static str {
                match self {
                    $( $name::$variant => $id ),+
                }
            }
        }
    };
}

constructs! {
    /// One kind of [`Node`] — a step of a rule body.
    pub enum NodeKind {
        /// [`Node::Fill`].
        Fill = "node:fill",
        /// [`Node::Void`].
        Void = "node:void",
        /// [`Node::Skip`].
        Skip = "node:skip",
        /// [`Node::Call`].
        Call = "node:call",
        /// [`Node::Split`].
        Split = "node:split",
        /// [`Node::Reorient`].
        Reorient = "node:reorient",
        /// [`Node::Mark`].
        Mark = "node:mark",
        /// [`Node::Bind`].
        Bind = "node:bind",
    }
}

impl NodeKind {
    /// Classify one node.
    ///
    /// Exhaustive on purpose: a new [`Node`] variant stops this compiling, and
    /// nothing — not a build, not a test, not the CI step — proceeds until
    /// someone says which kind it is.
    pub fn of(node: &Node) -> NodeKind {
        match node {
            Node::Fill { .. } => NodeKind::Fill,
            Node::Void => NodeKind::Void,
            Node::Skip => NodeKind::Skip,
            Node::Call { .. } => NodeKind::Call,
            Node::Split(_) => NodeKind::Split,
            Node::Reorient { .. } => NodeKind::Reorient,
            Node::Mark { .. } => NodeKind::Mark,
            Node::Bind { .. } => NodeKind::Bind,
        }
    }
}

constructs! {
    /// One kind of [`Cond`] — a rule guard.
    pub enum CondKind {
        /// [`Cond::Always`].
        Always = "cond:always",
        /// [`Cond::Otherwise`].
        Otherwise = "cond:otherwise",
        /// [`Cond::Cmp`].
        Cmp = "cond:cmp",
        /// [`Cond::All`].
        All = "cond:all",
        /// [`Cond::Any`].
        Any = "cond:any",
        /// [`Cond::NoneOf`].
        NoneOf = "cond:none_of",
        /// [`Cond::Orientation`].
        Orientation = "cond:orientation",
    }
}

impl CondKind {
    /// Classify one guard. Exhaustive, for the reason [`NodeKind::of`] is.
    pub fn of(cond: &Cond) -> CondKind {
        match cond {
            Cond::Always => CondKind::Always,
            Cond::Otherwise => CondKind::Otherwise,
            Cond::Cmp { .. } => CondKind::Cmp,
            Cond::All { .. } => CondKind::All,
            Cond::Any { .. } => CondKind::Any,
            Cond::NoneOf { .. } => CondKind::NoneOf,
            Cond::Orientation { .. } => CondKind::Orientation,
        }
    }
}

constructs! {
    /// One kind of [`Paint`] — what a palette role or an inline material
    /// resolves to.
    pub enum PaintKind {
        /// [`Paint::Block`].
        Block = "paint:block",
        /// [`Paint::Mix`] — the only per-cell material variation the language
        /// has.
        Mix = "paint:mix",
    }
}

impl PaintKind {
    /// Classify one paint. Exhaustive, for the reason [`NodeKind::of`] is.
    pub fn of(paint: &Paint) -> PaintKind {
        match paint {
            Paint::Block(_) => PaintKind::Block,
            Paint::Mix(_) => PaintKind::Mix,
        }
    }
}

// ---------------------------------------------------------------------------
// The required set
// ---------------------------------------------------------------------------

/// **Constructs exempt from the required set**, each with the reason it is
/// exempt.
///
/// The required set is *every* construct — the shape `tools/check-dw-codes.py`
/// uses, and for its reason: a required set that is a chosen subset can be made
/// green by shrinking it, which is the one move the debug doctrine forbids. An
/// exemption is therefore a named, reasoned entry here and nowhere else.
///
/// Two ways this list is itself checked, so it cannot rot into a permission
/// slip: an entry naming a construct that does not exist is an error, and an
/// entry naming a construct the corpus *does* demonstrate is an error (delete
/// it — the exemption has been paid off).
///
/// It is empty. That is a statement about the corpus, not about the language.
pub const EXEMPT: &[(&str, &str)] = &[];

/// What a green verdict does and does not say. Carried in every report, printed
/// on every run, and repeated in `docs/reference/grammar.md`, because a number
/// travels further than the page that qualifies it.
pub const MEASURES: &str = "This report measures DEMONSTRATION, not expressiveness. A pass means \
                            no part of the IR is left undemonstrated by the corpus an author is \
                            sent to. It is NOT evidence that an author can build any particular \
                            thing, and no document, PR or review may cite it as such.";

// ---------------------------------------------------------------------------
// The report
// ---------------------------------------------------------------------------

/// One construct's standing in the corpus.
///
/// Shaped like [`crate::gates::Gate`] on purpose — same fields, same meaning of
/// `bound`, same rule that a zero binding is a finding rather than a quiet pass
/// — so a reader who has read one report can read this one.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct Construct {
    /// Stable id, e.g. `node:skip`.
    pub id: &'static str,
    /// True when the corpus demonstrates it, or when it is exempt.
    pub pass: bool,
    /// **How many times the corpus writes it.** Zero is a finding.
    pub bound: usize,
    /// Why it is exempt, when it is.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exempt: Option<&'static str>,
    /// What was found, in one line.
    pub detail: String,
}

/// Numbers with no threshold. Not gates, and deliberately not presented as any.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct Measurements {
    /// Programs scanned.
    pub programs: usize,
    /// Rules across those programs.
    pub rules: usize,
    /// Rule alternatives.
    pub alternatives: usize,
    /// [`Node`]s in every rule body.
    pub ir_nodes: usize,
    /// Palette roles bound across the corpus.
    pub palette_roles: usize,
    /// Roles bound to a mix that includes `minecraft:air` — erosion. Reported
    /// rather than gated: "is air a legal member of a mix" is a property of
    /// [`PaintKind::Mix`], which *is* gated, and inventing a second threshold
    /// for how a mix is composed would be a fabricated gate.
    pub mixes_containing_air: usize,
    /// Distinct block states named anywhere in the corpus.
    pub distinct_block_states: usize,
}

/// The whole verdict over one corpus.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct Report {
    /// `"pass"` when every required construct is demonstrated, else `"fail"`.
    pub verdict: &'static str,
    /// [`MEASURES`] — what a pass claims, and what it does not.
    pub measures: &'static str,
    /// The program ids scanned, in the order the library lists them.
    pub corpus: Vec<String>,
    /// Every construct, in a fixed order.
    pub constructs: Vec<Construct>,
    /// Numbers, no verdicts.
    pub measurements: Measurements,
    /// Things a reader must be told: a construct nothing demonstrates, an
    /// exemption that has outlived its reason, an empty corpus.
    pub findings: Vec<String>,
}

impl Report {
    /// True when every required construct is demonstrated.
    pub fn is_pass(&self) -> bool {
        self.verdict == "pass"
    }

    /// Canonical pretty JSON with a trailing newline.
    pub fn to_json(&self) -> String {
        let mut s = serde_json::to_string_pretty(self).expect("a coverage report serialises");
        s.push('\n');
        s
    }
}

// ---------------------------------------------------------------------------
// Counting
// ---------------------------------------------------------------------------

#[derive(Default)]
struct Tally {
    /// Construct id to (occurrences, the programs that write it).
    seen: BTreeMap<&'static str, (usize, BTreeSet<String>)>,
    current: String,
    m: Counts,
}

#[derive(Default)]
struct Counts {
    programs: usize,
    rules: usize,
    alternatives: usize,
    ir_nodes: usize,
    palette_roles: usize,
    mixes_containing_air: usize,
    blocks: BTreeSet<String>,
}

impl Tally {
    fn hit(&mut self, id: &'static str) {
        let e = self.seen.entry(id).or_default();
        e.0 += 1;
        e.1.insert(self.current.clone());
    }

    fn node(&mut self, node: &Node) {
        self.m.ir_nodes += 1;
        self.hit(NodeKind::of(node).id());
        // A second exhaustive match, and it earns its keep: this one is what
        // makes the *walk* total. A new variant carrying a child body that this
        // arm forgot would count itself and hide everything under it.
        match node {
            Node::Fill { material } => match material {
                // A role's paint is counted once where it is bound, not once per
                // use: "how many roles are a mix" is the question spec-0033 §1
                // asked, and counting uses would let one mix used fifty times
                // read as fifty demonstrations.
                Material::Role { .. } => {}
                Material::Inline(paint) => self.paint(paint),
            },
            Node::Void | Node::Skip | Node::Call { .. } => {}
            Node::Reorient { body, .. } | Node::Mark { body, .. } => self.node(body),
            Node::Bind { palette, body, .. } => {
                // A rebinding to an inline paint is a paint demonstration for
                // the same reason a `fill` of one is; a rebinding to another
                // role is counted where that role is bound, as everywhere else.
                for material in palette.values() {
                    if let Material::Inline(paint) = material {
                        self.paint(paint);
                    }
                }
                self.node(body);
            }
            Node::Split(split) => {
                for child in &split.children {
                    self.node(child);
                }
            }
        }
    }

    fn cond(&mut self, cond: &Cond) {
        self.hit(CondKind::of(cond).id());
        match cond {
            Cond::Always | Cond::Otherwise | Cond::Cmp { .. } | Cond::Orientation { .. } => {}
            Cond::All { of } | Cond::Any { of } | Cond::NoneOf { of } => {
                for sub in of {
                    self.cond(sub);
                }
            }
        }
    }

    fn paint(&mut self, paint: &Paint) {
        self.hit(PaintKind::of(paint).id());
        match paint {
            Paint::Block(b) => {
                self.m.blocks.insert(b.to_string());
            }
            Paint::Mix(mix) => {
                if mix.iter().any(|w| w.block.is_air()) {
                    self.m.mixes_containing_air += 1;
                }
                for w in mix {
                    self.m.blocks.insert(w.block.to_string());
                }
            }
        }
    }

    fn program(&mut self, id: &str, program: &Program) {
        self.current = id.to_string();
        self.m.programs += 1;
        for paint in program.palette.values() {
            self.m.palette_roles += 1;
            self.paint(paint);
        }
        for alts in program.rules.values() {
            self.m.rules += 1;
            for alt in alts {
                self.m.alternatives += 1;
                self.cond(&alt.when);
                self.node(&alt.body);
            }
        }
    }
}

/// Measure demonstration coverage over a corpus of programs.
///
/// `corpus` is [`crate::library::PROGRAMS`] in every caller that matters; it is
/// a parameter so a test can measure a corpus it wrote itself, which is the only
/// way to red-demo a zero on a language surface the library happens to cover.
pub fn measure(corpus: &[LibraryProgram]) -> Report {
    measure_with(corpus, EXEMPT)
}

/// [`measure`], against a given allowlist.
///
/// The live allowlist is empty, so the two rules that keep it from rotting into
/// a permission slip — an exemption excuses a zero and nothing else, and an
/// exemption naming no construct is itself an error — have nothing in the build
/// to happen to. Passing the list in is what lets a test put an entry in front
/// of them and watch them fire, instead of asserting a value it wrote itself.
fn measure_with(corpus: &[LibraryProgram], allowlist: &[(&'static str, &'static str)]) -> Report {
    let mut tally = Tally::default();
    let mut ids = Vec::new();
    for (id, build) in corpus {
        ids.push((*id).to_string());
        tally.program(id, &build());
    }

    let exempt: BTreeMap<&str, &str> = allowlist.iter().copied().collect();
    let all: Vec<&'static str> = NodeKind::ALL
        .iter()
        .map(|k| k.id())
        .chain(CondKind::ALL.iter().map(|k| k.id()))
        .chain(PaintKind::ALL.iter().map(|k| k.id()))
        .collect();

    let mut findings = Vec::new();
    let mut constructs = Vec::new();
    for id in &all {
        let (bound, programs) = tally
            .seen
            .get(id)
            .map(|(n, p)| (*n, p.clone()))
            .unwrap_or_default();
        let reason = exempt.get(id).copied();
        if bound == 0 {
            findings.push(format!(
                "construct `{id}` has ZERO bindings in the corpus — no example writes it, so for \
                 an author following prefab-procedure.md §3 it does not exist{}",
                match reason {
                    Some(why) => format!(" (exempt: {why})"),
                    None => String::new(),
                }
            ));
        } else if let Some(why) = reason {
            findings.push(format!(
                "construct `{id}` is on the exemption allowlist but the corpus demonstrates it {} \
                 time(s) — delete the entry, its reason ({why}) has been paid off",
                bound
            ));
        }
        constructs.push(Construct {
            id,
            // An exemption excuses a zero and nothing else. A demonstrated
            // construct carrying a stale exemption still fails, so the allowlist
            // can only ever shrink on its own.
            pass: if bound == 0 {
                reason.is_some()
            } else {
                reason.is_none()
            },
            bound,
            exempt: reason,
            detail: if bound == 0 {
                "no example in the corpus writes it".to_string()
            } else {
                format!("{bound} use(s) in {}", name_list(&programs))
            },
        });
    }

    for (id, why) in allowlist {
        if !all.contains(id) {
            findings.push(format!(
                "exemption `{id}` ({why}) names no construct this build knows — a renamed or \
                 deleted IR variant left it behind"
            ));
            constructs.push(Construct {
                id,
                pass: false,
                bound: 0,
                exempt: Some(why),
                detail: "not a construct of this IR".to_string(),
            });
        }
    }

    if tally.m.programs == 0 {
        findings.push(
            "the corpus is EMPTY — every count below is zero because nothing was scanned, not \
             because nothing is demonstrated"
                .to_string(),
        );
    }

    let verdict = if tally.m.programs > 0 && constructs.iter().all(|c| c.pass) {
        "pass"
    } else {
        "fail"
    };
    Report {
        verdict,
        measures: MEASURES,
        corpus: ids,
        constructs,
        measurements: Measurements {
            programs: tally.m.programs,
            rules: tally.m.rules,
            alternatives: tally.m.alternatives,
            ir_nodes: tally.m.ir_nodes,
            palette_roles: tally.m.palette_roles,
            mixes_containing_air: tally.m.mixes_containing_air,
            distinct_block_states: tally.m.blocks.len(),
        },
        findings,
    }
}

/// The programs that demonstrate a construct, named rather than counted — an
/// author is being told where to go and look.
fn name_list(programs: &BTreeSet<String>) -> String {
    const SHOWN: usize = 4;
    let names: Vec<&str> = programs.iter().map(|s| s.as_str()).collect();
    if names.len() <= SHOWN {
        names.join(", ")
    } else {
        format!(
            "{} and {} more",
            names[..SHOWN].join(", "),
            names.len() - SHOWN
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::block::BlockState;
    use crate::ir::{Alternative, Material, WeightedBlock};
    use crate::library;

    fn empty() -> Program {
        Program::new("nothing", "all").rule("all", Node::Void)
    }

    /// Every kind reaches the report, and the ids are the ones a reader greps
    /// for. This is the list that would otherwise be hand-kept.
    #[test]
    fn every_construct_kind_appears_in_the_report() {
        let report = measure(&[("empty", empty)]);
        let ids: Vec<&str> = report.constructs.iter().map(|c| c.id).collect();
        assert_eq!(
            ids.len(),
            NodeKind::ALL.len() + CondKind::ALL.len() + PaintKind::ALL.len()
        );
        for wanted in ["node:skip", "cond:none_of", "paint:mix", "node:fill"] {
            assert!(ids.contains(&wanted), "{ids:?}");
        }
    }

    /// A zero is a finding and a red, both, and it says where an author would
    /// have looked. This is the whole point of the report, demonstrated on a
    /// corpus small enough to reason about.
    #[test]
    fn a_construct_no_example_writes_is_a_finding_and_a_red() {
        let report = measure(&[("empty", empty)]);
        assert!(!report.is_pass());
        let skip = report
            .constructs
            .iter()
            .find(|c| c.id == "node:skip")
            .unwrap();
        assert_eq!(skip.bound, 0);
        assert!(!skip.pass);
        assert!(
            report
                .findings
                .iter()
                .any(|f| f.contains("`node:skip`") && f.contains("ZERO")),
            "{:?}",
            report.findings
        );
        let void = report
            .constructs
            .iter()
            .find(|c| c.id == "node:void")
            .unwrap();
        assert_eq!(void.bound, 1);
        assert!(void.pass);
        assert_eq!(void.detail, "1 use(s) in empty");
    }

    /// Counting reaches inside every wrapper: a construct written under a
    /// `mark`, under a `reorient`, inside a split child or inside a nested guard
    /// is demonstrated, and a walk that stopped at the wrapper would report it
    /// as a gap.
    #[test]
    fn the_walk_reaches_under_every_wrapper() {
        fn nested() -> Program {
            use crate::geom::Axis;
            use crate::ir::{CmpOp, DimRef, Expr, Mark, MarkAt, Reorient, Size, Split};
            let deep = Node::Mark {
                mark: Mark::new("here", MarkAt::FloorCenter),
                body: Box::new(Node::Reorient {
                    orient: Reorient::KEEP,
                    body: Box::new(Node::Split(Split {
                        axis: Axis::Y,
                        sizes: vec![Size::abs(1), Size::rel(1)],
                        rounding: Default::default(),
                        repeat: false,
                        orient: Reorient::KEEP,
                        children: vec![Node::Skip, Node::Void],
                    })),
                }),
            };
            Program::new("nested", "all").rule_alts(
                "all",
                vec![Alternative::new(deep).when(Cond::NoneOf {
                    of: vec![Cond::Any {
                        of: vec![Cond::cmp(Expr::dim(DimRef::X), CmpOp::Lt, Expr::int(2))],
                    }],
                })],
            )
        }
        let report = measure(&[("nested", nested)]);
        let bound = |id: &str| report.constructs.iter().find(|c| c.id == id).unwrap().bound;
        assert_eq!(bound("node:skip"), 1, "under mark/reorient/split");
        assert_eq!(bound("cond:cmp"), 1, "under none_of/any");
        assert_eq!(bound("cond:none_of"), 1);
        assert_eq!(bound("cond:any"), 1);
        assert_eq!(report.measurements.ir_nodes, 5);
    }

    /// A mix is counted where it is BOUND, once, however often it is filled —
    /// spec-0033 §1's question was "how many roles are a mix", and fifty uses of
    /// one mix are one demonstration.
    #[test]
    fn a_mix_counts_once_per_binding_and_air_in_it_is_measured() {
        fn eroded() -> Program {
            Program::new("eroded", "all")
                .role_mix(
                    "wall",
                    vec![
                        WeightedBlock {
                            weight: 3,
                            block: BlockState::simple("minecraft:stone_bricks"),
                        },
                        WeightedBlock {
                            weight: 1,
                            block: BlockState::simple("minecraft:air"),
                        },
                    ],
                )
                .rule("all", Node::fill("wall"))
                .rule("again", Node::fill("wall"))
        }
        let report = measure(&[("eroded", eroded)]);
        let mix = report
            .constructs
            .iter()
            .find(|c| c.id == "paint:mix")
            .unwrap();
        assert_eq!(mix.bound, 1, "two fills of one role are one bound mix");
        assert_eq!(report.measurements.mixes_containing_air, 1);
        assert_eq!(report.measurements.palette_roles, 1);
        assert_eq!(report.measurements.distinct_block_states, 2);
    }

    /// An inline paint is a demonstration too — a program that never binds a
    /// role still shows the reader what a paint is.
    #[test]
    fn an_inline_paint_counts() {
        fn inline() -> Program {
            Program::new("inline", "all").rule(
                "all",
                Node::Fill {
                    material: Material::block(BlockState::simple("minecraft:stone")),
                },
            )
        }
        let report = measure(&[("inline", inline)]);
        assert_eq!(
            report
                .constructs
                .iter()
                .find(|c| c.id == "paint:block")
                .unwrap()
                .bound,
            1
        );
    }

    /// An exemption excuses a zero — and nothing else.
    #[test]
    fn an_exemption_excuses_a_zero() {
        let why = "no example writes it yet, and here is why that is acceptable";
        let report = measure_with(&[("empty", empty)], &[("node:skip", why)]);
        let skip = report
            .constructs
            .iter()
            .find(|c| c.id == "node:skip")
            .unwrap();
        assert_eq!(skip.bound, 0);
        assert!(skip.pass, "an exempt zero does not red");
        assert_eq!(skip.exempt, Some(why));
        // Still a finding: the exemption is a decision to live with a gap, not a
        // claim there is none. It is named on every run so it cannot go quiet.
        assert!(
            report
                .findings
                .iter()
                .any(|f| f.contains("`node:skip`") && f.contains(why)),
            "{:?}",
            report.findings
        );
        // `node:void` is still the only other thing this corpus writes, so the
        // verdict is still red — an exemption moves one construct, not the bar.
        assert!(!report.is_pass());
    }

    /// The allowlist can only ever shrink: an exemption whose construct the
    /// corpus demonstrates is a red, not a silent pass.
    #[test]
    fn an_exemption_that_has_been_paid_off_is_a_red() {
        let report = measure_with(&[("empty", empty)], &[("node:void", "stale reason")]);
        let void = report
            .constructs
            .iter()
            .find(|c| c.id == "node:void")
            .unwrap();
        assert_eq!(void.bound, 1, "the corpus DOES write it");
        assert!(
            !void.pass,
            "so the exemption has been paid off and must red"
        );
        assert!(
            report
                .findings
                .iter()
                .any(|f| f.contains("`node:void`") && f.contains("paid off")),
            "{:?}",
            report.findings
        );
    }

    /// An exemption naming no construct — a renamed or deleted IR variant left
    /// it behind — is a red on its own, so the allowlist cannot outlive the IR.
    #[test]
    fn an_exemption_for_a_construct_that_does_not_exist_is_a_red() {
        let report = measure_with(&[("empty", empty)], &[("node:teleport", "invented")]);
        assert!(!report.is_pass());
        let ghost = report
            .constructs
            .iter()
            .find(|c| c.id == "node:teleport")
            .unwrap();
        assert!(!ghost.pass);
        assert!(
            report
                .findings
                .iter()
                .any(|f| f.contains("`node:teleport`") && f.contains("names no construct")),
            "{:?}",
            report.findings
        );
    }

    /// An empty corpus is not a pass. The report says the zeros mean "nothing
    /// was scanned", which is the unbound vacuity mode CLAUDE.md names.
    #[test]
    fn an_empty_corpus_is_a_finding_not_a_pass() {
        let report = measure(&[]);
        assert!(!report.is_pass());
        assert!(
            report
                .findings
                .iter()
                .any(|f| f.contains("corpus is EMPTY")),
            "{:?}",
            report.findings
        );
    }

    /// The non-claim travels with the number: it is a field of the report and of
    /// its JSON, not a line in a document the reader of the number never opens.
    #[test]
    fn the_report_carries_its_own_non_claim() {
        let report = measure(&library::PROGRAMS[..1]);
        assert!(
            report
                .measures
                .contains("DEMONSTRATION, not expressiveness")
        );
        assert!(report.to_json().contains("not expressiveness"));
    }

    /// **The required set has no zero bindings.**
    ///
    /// This is spec-0033 §4.3, and it is the reason the report exists rather
    /// than being a thing someone remembers to run: it is bound to `cargo test`,
    /// which is bound to the required `rust (fmt, clippy, test)` job, so a
    /// corpus change cannot be pushed without it.
    #[test]
    fn the_library_corpus_demonstrates_every_required_construct() {
        let report = measure(library::PROGRAMS);
        assert!(
            report.is_pass(),
            "{}\n\n{}",
            report.findings.join("\n"),
            MEASURES
        );
    }
}
