//! The horizon model (spec-0026): the one place a campaign's resolved stage-1
//! `horizon` becomes **declared physical facts** the rest of the compiler
//! reads. Nothing outside this module matches on
//! [`HorizonBase`](delvewright_dsl::HorizonBase) to decide world physics — a
//! consumer asks here, or asks
//! [`horizon_base`](delvewright_dsl::horizon_base) for the base and nothing
//! else.
//!
//! # The two kinds of horizon, and why the difference is structural
//!
//! `void` and `ocean` are **generator settings**: the world outside the placed
//! geometry is an analytic fact, one superflat layer stack, and the compiler
//! models it as [`nav::Ambient`](crate::nav::Ambient) — a per-column answer
//! computed rather than stored.
//!
//! `valley` is **built terrain**. Its ground is real blocks in real structure
//! templates, generated by [`crate::surround`] and placed by the same bootstrap
//! that places every other piece. Its ambient is therefore `void`: there is
//! nothing analytic out there, because everything out there was built.
//!
//! That difference is the whole design. A surround that entered as a new
//! `Ambient` variant would owe a new branch to gravity settling, the occupancy
//! model, relight, boundary safety, the fluid model and the snapshot renderer,
//! and each of those branches would be a second model of the same ground that
//! could disagree with the first. A surround that enters as **placed blocks**
//! owes none of them: every proof already knows how to read a placed block.
//!
//! # Where the surround stands
//!
//! Around the map, never inside it — and *the map* is a fact the campaign
//! states, not one the surround derives from the parts it finds. For a
//! campaign with a site plan that is the plan's `region`, the whole map's one
//! region and its design of record; for a campaign that places areas by hand
//! it is the union of the placed footprints, which is the only statement of
//! extent such a campaign has. See [`crate::plan::surround_rect`].
//!
//! Reading the region rather than the placed pieces is deliberate and is the
//! ordering spec-0049 exists to hold: a box may never grow the region
//! (`DW0826`), so a surround keyed to the region can never be pushed outward by
//! a part, and the space a plan reserved and did not fill stays reserved
//! instead of being eaten by terrain.

use delvewright_dsl::{Campaign, HorizonBase, ResolvedHorizon, horizon_base, resolved_horizon};

/// The resolved horizon of a campaign — defaults applied, `void` when absent.
pub fn of_campaign(campaign: &Campaign) -> ResolvedHorizon {
    resolved_horizon(&campaign.world.content.horizon)
}

/// The resolved base of a campaign's horizon.
pub fn base_of(campaign: &Campaign) -> HorizonBase {
    horizon_base(&campaign.world.content.horizon)
}

/// Sea level of the `ocean` superflat: the pinned bedrock/stone/water layer
/// stack (1 + 118 + 8 from the −64 build floor) tops the water at y=62.
/// Emission pins the same stack in `generator-settings`.
pub const SEA_LEVEL: i32 = crate::plan::SEA_LEVEL;

/// The top solid block of a `valley`'s **gap floor** — the flat ground between
/// the map's edge and the foot of the inner slopes.
///
/// Pinned one block under [`crate::plan::BASE_Y`], which is the same
/// relationship a grass plain would have: a `walk_y = 0` piece placed at
/// `BASE_Y` stands exactly on this floor. That is why a valley relocates
/// nothing — a campaign that swaps `void` for `valley` moves no piece, it only
/// gains ground to stand beside.
pub const VALLEY_GAP_FLOOR_TOP_Y: i32 = crate::plan::BASE_Y - 1;

/// The seed stream the valley surround draws from (ADR-0006 named streams).
/// Fixed here rather than at the call site so a re-seeding of one build cannot
/// silently become a re-seeding of a different one.
pub const VALLEY_STREAM: &str = "horizon/valley";

#[cfg(test)]
mod tests {
    use super::*;

    /// The relationship the module doc claims, asserted rather than described:
    /// a valley's gap floor tops exactly one block under the void datum, so a
    /// piece placed at `BASE_Y` stands on it.
    #[test]
    fn a_valley_relocates_nothing() {
        assert_eq!(VALLEY_GAP_FLOOR_TOP_Y + 1, crate::plan::BASE_Y);
    }

    /// `has_surround` is the question every consumer asks, and it must answer
    /// for the whole enum rather than for the base that happens to build
    /// terrain today.
    #[test]
    fn only_valley_builds_terrain() {
        assert!(!HorizonBase::Void.has_surround());
        assert!(!HorizonBase::Ocean.has_surround());
        assert!(HorizonBase::Valley.has_surround());
    }
}
