//! **Stage 6: a place is detailed inside the box the whole gave it**
//! (spec-0050).
//!
//! # Why the pieces here are cut out of the massing
//!
//! Every detail piece in this file is generated by **taking the cells the
//! derivation would have written inside that place's frame and shipping them as
//! a `.nbt`**. That is not a shortcut, it is the sharpest instrument available
//! for the property stage 6 has to hold: *detailing a place must not change
//! whether the map is walkable*. A piece cut from the massing makes the built
//! world byte-for-byte the massed world — so the whole stage-5 battery
//! runs over it unchanged, and if the fabric split were off by a single cell on
//! any face, the substituted world would differ from the massed one and
//! `DW0836`/`DW0837`/`DW0838` would say so.
//!
//! It also means every red below is produced by **perturbing a piece that was
//! green**, never by hand-authoring a broken one: the same discipline
//! `tests/blockout.rs` applies to the derivation, one layer out.
//!
//! The generator is fed by `delvec allocation` and nothing else — the frame, the
//! seams, the answering-face classes and the owed names all come from the
//! handing. So the file doubles as the demonstration that the handing is
//! *sufficient*: a piece written against it alone satisfies every gate.

mod common;

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use delvec::compiler::blockout::{self, Perturb};
use delvec::compiler::detail::{self, Allocation};
use delvec::compiler::plan::Plan;
use delvec::compiler::registry::PrefabRegistry;
use delvewright_dsl::{Campaign, DSL_VERSION, NodeId, Severity};

// ---------------------------------------------------------------------------
// The fixture, and the pieces cut out of its massing
// ---------------------------------------------------------------------------

fn blockout_dir() -> PathBuf {
    common::repo_root().join("crates/delvec/tests/fixtures/blockout")
}

fn campaign_at(dir: &Path) -> Campaign {
    common::campaign_at(dir)
}

/// The whole map's massing as a cell map, replayed in write order exactly as the
/// world applies it — the derivation the build runs, so a bound place's frame is
/// left empty.
fn massing(c: &Campaign) -> BTreeMap<[i64; 3], String> {
    let mut reads = delvewright_dsl::metrics::Reads::new();
    let (placement, _) = blockout::derive(c, &mut reads).expect("a site-plan campaign has massing");
    let fills = placement.mass;
    let mut out: BTreeMap<[i64; 3], String> = BTreeMap::new();
    for f in &fills {
        let lo = [
            i64::from(f.from[0]),
            i64::from(f.from[1]),
            i64::from(f.from[2]),
        ];
        let hi = [i64::from(f.to[0]), i64::from(f.to[1]), i64::from(f.to[2])];
        for cell in blockout::cells_of(lo, hi) {
            if f.block == "minecraft:air" {
                out.remove(&cell);
            } else {
                out.insert(cell, f.block.clone());
            }
        }
    }
    out
}

/// [`massing`] with nothing bound: the cells the derivation writes in every
/// place, which is what a piece is cut out of.
fn unbound_massing(c: &Campaign) -> BTreeMap<[i64; 3], String> {
    let mut c = c.clone();
    c.detail_plan = None;
    massing(&c)
}

/// A place's cells, piece-local, with air stated rather than omitted — which is
/// what a real exported piece does, and what makes the substitution total.
///
/// **Plus its own light**, and that is not decoration: spec-0050 §3 takes a bound
/// frame out of the whole's fixture pass, because the whole hanging torches
/// inside a building somebody designed would be the whole writing inside a bound
/// frame. A bound place lights itself and the existing gate judges it — so a
/// piece cut from the massing alone is a dark room, `DW0210` says so, and the
/// repair is the one a real detail piece makes. Torches on a four-cell grid over
/// the walk plane, never inside a seam's own cells.
fn piece_cells(
    c: &Campaign,
    a: &Allocation,
    mass: &BTreeMap<[i64; 3], String>,
) -> Vec<([i32; 3], String)> {
    let _ = c;
    let in_a_seam = |p: [i64; 3]| {
        a.seams.iter().any(|s| {
            (0..3).all(|i| {
                p[i] >= s.cells[0][i].min(s.cells[1][i]) && p[i] <= s.cells[0][i].max(s.cells[1][i])
            })
        })
    };
    let mut out = Vec::new();
    for x in 0..a.extent[0] {
        for y in 0..a.extent[1] {
            for z in 0..a.extent[2] {
                let world = [a.world_min[0] + x, a.world_min[1] + y, a.world_min[2] + z];
                let mut block = mass
                    .get(&world)
                    .cloned()
                    .unwrap_or_else(|| "minecraft:air".to_string());
                let lit_here = y == 1 && x % 4 == 1 && z % 4 == 1;
                if lit_here && block == "minecraft:air" && !in_a_seam([x, y, z]) {
                    block = "minecraft:torch".to_string();
                }
                out.push(([x as i32, y as i32, z as i32], block));
            }
        }
    }
    out
}

/// The first cell a body can stand in, in piece-local coordinates: own cell and
/// the one above clear, the one below solid. Scanned in a fixed order so two
/// runs choose the same cell.
fn standing_cell(a: &Allocation, cells: &[([i32; 3], String)]) -> [i32; 3] {
    let solid: std::collections::BTreeSet<[i32; 3]> = cells
        .iter()
        .filter(|(_, b)| b != "minecraft:air")
        .map(|(p, _)| *p)
        .collect();
    for y in 1..a.extent[1] as i32 {
        for x in 0..a.extent[0] as i32 {
            for z in 0..a.extent[2] as i32 {
                if !solid.contains(&[x, y, z])
                    && !solid.contains(&[x, y + 1, z])
                    && solid.contains(&[x, y - 1, z])
                {
                    return [x, y, z];
                }
            }
        }
    }
    panic!("`{}` offers nowhere to stand", a.place);
}

/// Write the piece a place's allocation asks for, cut out of the massing.
///
/// Everything the metadata claims comes from the allocation: the size is the
/// frame's extent, one face per allocated seam at the cells and class the
/// handing named, and one point anchor standing in the piece's own declared
/// space.
fn write_piece(dir: &Path, id: &str, a: &Allocation, cells: &[([i32; 3], String)]) {
    std::fs::create_dir_all(dir).unwrap();
    let refs: Vec<([i32; 3], &str)> = cells.iter().map(|(p, b)| (*p, b.as_str())).collect();
    let size = [a.extent[0] as i32, a.extent[1] as i32, a.extent[2] as i32];
    std::fs::write(
        dir.join(format!("{id}.nbt")),
        common::structure_nbt(size, &refs),
    )
    .unwrap();
    let seat = standing_cell(a, cells);
    let faces: Vec<serde_json::Value> = a
        .seams
        .iter()
        .map(|s| {
            serde_json::json!({
                "space": "room",
                "class": s.answer_with[0],
                "dir": s.face,
                "opening": { "from": s.cells[0], "to": s.cells[1] },
            })
        })
        .collect();
    let anchors: serde_json::Map<String, serde_json::Value> = a
        .owed_anchors
        .iter()
        .enumerate()
        .map(|(i, _)| {
            (
                format!("seat{i}"),
                serde_json::json!({
                    "pos": seat,
                    "facing": "north",
                    "resolves_to": "space:room",
                }),
            )
        })
        .collect();
    let meta = serde_json::json!({
        "prefab_id": format!("prefab/{id}"),
        "structure": {
            "file": format!("{id}.nbt"),
            "id": id,
            "size": size,
            "data_version": 4671,
            "generator": "crates/delvec/tests/detail.rs",
        },
        "anchors": anchors,
        "connectors": [],
        "lighting": { "profile": "lit", "measured_min_light": 8, "measured": "2026-08-21" },
        "license": {
            "source": "original",
            "spdx": "GPL-3.0-or-later",
            "note": "Test fixture.",
            "provenance": "Cut out of the derived massing by crates/delvec/tests/detail.rs."
        },
        "spatial_contract": {
            "entry": "room",
            "spaces": {
                "room": {
                    "envelope": "enclosed",
                    "boxes": [{ "from": [0, 1, 0], "to": [size[0] - 1, size[1] - 1, size[2] - 1] }],
                },
            },
            "no_body": {},
            "edges": [],
            "faces": faces,
        },
    });
    std::fs::write(
        dir.join(format!("{id}.json")),
        serde_json::to_string_pretty(&meta).unwrap() + "\n",
    )
    .unwrap();
    // A detail piece cut out of the derived massing stands in a site-plan world
    // whose party gets outdoors, so `DW0885` asks it which of its sides are
    // finished surface. These are free-standing boxes in a `void` world: every
    // side that has a block on it is one the player would see.
    common::declare_shown_faces(dir, id);
}

/// What a green stage-6 campaign looks like on disk.
struct Detailed {
    campaign: PathBuf,
    prefabs: PathBuf,
}

/// Materialise the blockout fixture with `nodes` bound to pieces cut from its own
/// massing.
fn detailed(root: &Path, nodes: &[&str]) -> Detailed {
    let campaign = root.join("campaign");
    let prefabs = root.join("prefabs");
    std::fs::create_dir_all(&prefabs).unwrap();
    common::copy_dir_all(&blockout_dir(), &campaign);
    let c = campaign_at(&campaign);
    let mass = unbound_massing(&c);

    let mut details = Vec::new();
    for node in nodes {
        let id = node.split('/').nth(1).unwrap();
        let a = detail::allocation(&c, &NodeId((*node).to_string()))
            .unwrap_or_else(|| panic!("`{node}` is a place this map has"));
        let cells = piece_cells(&c, &a, &mass);
        write_piece(&prefabs, id, &a, &cells);
        let anchors: serde_json::Map<String, serde_json::Value> = a
            .owed_anchors
            .iter()
            .enumerate()
            .map(|(i, name)| (name.clone(), serde_json::json!(format!("seat{i}"))))
            .collect();
        details.push(serde_json::json!({
            "place": node,
            "piece": format!("prefab/{id}"),
            "anchors": anchors,
        }));
    }
    write_detail_plan(&campaign, &details);
    Detailed { campaign, prefabs }
}

fn write_detail_plan(dir: &Path, details: &[serde_json::Value]) {
    let doc = serde_json::json!({
        "campaign_id": "blockout",
        "content": {
            "palette": { "role/wall": "minecraft:stone_bricks", "role/floor": "minecraft:tuff" },
            "details": details,
        },
        "dsl_version": DSL_VERSION,
        "stage": "detail-plan",
    });
    std::fs::write(
        dir.join("detail-plan.json"),
        delvewright_dsl::to_canonical_string(&doc).unwrap(),
    )
    .unwrap();
}

/// Run the validation-tier detail checks over a materialised campaign.
fn check_at(d: &Detailed) -> (Vec<delvewright_dsl::Diagnostic>, detail::DetailBinding) {
    let c = campaign_at(&d.campaign);
    let reg = PrefabRegistry::load_dir(&d.prefabs).expect("the piece library loads");
    detail::check(&c, &reg)
}

fn codes(d: &[delvewright_dsl::Diagnostic]) -> Vec<String> {
    d.iter().map(|x| x.code.clone()).collect()
}

fn errors(d: &[delvewright_dsl::Diagnostic]) -> Vec<&delvewright_dsl::Diagnostic> {
    d.iter().filter(|x| x.severity == Severity::Error).collect()
}

/// Edit a bound piece's metadata in place.
fn patch_piece(d: &Detailed, id: &str, f: impl FnOnce(&mut serde_json::Value)) {
    common::patch_file(&d.prefabs.join(format!("{id}.json")), f);
}

fn patch_detail_plan(d: &Detailed, f: impl FnOnce(&mut serde_json::Value)) {
    common::patch_file(&d.campaign.join("detail-plan.json"), f);
}

/// Every place the blockout fixture declares, **read off the graph**.
///
/// It was a hand-written list of six, and a hand-written census of something
/// that grows is the shape `CLAUDE.md` warns about: the fixture gained a place
/// and the list did not, so `fully_detailed` quietly became false in the test
/// that exists to assert it is true. Derived, it cannot go stale, and a fixture
/// that gained a place gets it detailed for free.
fn every_place() -> Vec<String> {
    let c = campaign_at(&blockout_dir());
    c.layout_graph
        .as_ref()
        .expect("the blockout fixture carries a layout graph")
        .content
        .nodes
        .iter()
        .map(|n| n.id.0.clone())
        .collect()
}

// ---------------------------------------------------------------------------
// The green case, and what it binds
// ---------------------------------------------------------------------------

#[test]
fn a_bound_place_validates_and_states_its_binding() {
    let tmp = tempdir("green");
    let d = detailed(&tmp, &["node/exit"]);
    let (diags, binding) = check_at(&d);
    assert!(
        errors(&diags).is_empty(),
        "a piece cut from the massing satisfies every stage-6 gate: {:?}",
        codes(&diags)
    );
    assert_eq!(binding.rows, 1, "one row read");
    assert_eq!(binding.bound, 1, "and it bound a place");
    assert_eq!(binding.boxes, 7, "against the plan's seven boxes");
    assert_eq!(binding.measured, 1, "one piece measured against its frame");
    assert_eq!(binding.seams_required, 1, "`node/exit` has one seam");
    assert_eq!(binding.faces_examined, 1, "and the piece declares one face");
    assert_eq!(binding.owed, 1, "and owes one anchor name");
    assert!(
        binding
            .line()
            .contains("1 of 7 place(s) bound over 1 `details[]` row(s)"),
        "the count states its denominator: {}",
        binding.line()
    );
}

/// A campaign that carries no detail plan runs every check zero times **and says
/// so** — the standing treatment for a binding of zero.
#[test]
fn a_campaign_with_no_detail_plan_binds_zero_and_states_it() {
    let c = campaign_at(&blockout_dir());
    let reg = PrefabRegistry::load_dir(&common::shown_prefabs_dir("detail")).unwrap();
    let (diags, binding) = detail::check(&c, &reg);
    assert!(diags.is_empty(), "{:?}", codes(&diags));
    assert_eq!(binding.rows, 0);
    assert!(
        binding
            .line()
            .contains("0 of 0 place(s) bound over 0 `details[]` row(s)"),
        "{}",
        binding.line()
    );
}

// ---------------------------------------------------------------------------
// DW0842 — the binding does not bind
// ---------------------------------------------------------------------------

#[test]
fn dw0842_refuses_a_place_bound_twice() {
    let tmp = tempdir("dw0842-twice");
    let d = detailed(&tmp, &["node/exit"]);
    patch_detail_plan(&d, |v| {
        let row = v["content"]["details"][0].clone();
        v["content"]["details"].as_array_mut().unwrap().push(row);
    });
    let e = check_and_expect(&d, "DW0842");
    assert!(e.contains("more than one"), "{e}");
}

#[test]
fn dw0842_refuses_a_place_the_graph_does_not_have() {
    let tmp = tempdir("dw0842-place");
    let d = detailed(&tmp, &["node/exit"]);
    patch_detail_plan(&d, |v| {
        v["content"]["details"][0]["place"] = serde_json::json!("node/nowhere");
    });
    let e = check_and_expect(&d, "DW0842");
    assert!(e.contains("node/nowhere"), "{e}");
}

#[test]
fn dw0842_refuses_a_piece_the_library_does_not_hold() {
    let tmp = tempdir("dw0842-piece");
    let d = detailed(&tmp, &["node/exit"]);
    patch_detail_plan(&d, |v| {
        v["content"]["details"][0]["piece"] = serde_json::json!("prefab/nothing");
    });
    let e = check_and_expect(&d, "DW0842");
    assert!(e.contains("prefab/nothing"), "{e}");
}

#[test]
fn dw0842_refuses_an_anchor_key_the_place_does_not_owe() {
    let tmp = tempdir("dw0842-owe");
    let d = detailed(&tmp, &["node/exit"]);
    patch_detail_plan(&d, |v| {
        v["content"]["details"][0]["anchors"]["anchor/seam-cell-exit"] = serde_json::json!("seat0");
    });
    let e = check_and_expect(&d, "DW0842");
    assert!(e.contains("is not a name"), "{e}");
}

/// **One cause, one line — the primary-absent side.** With a map to be wrong
/// about, one bad `place` is one row's mistake: it is refused on its own, at its
/// own path, and the rows either side of it are not.
#[test]
fn dw0842_refuses_one_bad_row_per_row_while_the_map_exists() {
    let tmp = tempdir("dw0842-one-row");
    let places = every_place();
    let refs: Vec<&str> = places.iter().map(String::as_str).collect();
    let d = detailed(&tmp, &refs);
    patch_detail_plan(&d, |v| {
        v["content"]["details"][1]["place"] = serde_json::json!("node/nowhere");
    });
    let (diags, binding) = check_at(&d);
    let hit: Vec<_> = diags
        .iter()
        .filter(|x| x.code == "DW0842" && x.severity == Severity::Error)
        .collect();
    assert_eq!(
        hit.len(),
        1,
        "one wrong row is one refusal: {:?}",
        codes(&diags)
    );
    assert_eq!(hit[0].path, "/content/details[1]/place");
    assert!(
        hit[0].message.contains("node/nowhere"),
        "{}",
        hit[0].message
    );
    assert_eq!(
        binding.bound,
        places.len() - 1,
        "and every other row still bound"
    );
}

/// **One cause, one line — the primary-present side.** A site plan that resolves
/// ZERO boxes makes every `details[]` row miss by construction, so the per-row
/// refusal says one sentence once per row and none of the copies is the finding.
/// Measured on a 24-place campaign before this fold: `DW0824` (correct, one
/// line) followed by 24 copies of `DW0842`. The count, every row and the primary
/// it is downstream of are stated once — and the run still stops.
#[test]
fn dw0842_states_a_zero_box_plan_once_and_names_every_row() {
    let tmp = tempdir("dw0842-zero-boxes");
    let places = every_place();
    let refs: Vec<&str> = places.iter().map(String::as_str).collect();
    let d = detailed(&tmp, &refs);
    std::fs::remove_file(d.campaign.join("layout-graph.json")).unwrap();
    let (diags, binding) = check_at(&d);
    let hit: Vec<_> = diags
        .iter()
        .filter(|x| x.code == "DW0842" && x.severity == Severity::Error)
        .collect();
    assert_eq!(
        hit.len(),
        1,
        "one line for one map, not one per row: {:?}",
        codes(&diags)
    );
    assert_eq!(hit[0].path, "/content/details");
    for p in &places {
        assert!(
            hit[0].message.contains(p.as_str()),
            "a fold names every row it stands for; `{p}` is missing from: {}",
            hit[0].message
        );
    }
    assert!(
        hit[0].message.contains("DW0824"),
        "and it names the primary it defers to: {}",
        hit[0].message
    );
    assert_eq!(binding.rows, places.len(), "the row count is still stated");
    assert_eq!(binding.boxes, 0, "against a zero denominator");
    assert_eq!(binding.bound, 0);
}

/// The limiting case, named rather than inferred.
#[test]
fn dw0842_refuses_a_detail_plan_with_no_site_plan() {
    let tmp = tempdir("dw0842-nosite");
    let d = detailed(&tmp, &["node/exit"]);
    std::fs::remove_file(d.campaign.join("site-plan.json")).unwrap();
    let (diags, binding) = check_at(&d);
    let e = errors(&diags);
    assert!(e.iter().any(|x| x.code == "DW0842"), "{:?}", codes(&diags));
    assert_eq!(binding.boxes, 0, "and the zero denominator is stated");
}

/// **A row that is READ and a place that gets BOUND are different numbers**, and
/// collapsing them let the first exceed its own denominator.
///
/// Two rows naming one place: two rows read, one place bound, five boxes. Said
/// as one number it would have printed "2 of 5 place(s) bound" over a map with
/// one detailed place.
#[test]
fn a_row_read_and_a_place_bound_are_counted_apart() {
    let tmp = tempdir("counts");
    let d = detailed(&tmp, &["node/exit"]);
    patch_detail_plan(&d, |v| {
        let row = v["content"]["details"][0].clone();
        v["content"]["details"].as_array_mut().unwrap().push(row);
    });
    let (_, binding) = check_at(&d);
    assert_eq!(binding.rows, 2, "both rows were read");
    assert_eq!(binding.bound, 1, "and one place was bound");
    assert!(
        binding.bound <= binding.boxes,
        "a count never exceeds its denominator"
    );
}

/// **A piece that is not its frame suspends the FACE check and nothing else.**
///
/// The owed anchors and the declared class depend on neither the extent nor the
/// contract, so a wrong size must not suppress them — fixing the size would then
/// produce a crop of refusals nobody had been shown, and the place's owed names
/// would have been missing from the binding count while it happened.
#[test]
fn a_wrong_extent_suspends_the_face_check_and_no_other() {
    let tmp = tempdir("no-truncation");
    let d = detailed(&tmp, &["node/exit"]);
    patch_piece(&d, "exit", |v| {
        v["structure"]["size"][0] = serde_json::json!(12);
        v["footprint_class"] = serde_json::json!("expanse");
    });
    patch_detail_plan(&d, |v| {
        v["content"]["details"][0]["anchors"] = serde_json::json!({});
    });
    let (diags, binding) = check_at(&d);
    let found = codes(&diags);
    assert!(found.contains(&"DW0843".to_string()), "{found:?}");
    assert!(
        found.contains(&"DW0845".to_string()),
        "the owed anchor is still asked for: {found:?}"
    );
    assert!(
        found.contains(&"DW0848".to_string()),
        "and the declared class is still judged: {found:?}"
    );
    assert!(
        !found.contains(&"DW0844".to_string()),
        "while the face check is suspended, because its cells come from a frame \
         this piece is not: {found:?}"
    );
    assert_eq!(binding.owed, 1, "and the owed name is IN the denominator");
    assert_eq!(binding.classed, 1, "as is the declared class");
    assert_eq!(
        binding.seams_required, 0,
        "while the suspended check honestly says it examined nothing"
    );
}

// ---------------------------------------------------------------------------
// DW0843 — the piece is not the shape of its allocation
// ---------------------------------------------------------------------------

/// **Undersize refuses exactly as oversize does**, on every axis.
#[test]
fn dw0843_refuses_a_piece_one_cell_off_in_either_direction_on_any_axis() {
    for axis in 0..3 {
        for delta in [1i64, -1] {
            let tmp = tempdir(&format!("dw0843-{axis}-{delta}"));
            let d = detailed(&tmp, &["node/exit"]);
            patch_piece(&d, "exit", |v| {
                let n = v["structure"]["size"][axis].as_i64().unwrap();
                v["structure"]["size"][axis] = serde_json::json!(n + delta);
            });
            let e = check_and_expect(&d, "DW0843");
            assert!(
                e.contains(if delta > 0 { "1 too many" } else { "1 too few" }),
                "the refusal names the direction and the amount: {e}"
            );
            assert!(
                e.contains("undersize refuses exactly as oversize does"),
                "and says why they are the same finding: {e}"
            );
        }
    }
}

#[test]
fn dw0843_refuses_a_detail_piece_that_declares_no_contract() {
    let tmp = tempdir("dw0843-contract");
    let d = detailed(&tmp, &["node/exit"]);
    patch_piece(&d, "exit", |v| {
        v.as_object_mut().unwrap().remove("spatial_contract");
    });
    let e = check_and_expect(&d, "DW0843");
    assert!(e.contains("declares no spatial contract"), "{e}");
}

// ---------------------------------------------------------------------------
// DW0844 — the piece's openings are not the plan's seams, both directions
// ---------------------------------------------------------------------------

#[test]
fn dw0844_refuses_a_seam_the_piece_seals() {
    let tmp = tempdir("dw0844-sealed");
    let d = detailed(&tmp, &["node/exit"]);
    patch_piece(&d, "exit", |v| {
        v["spatial_contract"]["faces"] = serde_json::json!([]);
    });
    let e = check_and_expect(&d, "DW0844");
    assert!(e.contains("leaves the seam"), "{e}");
    assert!(e.contains("no face on that side at all"), "{e}");
}

#[test]
fn dw0844_refuses_a_face_answering_no_seam() {
    let tmp = tempdir("dw0844-discovered");
    let d = detailed(&tmp, &["node/exit"]);
    patch_piece(&d, "exit", |v| {
        let extra = serde_json::json!({
            "space": "room",
            "class": "walk",
            "dir": "north",
            "opening": { "from": [3, 1, 0], "to": [4, 3, 0] },
        });
        v["spatial_contract"]["faces"]
            .as_array_mut()
            .unwrap()
            .push(extra);
    });
    let e = check_and_expect(&d, "DW0844");
    assert!(e.contains("DISCOVERED rather than designed"), "{e}");
}

/// **One cause, one line — the DEFER shape** (`dsl::diagnostic`).
///
/// A `details[]` row is judged against a FRAME and a SEAM SET the site plan
/// computed, so a plan whose own checks have already refused them makes a
/// stage-6 line a true measurement against a number the map does not keep — and
/// the primary is in ANOTHER document, where the reader cannot see the relation.
/// Measured on a 24-place campaign: widening one box by one block printed
/// `DW0825` and `DW0828` in the site plan and then `DW0843` and `DW0844` in the
/// detail plan, five codes over three documents, with nothing saying which was
/// the edit.
///
/// The stage-6 lines keep their own refusals — each names a real mismatch, and
/// suppressing them is how fixing one thing produces a fresh crop nobody was
/// shown — and gain a clause naming what they stand downstream of.
#[test]
fn a_stage_six_verdict_names_the_site_plan_refusal_it_stands_downstream_of() {
    let tmp = tempdir("upstream-refused");
    let d = detailed(&tmp, &["node/exit"]);
    // One block wider on x: off the kit grid (`DW0825`), and the frame the piece
    // is measured against moves with it.
    common::patch_file(&d.campaign.join("site-plan.json"), |v| {
        let boxes = v["content"]["boxes"].as_array_mut().unwrap();
        let b = boxes
            .iter_mut()
            .find(|b| b["node"] == "node/exit")
            .expect("the fixture places `node/exit`");
        let x = b["extent"][0].as_i64().unwrap();
        b["extent"][0] = serde_json::json!(x + 1);
    });
    let e = check_and_expect(&d, "DW0843");
    assert!(
        e.contains("is not the shape of the box"),
        "the verdict still refuses on its own terms: {e}"
    );
    assert!(
        e.contains("downstream of a site-plan refusal") && e.contains("DW0825"),
        "and says what it is downstream of: {e}"
    );
}

/// The other side of the same rule: with a plan the plan's own checks accept,
/// the clause is ABSENT. A deferral that fired on a settled plan would be
/// telling every author their measurement is provisional.
#[test]
fn a_stage_six_verdict_carries_no_deferral_when_the_plan_is_settled() {
    let tmp = tempdir("upstream-settled");
    let d = detailed(&tmp, &["node/exit"]);
    patch_piece(&d, "exit", |v| {
        let n = v["structure"]["size"][0].as_i64().unwrap();
        v["structure"]["size"][0] = serde_json::json!(n + 1);
    });
    let e = check_and_expect(&d, "DW0843");
    assert!(e.contains("1 too many"), "the ordinary refusal: {e}");
    assert!(
        !e.contains("downstream of a site-plan refusal"),
        "and nothing upstream to defer to: {e}"
    );
}

#[test]
fn dw0844_refuses_a_face_of_the_wrong_class() {
    let tmp = tempdir("dw0844-class");
    let d = detailed(&tmp, &["node/exit"]);
    patch_piece(&d, "exit", |v| {
        v["spatial_contract"]["faces"][0]["class"] = serde_json::json!("barred");
    });
    let e = check_and_expect(&d, "DW0844");
    assert!(e.contains("not the same crossing"), "{e}");
}

/// **The two observers, proven independent** (spec-0050 §16.7).
///
/// A piece that lies in its metadata — declaring the face while its BYTES seal
/// the way — passes `DW0844`, which reads declarations, and reds on the bytes
/// battery, which reads blocks. Neither could have caught it alone, and that is
/// the whole reason `DW0844` is deliberately redundant with `DW0836`/`DW0838`
/// rather than their replacement.
#[test]
fn a_piece_that_lies_in_its_metadata_passes_dw0844_and_reds_on_bytes() {
    let tmp = tempdir("independent");
    let d = detailed(&tmp, &["node/exit"]);
    // Wall the seam's own cells up in the BYTES, leaving every declaration
    // exactly as it was.
    let c = campaign_at(&d.campaign);
    let a = detail::allocation(&c, &NodeId("node/exit".into())).unwrap();
    let mass = unbound_massing(&c);
    let mut cells = piece_cells(&c, &a, &mass);
    let seam = &a.seams[0];
    for (p, b) in cells.iter_mut() {
        let inside = (0..3).all(|i| {
            i64::from(p[i]) >= seam.cells[0][i].min(seam.cells[1][i])
                && i64::from(p[i]) <= seam.cells[0][i].max(seam.cells[1][i])
        });
        if inside {
            *b = "minecraft:stone_bricks".to_string();
        }
    }
    write_piece(&d.prefabs, "exit", &a, &cells);

    let (diags, _) = check_at(&d);
    assert!(
        errors(&diags).is_empty(),
        "the declaration reader sees nothing wrong — it was not lied to about a \
         declaration: {:?}",
        codes(&diags)
    );

    let (battery, codes) = battery_at(&d);
    assert!(
        codes.iter().any(|c| c == "DW0836" || c == "DW0837"),
        "and the byte reader refuses: {codes:?}"
    );
    assert!(battery.refusal().is_some());
}

// ---------------------------------------------------------------------------
// DW0845 — an owed anchor has no standing
// ---------------------------------------------------------------------------

#[test]
fn dw0845_refuses_an_owed_name_left_unbound() {
    let tmp = tempdir("dw0845-unbound");
    let d = detailed(&tmp, &["node/exit"]);
    patch_detail_plan(&d, |v| {
        v["content"]["details"][0]["anchors"] = serde_json::json!({});
    });
    let e = check_and_expect(&d, "DW0845");
    assert!(e.contains("anchor/node-exit"), "{e}");
    assert!(e.contains("never force a quest edit"), "{e}");
}

#[test]
fn dw0845_refuses_an_anchor_a_body_cannot_be_at() {
    let tmp = tempdir("dw0845-nobody");
    let d = detailed(&tmp, &["node/exit"]);
    patch_piece(&d, "exit", |v| {
        v["anchors"]["seat0"]["resolves_to"] = serde_json::json!("no_body:rafters");
    });
    let e = check_and_expect(&d, "DW0845");
    assert!(e.contains("not play space"), "{e}");
}

#[test]
fn dw0845_refuses_a_region_anchor_where_a_place_to_stand_is_owed() {
    let tmp = tempdir("dw0845-region");
    let d = detailed(&tmp, &["node/exit"]);
    patch_piece(&d, "exit", |v| {
        let a = v["anchors"]["seat0"].as_object_mut().unwrap();
        a.remove("pos");
        a.insert(
            "region".to_string(),
            serde_json::json!({ "from": [1, 1, 1], "to": [2, 2, 2] }),
        );
        a.insert(
            "block".to_string(),
            serde_json::json!("minecraft:iron_bars"),
        );
    });
    let e = check_and_expect(&d, "DW0845");
    assert!(e.contains("declares no cell"), "{e}");
}

/// **A gate station bound to a cell** (spec-0052 §7.5) — the direction nothing
/// in this engine could report before, because before stations no owed name was
/// ever a gate.
///
/// Its sibling above is the reason this is a separate rule rather than a wider
/// one: an owed POINT bound to a region is `DW0845`'s "a region, not a place to
/// stand", and it stays `DW0845`. Raising a second code for it would prescribe
/// two repairs for one mistake and move a diagnostic campaigns already meet.
///
/// Binding: one owed name, declared as a gate, bound to the piece's point.
#[test]
fn dw0842_refuses_a_gate_station_bound_to_a_cell() {
    let tmp = tempdir("dw0842-gate-station");
    let d = detailed(&tmp, &["node/exit"]);
    // Declare a gate station on the bound place and bind it to `seat0`, which
    // is a point: the piece has a cell where the campaign promised a volume.
    common::patch_file(&d.campaign.join("layout-graph.json"), |v| {
        v["dsl_version"] = serde_json::json!(DSL_VERSION);
        for n in v["content"]["nodes"].as_array_mut().unwrap() {
            if n["id"] == "node/exit" {
                n["stations"] = serde_json::json!([
                    { "anchor": "anchor/vestry-grille", "kind": "gate" }
                ]);
            }
        }
    });
    patch_detail_plan(&d, |v| {
        v["content"]["details"][0]["anchors"]["anchor/vestry-grille"] = serde_json::json!("seat0");
    });
    let e = check_and_expect(&d, "DW0842");
    assert!(
        e.contains("anchor/vestry-grille"),
        "must name the station: {e}"
    );
    assert!(
        e.contains("declares no region"),
        "must say what the piece anchor is missing: {e}"
    );
    assert!(
        e.contains("`point`"),
        "and must name the reachable remedy — change the kind: {e}"
    );
}

// ---------------------------------------------------------------------------
// DW0848 — the declared footprint class, at the consumer door
// ---------------------------------------------------------------------------

#[test]
fn dw0848_refuses_a_declared_class_the_bytes_contradict() {
    let tmp = tempdir("dw0848");
    let d = detailed(&tmp, &["node/exit"]);
    // `node/exit` is an 8x8 alcove; `expanse` starts at 64x64.
    patch_piece(&d, "exit", |v| {
        v["footprint_class"] = serde_json::json!("expanse");
    });
    let e = check_and_expect(&d, "DW0848");
    assert!(e.contains("could serve no box of that class"), "{e}");

    // And the honest claim passes, so the check is not simply always red.
    let tmp = tempdir("dw0848-green");
    let d = detailed(&tmp, &["node/exit"]);
    patch_piece(&d, "exit", |v| {
        v["footprint_class"] = serde_json::json!("alcove");
    });
    let (diags, binding) = check_at(&d);
    assert!(errors(&diags).is_empty(), "{:?}", codes(&diags));
    assert_eq!(
        binding.classed, 1,
        "and the declaration was judged, not skipped"
    );
}

#[test]
fn dw0812_refuses_a_footprint_class_the_table_does_not_define() {
    let tmp = tempdir("dw0848-unknown");
    let d = detailed(&tmp, &["node/exit"]);
    patch_piece(&d, "exit", |v| {
        v["footprint_class"] = serde_json::json!("cathedral");
    });
    let e = check_and_expect(&d, "DW0812");
    assert!(e.contains("cathedral"), "{e}");
}

// ---------------------------------------------------------------------------
// DW0821's promotion, in both directions
// ---------------------------------------------------------------------------

/// The fixture declares a vista the derived massing blocks, so the same world is
/// a warning while any box is unbound and a refusal once every node is bound.
/// Nothing is set and nothing is chosen: the severity is computed from the
/// artifact.
#[test]
fn dw0821_is_a_warning_until_every_node_is_bound_and_then_a_refusal() {
    let tmp = tempdir("dw0821-partial");
    let all = every_place();
    let some: Vec<&str> = all[..all.len() - 1].iter().map(String::as_str).collect();
    let partial = detailed(&tmp, &some);
    assert!(!detail::fully_detailed(&campaign_at(&partial.campaign)));
    let (battery, found) = battery_at(&partial);
    assert!(found.iter().any(|c| c == "DW0821"), "{found:?}");
    assert!(
        battery
            .findings
            .iter()
            .any(|(_, d)| d.code == "DW0821" && d.severity == Severity::Warning),
        "one box still massed, so the vista is still the walk sheet's business"
    );

    let tmp = tempdir("dw0821-full");
    let every: Vec<&str> = all.iter().map(String::as_str).collect();
    let full = detailed(&tmp, &every);
    let c = campaign_at(&full.campaign);
    assert!(detail::fully_detailed(&c));
    let (dd, binding) = check_at(&full);
    assert!(
        errors(&dd).is_empty(),
        "a piece cut from the massing of EVERY place satisfies every stage-6 gate — \
         including the hall's hosted stair, the loft's rim over it, the undercroft's \
         climb up through a punched floor, and the way that is not a box with a size \
         class at all: {:?}",
        codes(&dd)
    );
    assert_eq!(
        binding.bound,
        binding.boxes,
        "and every place is bound: {}",
        binding.line()
    );
    assert_eq!(
        binding.seams_required, 14,
        "each of the seven seams answered from both sides"
    );

    let (battery, _) = battery_at(&full);
    let sight: Vec<_> = battery
        .findings
        .iter()
        .filter(|(_, d)| d.code == "DW0821")
        .collect();
    assert_eq!(sight.len(), 1, "the same one vista");
    assert_eq!(
        sight[0].1.severity,
        Severity::Error,
        "and with nothing left to carve it is a refusal"
    );
    let refusal = battery.refusal().expect("which stops the build");
    assert_eq!(
        refusal.1.code,
        "DW0821",
        "and it is the ONLY refusal — the substituted world is otherwise the massed \
         world, over every one of its five places: {:?}",
        battery
            .findings
            .iter()
            .filter(|(_, x)| x.severity == Severity::Error)
            .map(|(_, x)| x.code.clone())
            .collect::<Vec<_>>()
    );
}

// ---------------------------------------------------------------------------
// Traversal equivalence, and determinism
// ---------------------------------------------------------------------------

/// Run the stage-5 battery over the detailed world — the equivalence instrument
/// (spec-0050 §7), unchanged and reused rather than reimplemented.
fn battery_at(d: &Detailed) -> (blockout::Battery, Vec<String>) {
    let c = campaign_at(&d.campaign);
    let reg = PrefabRegistry::load_dir(&d.prefabs).expect("the piece library loads");
    let plan = Plan::build(&c, &reg).expect("the detailed campaign plans");
    let mut structures: BTreeMap<String, Vec<u8>> = BTreeMap::new();
    for area in &plan.areas {
        for piece in &area.pieces {
            for t in &piece.templates {
                if let Ok(bytes) = std::fs::read(d.prefabs.join(&t.structure_file)) {
                    structures.insert(t.structure_file.clone(), bytes);
                }
            }
        }
    }
    let blocks = delvec::compiler::assembled::assembled_blocks(&plan, &structures);
    let battery = blockout::check(&plan, &blocks).expect("a site-plan campaign has a blockout");
    let codes = battery
        .findings
        .iter()
        .map(|(_, d)| d.code.clone())
        .collect();
    (battery, codes)
}

/// **Traversal equivalence, demonstrated as a passing battery rather than
/// asserted** (spec-0050 §16.4): the world with a piece standing where massing
/// stood answers every question the massed world answered, over the same
/// instrument.
#[test]
fn the_stage_five_battery_is_green_over_a_detailed_world() {
    let tmp = tempdir("equivalence");
    let d = detailed(&tmp, &["node/exit"]);
    let (battery, _) = battery_at(&d);
    assert!(
        battery.refusal().is_none(),
        "{:?}",
        battery
            .findings
            .iter()
            .filter(|(_, x)| x.severity == Severity::Error)
            .map(|(_, x)| x.message.clone())
            .collect::<Vec<_>>()
    );
    assert!(
        battery.binding.seams > 0 && battery.binding.nodes == 7,
        "and it bound to the whole map: {}",
        battery.binding.line()
    );
}

/// **Which of a derived area's two anchor producers wins, measured rather than
/// commented.**
///
/// The derivation names `anchor/node-…` at the massing's own footing; a piece
/// standing in that box then owes the same name, and where the piece stands is
/// the truth — so the detail plan's anchors are seated AFTER the derivation's
/// and overwrite them. That is what keeps a campaign's stage-3 vocabulary
/// working across a detailing edit without a quest touching it.
///
/// It is asserted here because the two producers a plan seats through point
/// opposite ways, and only a comment said so. A prefab-placed area is
/// first-wins (`AnchorTable::declare`): a pool can seat one anchor-bearing
/// piece twice, and `DW0498` reports the first carrier. The derived path is
/// last-wins (`AnchorTable::place`). Collapsing them into one rule compiles
/// and leaves every existing test passing, while every detailed place's anchor
/// moves silently back onto the massing — a quest that walks to `node/exit`
/// then walks somewhere nobody authored.
///
/// The control is the second half: the same name on the UNdetailed map. If the
/// two cells were equal the assertion above would hold for the wrong reason,
/// and the test would be green under either rule.
#[test]
fn a_detail_pieces_anchor_overwrites_the_derivations_footing() {
    let tmp = tempdir("anchor-precedence");
    let d = detailed(&tmp, &["node/exit"]);
    let reg = PrefabRegistry::load_dir(&d.prefabs).expect("the piece library loads");
    let key = (
        delvewright_dsl::SITE_AREA.to_string(),
        "anchor/node-exit".to_string(),
    );

    let at = |plan: &Plan<'_>| match plan.anchors.get(&key) {
        Some(delvec::compiler::plan::ResolvedAnchor::Point { pos, .. }) => *pos,
        _ => panic!("a place's own anchor is a cell to stand on"),
    };

    let detailed_c = campaign_at(&d.campaign);
    let detailed_at = at(&Plan::build(&detailed_c, &reg).expect("the detailed campaign plans"));

    let bare_c = campaign_at(&blockout_dir());
    let bare_at = at(&Plan::build(&bare_c, &reg).expect("the undetailed campaign plans"));

    assert_ne!(
        detailed_at, bare_at,
        "the control: if the piece's seat and the massing's footing were the \
         same cell, this test could not tell the two seating rules apart"
    );

    let a = detail::allocation(&detailed_c, &NodeId("node/exit".into()))
        .expect("`node/exit` is a place this map has");
    assert!(
        (0..3).all(|i| {
            i64::from(detailed_at[i]) >= a.world_min[i]
                && i64::from(detailed_at[i]) < a.world_min[i] + a.extent[i]
        }),
        "the resolved cell is inside the piece's own frame, not on the \
         massing's footing: {detailed_at:?} vs the frame at {:?} + {:?}",
        a.world_min,
        a.extent
    );
}

/// **Detailing the ENTRY place moves where the party arrives, and the role is
/// what carries it there.**
///
/// The pair neither change could have tested. The derivation declares
/// `AnchorRole::Entry` on the entry node's anchor (spec-0046) — so `spawn` is a
/// name content may address and not the thing resolution reads — while a
/// `details[]` row on that same place re-binds the name to the piece's own
/// seat. Every other test in this file details `node/exit`, so the one place
/// the two mechanisms meet was never walked.
///
/// What is asserted is the whole chain: the role is declared on a derived map,
/// it still names the owed anchor after detailing, and `Plan::entry_point` —
/// which drives `setworldspawn`, the class-apply teleport, first-join
/// placement and the `dw:cp` seed — lands inside the piece's frame rather than
/// on the massing footing it had before.
#[test]
fn detailing_the_entry_place_moves_where_the_party_arrives() {
    let tmp = tempdir("detailed-entry");
    let d = detailed(&tmp, &["node/landing"]);
    let c = campaign_at(&d.campaign);
    let reg = PrefabRegistry::load_dir(&d.prefabs).expect("the piece library loads");
    let plan = Plan::build(&c, &reg).expect("the detailed campaign plans");
    let area = delvewright_dsl::SITE_AREA.to_string();

    assert_eq!(
        plan.anchors
            .role_name(&area, delvec::compiler::plan::AnchorRole::Entry),
        Some(delvewright_dsl::ENTRY_ANCHOR),
        "a derived map declares what its entry anchor is for, detailed or not"
    );

    let a = detail::allocation(&c, &NodeId("node/landing".into()))
        .expect("`node/landing` is a place this map has");
    assert!(
        a.owed_anchors
            .iter()
            .any(|n| n == delvewright_dsl::ENTRY_ANCHOR),
        "the entry place owes the entry name: {:?}",
        a.owed_anchors
    );

    let at = plan
        .entry_point(&area)
        .expect("the party arrives somewhere");
    assert!(
        (0..3).all(|i| {
            i64::from(at[i]) >= a.world_min[i] && i64::from(at[i]) < a.world_min[i] + a.extent[i]
        }),
        "the party arrives inside the piece standing in the entry place: \
         {at:?} vs the frame at {:?} + {:?}",
        a.world_min,
        a.extent
    );

    let bare_at = Plan::build(&campaign_at(&blockout_dir()), &reg)
        .expect("the undetailed campaign plans")
        .entry_point(&area)
        .expect("the massed map has an entry too");
    assert_ne!(
        at, bare_at,
        "the control: detailing the entry place must actually move the start, \
         or this test would pass over a resolution that never consulted the piece"
    );
}

/// **The derivation stops writing inside a bound frame, and nowhere else.**
///
/// The world a bound campaign masses is the unbound one MINUS exactly the frame,
/// so the fabric split is measured rather than described.
#[test]
fn the_derivation_leaves_a_bound_frame_empty_and_touches_nothing_else() {
    let tmp = tempdir("holes");
    let d = detailed(&tmp, &["node/exit"]);
    let c = campaign_at(&d.campaign);
    let a = detail::allocation(&c, &NodeId("node/exit".into())).unwrap();
    let unbound = massing(&campaign_at(&blockout_dir()));

    let mut reads = delvewright_dsl::metrics::Reads::new();
    let (placement, _) = blockout::derive(&c, &mut reads).expect("the campaign derives");
    let mut bound: BTreeMap<[i64; 3], String> = BTreeMap::new();
    for f in &placement.mass {
        let lo = [
            i64::from(f.from[0]),
            i64::from(f.from[1]),
            i64::from(f.from[2]),
        ];
        let hi = [i64::from(f.to[0]), i64::from(f.to[1]), i64::from(f.to[2])];
        for cell in blockout::cells_of(lo, hi) {
            if f.block == "minecraft:air" {
                bound.remove(&cell);
            } else {
                bound.insert(cell, f.block.clone());
            }
        }
    }

    let inside = |cell: &[i64; 3]| {
        (0..3).all(|i| cell[i] >= a.world_min[i] && cell[i] < a.world_min[i] + a.extent[i])
    };
    let lost: Vec<_> = unbound.keys().filter(|k| !bound.contains_key(*k)).collect();
    assert!(
        !lost.is_empty(),
        "binding a place must actually stop the derivation writing something"
    );
    assert!(
        lost.iter().all(|k| inside(k)),
        "and every cell it stopped writing is inside the frame: {:?}",
        lost.iter().take(4).collect::<Vec<_>>()
    );
    let gained: Vec<_> = bound.keys().filter(|k| !unbound.contains_key(*k)).collect();
    assert!(gained.is_empty(), "and it writes nothing new: {gained:?}");
    for (cell, block) in &bound {
        assert_eq!(
            unbound.get(cell),
            Some(block),
            "and every cell it still writes is the block it always wrote, at {cell:?}"
        );
    }
}

/// A campaign that binds nothing masses exactly what it massed before, so the
/// whole of stage 6 is byte-invisible to every campaign below 0.15.0.
#[test]
fn a_campaign_that_binds_nothing_is_massed_byte_identically() {
    let tmp = tempdir("no-op");
    let d = detailed(&tmp, &[]);
    let bound = massing(&campaign_at(&d.campaign));
    let unbound = massing(&campaign_at(&blockout_dir()));
    assert_eq!(bound, unbound);
}

/// **Determinism (ADR-0006)**: same DSL, same seed, byte-identical output — with
/// a piece standing in a place.
#[test]
fn a_detailed_campaign_builds_byte_identically_twice() {
    let tmp = tempdir("determinism");
    let d = detailed(&tmp, &["node/exit"]);
    let a = build_into(&d, &tmp.join("out-a"));
    let b = build_into(&d, &tmp.join("out-b"));
    assert!(!a.is_empty(), "a build produced files");
    assert_eq!(
        a.keys().collect::<Vec<_>>(),
        b.keys().collect::<Vec<_>>(),
        "the same file set"
    );
    for (k, v) in &a {
        assert_eq!(b.get(k), Some(v), "and identical bytes in {k}");
    }
}

/// The seed reaches no blockout byte and no piece placement, so moving it moves
/// nothing about where a detailed place is or what is in it.
#[test]
fn the_seed_moves_no_detailed_byte() {
    let tmp = tempdir("seed");
    let d = detailed(&tmp, &["node/exit"]);
    let before = massing(&campaign_at(&d.campaign));
    common::patch_file(&d.campaign.join("world.json"), |v| {
        v["content"]["seed"] = serde_json::json!(987_654_321i64);
    });
    let after = massing(&campaign_at(&d.campaign));
    assert_eq!(before, after);
}

// ---------------------------------------------------------------------------
// The frame is unauthorable, asserted rather than described
// ---------------------------------------------------------------------------

/// The schema has no spelling for where anything goes, so the whole class of
/// "nudge the frame" edits does not parse. `delvewright_dsl::detailplan` asserts
/// this over the row and the document; here it is asserted end to end, over a
/// real campaign directory, because that is where an author would try it.
#[test]
fn a_detail_plan_cannot_state_a_coordinate() {
    let tmp = tempdir("unauthorable");
    let d = detailed(&tmp, &["node/exit"]);
    for (path, value) in [
        ("min", serde_json::json!([0, 0, 0])),
        ("offset", serde_json::json!([0, 1, 0])),
        ("extent", serde_json::json!([8, 5, 8])),
        ("datum", serde_json::json!("datum/grade")),
    ] {
        patch_detail_plan(&d, |v| {
            v["content"]["details"][0][path] = value;
        });
        let loaded =
            delvec::compiler::load::load_campaign_dir(&d.campaign).expect("still readable");
        let Err(diags) = delvewright_dsl::parse_campaign(&loaded.raw) else {
            panic!("a detail row carrying `{path}` must not parse");
        };
        assert!(
            diags.iter().any(|x| x.code == "DW0100"),
            "the refusal is the schema's: {:?}",
            codes(&diags)
        );
        // Put it back for the next round of the loop.
        patch_detail_plan(&d, |v| {
            v["content"]["details"][0]
                .as_object_mut()
                .unwrap()
                .remove(path);
        });
    }
}

// ---------------------------------------------------------------------------
// The two verbs, at process level
// ---------------------------------------------------------------------------

const BIN: &str = env!("CARGO_BIN_EXE_delvec");

fn delvec(args: &[&str]) -> std::process::Output {
    std::process::Command::new(BIN)
        .args(args)
        .output()
        .expect("run delvec")
}

/// `delvec allocation` hands out the whole of what the plan gives a place, and
/// nothing a piece could give back — there is no coordinate in the SCHEMA, and
/// the world position it prints is stated as a finding aid rather than as an
/// input, because nothing reads it back.
#[test]
fn the_allocation_verb_hands_out_the_frame_the_seams_and_the_owed_names() {
    let tmp = tempdir("allocation-cli");
    let d = detailed(&tmp, &[]);
    let out = delvec(&[
        "--prefabs",
        d.prefabs.to_str().unwrap(),
        "allocation",
        d.campaign.to_str().unwrap(),
        "node/exit",
    ]);
    assert_eq!(
        out.status.code(),
        Some(0),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let v: serde_json::Value = serde_json::from_slice(&out.stdout).expect("it prints JSON");
    assert_eq!(v["place"], "node/exit");
    assert_eq!(
        v["extent"],
        serde_json::json!([8, 5, 8]),
        "the frame is the box plus its floor course"
    );
    assert_eq!(v["datum_y"], 1, "and the walk plane is one course up");
    assert_eq!(v["seams"][0]["edge"], "edge/cell-exit");
    assert_eq!(v["seams"][0]["face"], "east");
    assert_eq!(v["seams"][0]["answer_with"], serde_json::json!(["walk"]));
    assert_eq!(v["owed_anchors"], serde_json::json!(["anchor/node-exit"]));
    assert_eq!(
        v["palette"]["role/wall"], "minecraft:stone_bricks",
        "and the whole's vocabulary is handed through, gated by nothing"
    );

    let all = delvec(&[
        "--prefabs",
        d.prefabs.to_str().unwrap(),
        "allocation",
        d.campaign.to_str().unwrap(),
        "--all",
    ]);
    assert_eq!(all.status.code(), Some(0));
    let v: serde_json::Value = serde_json::from_slice(&all.stdout).unwrap();
    assert_eq!(
        v.as_array().unwrap().len(),
        7,
        "one per place, in plan order"
    );
}

/// A detailed build exits zero and states its detail binding with its
/// denominator.
#[test]
fn a_detailed_build_exits_zero_and_states_its_binding() {
    let tmp = tempdir("build-cli");
    let d = detailed(&tmp, &["node/exit"]);
    let out = delvec(&[
        "--prefabs",
        d.prefabs.to_str().unwrap(),
        "build",
        d.campaign.to_str().unwrap(),
        "--out",
        tmp.join("out").to_str().unwrap(),
    ]);
    let err = String::from_utf8_lossy(&out.stderr);
    assert_eq!(out.status.code(), Some(0), "{err}");
    assert!(
        err.contains("1 of 7 place(s) bound"),
        "and the detail binding count, with its denominator"
    );
}

/// **A bound place lights itself, and the existing gate judges it**
/// (spec-0050 §3).
///
/// The blockout fixture declares `lighting: {fixture: torch}`, and before stage 6
/// that pass hung torches on every dark reachable cell of the whole area. Inside
/// a bound frame it must not: the frame is the piece's, and lighting is part of
/// what a place looks like — the whole lighting a building somebody designed
/// would be the whole writing inside a bound frame, which is the one thing the
/// fabric split says it does not do.
///
/// What replaces it is not silence. The cells go to the undeclared-darkness
/// measurement, so a dark detailed place is a **finding**, and this is the
/// demonstration: take the light out of the piece and the build refuses.
#[test]
fn the_whole_does_not_light_a_bound_place_and_a_dark_one_is_a_finding() {
    let tmp = tempdir("relight");
    let (out, s) = unlit_bound_place(&tmp, "node/exit");
    assert_ne!(out.status.code(), Some(0), "a dark place is a finding: {s}");
    assert!(
        s.contains("DW0210"),
        "and it is the darkness gate that says so, not a silence: {s}"
    );
    assert!(
        s.contains("area/site"),
        "over the site area the piece stands in: {s}"
    );
}

/// **The refusal names a remedy this author can take** — the second half of the
/// rule `delvewright_dsl::placement` opened, one layer in.
///
/// `CLAUDE.md`: *a gate that names a remedy owes a check that the remedy is
/// reachable*. The blockout fixture's plan **declares** `lighting`, and a bound
/// frame is exactly where that declaration does not reach (spec-0050 §3), so the
/// old message told an author who had already declared it to declare it — and
/// said the campaign had no `lighting` declaration while the document on disk
/// carried one. Both halves are asserted here: what the refusal must now say,
/// and the sentence it must no longer print.
///
/// The negative is the load-bearing half. A message can name the piece and still
/// carry the unreachable prescription three lines further down, and a test that
/// only greps for the new words would pass over exactly that.
#[test]
fn a_dark_bound_place_is_told_what_it_owes_and_not_to_declare_the_plans_lighting() {
    let tmp = tempdir("relight-remedy");
    // The precondition the whole finding rests on: the plan the fixture ships
    // ALREADY declares the lighting the old message prescribed.
    let base = campaign_at(&blockout_dir());
    assert!(
        base.site_plan
            .as_ref()
            .expect("the blockout fixture carries a site plan")
            .content
            .lighting
            .is_some(),
        "fixture: the plan must declare `lighting` for the old remedy to be unreachable"
    );

    let (out, s) = unlit_bound_place(&tmp, "node/exit");
    assert_ne!(
        out.status.code(),
        Some(0),
        "a dark bound place refuses: {s}"
    );
    assert!(s.contains("DW0210"), "under the darkness gate: {s}");

    assert!(
        s.contains("bound place(s) measure dark"),
        "the refusal must say the dark cells are in a BOUND place, which is the fact \
         that decides the remedy: {s}"
    );
    let line = s
        .lines()
        .find(|l| l.trim_start().starts_with("place `"))
        .unwrap_or_else(|| panic!("the report names no bound place:\n{s}"));
    assert!(
        line.contains("place `node/exit`") && line.contains("bound to `prefab/exit`"),
        "and it names the place AND the piece, because the remedy is taken in the \
         piece and nothing else says which one: {line}"
    );
    assert!(
        line.contains("in the piece's own coordinates"),
        "and it states the darkest cell where the author edits it — a world coordinate \
         is unusable inside a `.nbt` whose origin is its own corner: {line}"
    );
    assert!(
        s.contains("INSIDE THE PIECE BOUND TO IT"),
        "and the remedy it prescribes is the one that exists: {s}"
    );

    // The negative.
    assert!(
        !s.contains("Mitigate each area one of"),
        "the plan-level remedy must NOT be prescribed over a bound place: the fixture's \
         plan declares `lighting` already and the fixture pass never enters a bound \
         frame, so that sentence asks for an act that changes nothing: {s}"
    );
    assert!(
        !s.contains("with no `lighting` declaration"),
        "nor may the refusal claim the campaign declared no lighting while its plan \
         carries one: {s}"
    );
}

/// Build the blockout fixture with `node` bound to a piece cut from the massing
/// and its own torches removed — the one state that puts a dark place inside a
/// bound frame. Returns the run and its combined output.
///
/// Shared by the two tests above rather than written twice: they assert
/// different things about the same world, and two copies of the perturbation is
/// two places for the state under test to drift.
fn unlit_bound_place(tmp: &Path, node: &str) -> (std::process::Output, String) {
    let d = detailed(tmp, &[node]);
    // Green first, so what follows is measured against a piece that was lit.
    let out = delvec(&[
        "--prefabs",
        d.prefabs.to_str().unwrap(),
        "build",
        d.campaign.to_str().unwrap(),
        "--out",
        tmp.join("out-lit").to_str().unwrap(),
    ]);
    assert_eq!(
        out.status.code(),
        Some(0),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );

    // Now put the piece's own lights out, changing nothing else.
    let c = campaign_at(&d.campaign);
    let a = detail::allocation(&c, &NodeId(node.into())).unwrap();
    let mass = unbound_massing(&c);
    let cells: Vec<([i32; 3], String)> = piece_cells(&c, &a, &mass)
        .into_iter()
        .map(|(p, b)| {
            if b == "minecraft:torch" {
                (p, "minecraft:air".to_string())
            } else {
                (p, b)
            }
        })
        .collect();
    assert!(
        cells.iter().all(|(_, b)| b != "minecraft:torch"),
        "the perturbation actually removed something"
    );
    write_piece(&d.prefabs, node.split('/').nth(1).unwrap(), &a, &cells);

    let out = delvec(&[
        "--prefabs",
        d.prefabs.to_str().unwrap(),
        "build",
        d.campaign.to_str().unwrap(),
        "--out",
        tmp.join("out-dark").to_str().unwrap(),
    ]);
    let s =
        String::from_utf8_lossy(&out.stdout).to_string() + &String::from_utf8_lossy(&out.stderr);
    (out, s)
}

/// **The red reaching a creator's exit code**, end to end and through the fence.
///
/// The unit checks above read `detail::check`'s raw list; this reads what
/// `delvec build` actually does with it, which is where an obligation that the
/// fence quietly dropped would show up as a green build.
#[test]
fn a_piece_that_is_not_its_frame_fails_the_build_through_the_fence() {
    let tmp = tempdir("build-red");
    let d = detailed(&tmp, &["node/exit"]);
    patch_piece(&d, "exit", |v| {
        v["structure"]["size"][0] = serde_json::json!(12);
    });
    let out = delvec(&[
        "--prefabs",
        d.prefabs.to_str().unwrap(),
        "build",
        d.campaign.to_str().unwrap(),
        "--out",
        tmp.join("out").to_str().unwrap(),
    ]);
    let s = String::from_utf8_lossy(&out.stdout) + String::from_utf8_lossy(&out.stderr);
    assert_eq!(out.status.code(), Some(1), "{s}");
    assert!(s.contains("DW0843"), "{s}");
    assert!(
        !tmp.join("out").join("manifest.json").exists(),
        "and no datapack was written"
    );
}

/// **The bot is handed the same walk** (spec-0050 §16.4).
///
/// The critical-path export is what the mineflayer harness drives, so comparing
/// it between a detailed map and its massed twin asks the playthrough's own
/// question at compile time: same objectives, same order, same completion
/// oracle. The one thing that moves is where inside the detailed place the body
/// walks to — which is §7's "anchor positions within their box" being free, and
/// is the anchor RE-BINDING working: if this were byte-identical, the piece's own
/// anchor would not have replaced the massing's footing at all.
///
/// A full playthrough needs a server and a bot and is a runtime tier; this is
/// what can be measured without one, and it is not a substitute for it.
#[test]
fn the_bot_is_handed_the_same_path_with_one_cell_moved_inside_the_detailed_place() {
    let tmp = tempdir("bot-export");
    let d = detailed(&tmp, &["node/exit"]);
    let detailed_out = build_into(&d, &tmp.join("out-detailed"));

    // The massed twin: the same campaign with the binding taken away.
    std::fs::remove_file(d.campaign.join("detail-plan.json")).unwrap();
    let massed_out = build_into(&d, &tmp.join("out-massed"));

    let path = |t: &BTreeMap<String, Vec<u8>>| -> serde_json::Value {
        serde_json::from_slice(
            t.get("critical-path.json")
                .expect("every build exports the bot's path"),
        )
        .expect("it is JSON")
    };
    let (a, b) = (path(&detailed_out), path(&massed_out));
    let (sa, sb) = (
        a["steps"].as_array().unwrap(),
        b["steps"].as_array().unwrap(),
    );
    assert!(!sa.is_empty(), "the fixture has a critical path");
    assert_eq!(sa.len(), sb.len(), "the same number of steps");

    /// A step's displacement between the two builds, `detailed - massed`.
    fn delta(x: &serde_json::Value, y: &serde_json::Value) -> [i64; 3] {
        let (a, b) = (x.as_array(), y.as_array());
        match (a, b) {
            (Some(a), Some(b)) => std::array::from_fn(|i| {
                a[i].as_i64().expect("coord") - b[i].as_i64().expect("coord")
            }),
            _ => [0; 3],
        }
    }

    /// `v` with every `[x, y, z]` triple it holds translated by `d`.
    fn shift(v: &serde_json::Value, d: [i64; 3]) -> serde_json::Value {
        match v {
            serde_json::Value::Array(a)
                if a.len() == 3 && a.iter().all(serde_json::Value::is_i64) =>
            {
                serde_json::json!([
                    a[0].as_i64().unwrap() + d[0],
                    a[1].as_i64().unwrap() + d[1],
                    a[2].as_i64().unwrap() + d[2],
                ])
            }
            serde_json::Value::Object(o) => {
                serde_json::Value::Object(o.iter().map(|(k, w)| (k.clone(), shift(w, d))).collect())
            }
            other => other.clone(),
        }
    }

    let mut moved = 0usize;
    for (x, y) in sa.iter().zip(sb.iter()) {
        let xo = x.as_object().unwrap();
        // The one displacement §7 permits, taken once so every field below is
        // judged against it rather than against its own idea of what moved.
        let d = match (xo.get("pos"), y.get("pos")) {
            (Some(a), Some(b)) => delta(a, b),
            _ => [0; 3],
        };
        if d != [0; 3] {
            moved += 1;
        }
        for (k, v) in xo {
            if k == "pos" {
                continue;
            }
            // `completion` is not an independent fact about the step: it is the
            // anchor cell restated as the volume the server adjudicates in
            // (`reach::reach_completion`), so it necessarily follows `pos`.
            // Exempting it would be the weakening; demanding that it move by
            // EXACTLY the displacement `pos` moved by is stronger than the
            // equality it replaces, because it refuses a volume that failed to
            // follow the re-bound anchor — one clamped, cached, or resolved
            // against the massing's cell — and refuses one that changed shape on
            // the way. What it deliberately does NOT judge is the extent rule
            // itself, which is the same on both sides of this comparison;
            // `tests/reach_completion.rs` owns that.
            if k == "completion" {
                assert_eq!(
                    Some(v),
                    y.get(k).map(|w| shift(w, d)).as_ref(),
                    "step field `completion` did not follow `pos` by {d:?}; it is the \
                     anchor cell restated as a volume and may move only with it"
                );
                continue;
            }
            assert_eq!(
                Some(v),
                y.get(k),
                "step field `{k}` moved, and only a POSITION inside a detailed place may"
            );
        }
    }
    assert_eq!(
        moved, 1,
        "exactly one step moved — the one seated in the place a piece now stands in"
    );
    for k in a.as_object().unwrap().keys() {
        if k != "steps" {
            assert_eq!(
                a[k], b[k],
                "and nothing else about the contract moved: `{k}`"
            );
        }
    }
}

/// **Both binding lines reach a reader** — the builder's and the observer's.
///
/// `blockout::Binding::line()` had no production caller at all until stage 6:
/// the battery's count was printed and the derivation's was not, so a build
/// stated what was examined and never what was built. A line that is correct,
/// reviewable and reaches nobody is the UNRUN shape at its smallest, and the
/// repair is not a doc line — it is this assertion, over the process.
#[test]
fn a_build_states_what_it_built_as_well_as_what_it_examined() {
    let tmp = tempdir("binding-lines");
    let d = detailed(&tmp, &["node/exit"]);
    let out = delvec(&[
        "--prefabs",
        d.prefabs.to_str().unwrap(),
        "build",
        d.campaign.to_str().unwrap(),
        "--out",
        tmp.join("out").to_str().unwrap(),
    ]);
    let err = String::from_utf8_lossy(&out.stderr);
    assert_eq!(out.status.code(), Some(0), "{err}");
    assert!(
        err.contains("blockout binding:"),
        "the DERIVATION states what it bound to: {err}"
    );
    assert!(
        err.contains("(1 detailed, so 6 massed by the derivation)"),
        "and the split is the number stage 6 made load-bearing — a reader who \
         cannot see it cannot tell a fully detailed map from one binding nothing: \
         {err}"
    );
    assert!(
        err.contains("blockout battery binding:"),
        "and the OBSERVER states what it examined: {err}"
    );
    assert!(
        err.contains("detail binding:"),
        "as does the detail gate: {err}"
    );
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

fn check_and_expect(d: &Detailed, code: &str) -> String {
    let (diags, _) = check_at(d);
    let hit: Vec<_> = diags
        .iter()
        .filter(|x| x.code == code && x.severity == Severity::Error)
        .collect();
    assert_eq!(
        hit.len(),
        1,
        "expected exactly one {code}, got {:?}",
        codes(&diags)
    );
    hit[0].message.clone()
}

fn build_into(d: &Detailed, out: &Path) -> BTreeMap<String, Vec<u8>> {
    let loaded = delvec::compiler::load::load_campaign_dir(&d.campaign).unwrap();
    let c = delvewright_dsl::parse_campaign(&loaded.raw).unwrap();
    let reg = PrefabRegistry::load_dir(&d.prefabs).unwrap();
    let plan = Plan::build(&c, &reg).expect("the detailed campaign plans");
    let mut structures: BTreeMap<String, Vec<u8>> = BTreeMap::new();
    for area in &plan.areas {
        for piece in &area.pieces {
            for t in &piece.templates {
                if let Ok(bytes) = std::fs::read(d.prefabs.join(&t.structure_file)) {
                    structures.insert(t.structure_file.clone(), bytes);
                }
            }
        }
    }
    let tree = delvec::compiler::commands::CommandTree::v1_21_11();
    let (built, _warn) = delvec::compiler::emit::build_with_warnings(
        &plan,
        &loaded.inputs,
        &structures,
        &tree,
        &reg,
        None,
        &BTreeMap::new(),
    )
    .expect("the detailed campaign builds");
    let _ = out;
    built
}

/// A scratch directory of this test's own, removed and recreated so a rerun
/// never inherits the last run's files.
fn tempdir(name: &str) -> PathBuf {
    let p = std::env::temp_dir().join(format!("dw-detail-{name}"));
    let _ = std::fs::remove_dir_all(&p);
    std::fs::create_dir_all(&p).unwrap();
    p
}

/// The perturbation surface is an ARGUMENT, never a switch — asserted here for
/// the same reason `tests/blockout.rs` asserts it of the derivation: a
/// production path that could acquire a defect from a global is a production
/// path nothing can measure.
#[test]
fn the_detailed_build_runs_the_unperturbed_derivation() {
    let tmp = tempdir("unperturbed");
    let d = detailed(&tmp, &["node/exit"]);
    let c = campaign_at(&d.campaign);
    let reg = PrefabRegistry::load_dir(&d.prefabs).unwrap();
    let a = Plan::build(&c, &reg).expect("plans");
    let b = Plan::build_with(&c, &reg, Perturb::none()).expect("plans");
    let mass = |p: &Plan| -> Vec<String> {
        p.areas
            .iter()
            .flat_map(|x| x.mass.iter())
            .map(|f| format!("{:?}{:?}{}", f.from, f.to, f.block))
            .collect()
    };
    assert_eq!(mass(&a), mass(&b));
}
