#!/usr/bin/env node
// SPIKE TOOLING (area-effect / non-griefing-explosion arrow) — NOT part of the
// shipped pipeline, NOT wired into CI. Same shape as
// `tools/spike-death-teleport/` and `tools/spike-jump-arc/`.
//
// The question (owner, 2026-08-11): can a DATAPACK ALONE give the player an
// arrow that, on impact, produces either (1) an explosion that damages but does
// not break blocks, or (2) a splash-potion-style area effect — as an item that
// sits in a chest as scavenged loot?
//
// Everything below is measured on a live pinned vanilla 1.21.11 server. The two
// candidate mechanisms under test are data-driven enchantment effects, both
// confirmed present in the pinned server jar's own registry dump
// (`registries-1.21.11.json`, generated by `--reports`):
//
//   * `minecraft:hit_block`  — an enchantment effect component that fires when a
//     projectile shot with the enchanted item hits a BLOCK.
//   * `minecraft:explode` with `block_interaction: "none"` — an entity effect
//     that produces a real explosion.
//   * `minecraft:run_function` — an entity effect that runs an mcfunction.
//
// The competing hypothesis the no-hack rule cares about is per-tick polling for
// landed arrows (`as @e[type=arrow,nbt={inGround:1b}]`). The registry dump
// settles half of that on its own: `minecraft:trigger_type` has 58 entries and
// none of them is a projectile-hit trigger, so the advancement route does not
// exist. What is left to measure is whether the enchantment route is real, and
// exactly WHERE the authored behaviour has to live.
//
// PHASES. `--phase 1` builds the arena, runs every measurement, and leaves a
// chest of loot behind. `run.sh` then RESTARTS the server and runs `--phase 2`,
// which re-reads that chest and re-fires — the reload axis, measured rather than
// assumed.
//
// Raw observations go to --out as JSON and are committed next to the findings
// note so a future session checks the reasoning instead of repeating the run.

import { createRequire } from "node:module";
import { spawn } from "node:child_process";
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import readline from "node:readline";

const require = createRequire(new URL("../../harness/package.json", import.meta.url));
const mineflayer = require("mineflayer");

const CONTAINER = process.env.SPIKE_CONTAINER ?? "dw-spike-arrow";
const PORT = Number(process.env.SPIKE_PORT ?? 25599);
const OUT = process.env.SPIKE_OUT ?? new URL("./observations.json", import.meta.url).pathname;
const PHASE = Number(process.env.SPIKE_PHASE ?? 1);
const BOT_A = "dw_spike_a";
const BOT_B = "dw_spike_b";

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// ---------------------------------------------------------------- rcon channel
// One long-lived `rcon-cli` reading stdin, commands PIPELINED and every batch
// fenced by a `#sync` write/read whose value must come back — a desync aborts
// the run rather than silently shifting every later reading by one. Lifted from
// tools/spike-death-teleport/measure.mjs, which exists in this shape because an
// earlier spike never read a single rcon response and measured nothing.
const proc = spawn("docker", ["exec", "-i", CONTAINER, "rcon-cli"], {
  stdio: ["pipe", "pipe", "inherit"],
});
const rl = readline.createInterface({ input: proc.stdout });
const inbox = [];
let notify = null;
rl.on("line", (line) => {
  inbox.push(line.replace(/^>\s?/, ""));
  if (notify) {
    const n = notify;
    notify = null;
    n();
  }
});
async function readLines(n) {
  while (inbox.length < n) await new Promise((r) => (notify = r));
  return inbox.splice(0, n);
}
let syncN = 0;
async function batch(cmds) {
  const out = [];
  // rcon replies are line-oriented and a single huge write can outrun the
  // reader; chunk so a batch is never larger than the server will answer in one
  // breath.
  for (let i = 0; i < cmds.length; i += 200) {
    const slice = cmds.slice(i, i + 200);
    const n = ++syncN;
    const all = [
      `scoreboard players set #sync dw.sig ${n}`,
      ...slice,
      "scoreboard players get #sync dw.sig",
    ];
    proc.stdin.write(all.join("\n") + "\n");
    const r = await readLines(all.length);
    if (!r[r.length - 1].includes(`#sync has ${n} `)) {
      throw new Error(`rcon desync at ${n}; responses were ${JSON.stringify(r)}`);
    }
    out.push(...r.slice(1, -1));
  }
  return out;
}
const rcon = async (cmd) => (await batch([cmd]))[0];

// Rejection shapes that must never pass silently. `No blocks were filled` is a
// LEGITIMATE answer for the block census below (it means "zero"), so the census
// uses raw `rcon()` and parses it explicitly; every setup command goes through
// `ok()` and a rejection aborts the run.
const ERR = new RegExp(
  "^(Unknown or incomplete command|Incorrect argument|Expected |Invalid |Unknown " +
    "|That position is not loaded|Cannot place blocks outside of the world" +
    "|No blocks were filled|Could not set the block|No entity was found" +
    "|No targets matched|Malformed |Failed to )",
);
async function ok(cmd) {
  const r = await rcon(cmd);
  if (ERR.test(r)) throw new Error(`server rejected \`${cmd}\`: ${r}`);
  return r;
}

// ------------------------------------------------------------------- parsing
const DATA = / has the following entity data: /;
function nbt(line) {
  const i = line.search(DATA);
  return i < 0 ? null : line.slice(i).replace(DATA, "");
}
const num = (line) => {
  const v = nbt(line);
  return v === null ? null : Number.parseFloat(v);
};
const vec3 = (line) => {
  const v = nbt(line);
  if (v === null) return null;
  const m = v.match(/-?\d+(?:\.\d+)?(?:[eE]-?\d+)?/g);
  return m ? m.slice(0, 3).map(Number) : null;
};
const score = (line) => {
  const m = line.match(/ has (-?\d+) \[/);
  return m ? Number(m[1]) : null;
};
// A conditional `execute` with no `run` returns an EMPTY rcon response on
// 1.21.11, indistinguishable from a rejected command, so every boolean probe is
// spelled `execute <conditions> run time query gametime`.
const PROBE = "run time query gametime";
function flag(line) {
  if (line.startsWith("The time is")) return true;
  if (line === "") return false;
  throw new Error(`boolean probe did not evaluate: ${JSON.stringify(line)}`);
}
/**
 * `/fill` and `/kill` legitimately answer "No blocks were filled" / "No entity
 * was found" when there was nothing to do, and both strings are in `ERR`. So
 * setup that MAY be a no-op goes through `fill()` / `killq()`, which parse the
 * count; only genuinely-must-succeed commands go through `ok()`.
 */
async function fill(cmd) {
  const r = await rcon(cmd);
  return filled(r);
}
async function killq(sel) {
  const r = await rcon(`kill ${sel}`);
  if (ERR.test(r) && !/^No entity was found/.test(r)) {
    throw new Error(`server rejected \`kill ${sel}\`: ${r}`);
  }
  return r;
}

/** `/fill` reply -> number of blocks it changed. "No blocks were filled" is 0. */
function filled(line) {
  if (/^No blocks were filled/.test(line)) return 0;
  const m = line.match(/Successfully filled (\d+) block/);
  if (!m) throw new Error(`unparseable fill reply: ${JSON.stringify(line)}`);
  return Number(m[1]);
}

// ------------------------------------------------------------------- counters
const COUNTERS = [
  "#mark_hits", "#mark_has_exec", "#mark_exec_arrow", "#mark_exec_player",
  "#none_hits", "#tnt_hits", "#cloud_hits", "#ammo_hits", "#ammo_matched", "#dmg_hits",
];
async function zeroCounters() {
  await batch(COUNTERS.map((c) => `scoreboard players set ${c} dw.sig 0`));
  await batch([
    "kill @e[type=minecraft:marker]",
    "kill @e[type=minecraft:arrow]",
    "kill @e[type=minecraft:spectral_arrow]",
    "kill @e[type=minecraft:area_effect_cloud]",
  ]);
}
async function readCounters() {
  const r = await batch(COUNTERS.map((c) => `scoreboard players get ${c} dw.sig`));
  return Object.fromEntries(COUNTERS.map((c, i) => [c.slice(1), score(r[i]) ?? 0]));
}

// -------------------------------------------------------------------- geometry
// Superflat: bedrock -64, dirt -63/-62, grass_block -61. Standing surface -60.
const SURF = -60;
const SITES = {
  block: 110, // glass census box
  entity: 200, // mobs at known radii
  decor: 260, // armour stand / dropped item / item frame
  cloud: 300, // area_effect_cloud route
  terrain: 400, // water, slab, entity-hit
  player: 500, // bot-fired bow
  chest: 560, // the loot chest that must survive a restart
};
const ench = (id) =>
  `{id:"minecraft:bow",count:1,components:{"minecraft:enchantments":{"${id}":1}}}`;

/** Drop an arrow straight down a shaft onto the floor at (x, SURF-1, z). */
async function dropArrow(x, z, { weapon = null, item = null, tag = "shot", from = SURF + 12 } = {}) {
  const parts = [`Tags:["${tag}"]`, "Motion:[0.0d,-2.2d,0.0d]"];
  if (weapon) parts.push(`weapon:${weapon}`);
  if (item) parts.push(`item:${item}`);
  await ok(`summon minecraft:arrow ${x + 0.5} ${from} ${z + 0.5} {${parts.join(",")}}`);
}
/** Wait until the shot arrow has stuck (or died), so a trial never reads early. */
async function settle(tag, ms = 4000) {
  const deadline = Date.now() + ms;
  while (Date.now() < deadline) {
    const r = await rcon(`execute if entity @e[tag=${tag},nbt={inGround:1b}] ${PROBE}`);
    if (flag(r)) return true;
    await sleep(100);
  }
  return false;
}

// ============================================================== A. binding
// WHERE must the enchantment live for `hit_block` to fire? The product question
// is "an ARROW in a chest", so this is the measurement the whole ruling turns on.
async function bindingMatrix() {
  const plainArrowItem = `{id:"minecraft:arrow",count:1}`;
  const enchArrowItem =
    `{id:"minecraft:arrow",count:1,components:{"minecraft:enchantments":{"dwspike:mark":1}}}`;
  const enchBow = ench("dwspike:mark");
  const plainBow = `{id:"minecraft:bow",count:1}`;
  const cases = [
    { name: "weapon=enchanted bow, ammo=plain arrow", weapon: enchBow, item: plainArrowItem },
    { name: "weapon=plain bow, ammo=ENCHANTED arrow", weapon: plainBow, item: enchArrowItem },
    { name: "no weapon field, ammo=ENCHANTED arrow", weapon: null, item: enchArrowItem },
    { name: "no weapon field, ammo=plain arrow", weapon: null, item: plainArrowItem },
    { name: "weapon=enchanted bow, ammo=ENCHANTED arrow", weapon: enchBow, item: enchArrowItem },
  ];
  const rows = [];
  for (const c of cases) {
    await zeroCounters();
    await dropArrow(SITES.block, 0, { weapon: c.weapon, item: c.item, tag: "bind" });
    await settle("bind");
    await sleep(400);
    const counters = await readCounters();
    const ctx = await rcon("data get entity @e[tag=dwspike_ctx,limit=1] Pos");
    const execPos = await rcon("data get entity @e[tag=dwspike_execpos,limit=1] Pos");
    const arrowPos = await rcon("data get entity @e[tag=bind,limit=1] Pos");
    // `/data get entity <e> id` is not a path on 1.21.11, so the executor's
    // TYPE is read with boolean probes instead of parsed out of a dump.
    const [isArrow, isAny] = await batch([
      `execute if entity @e[tag=dwspike_exec,type=minecraft:arrow] ${PROBE}`,
      `execute if entity @e[tag=dwspike_exec] ${PROBE}`,
    ]);
    rows.push({
      case: c.name,
      weapon: c.weapon,
      ammo: c.item,
      fired: counters.mark_hits > 0,
      counters,
      function_position: vec3(ctx),
      executor_position: vec3(execPos),
      arrow_rest_position: vec3(arrowPos),
      executor_tag_landed_on_any_entity: flag(isAny),
      executor_is_the_arrow_entity: flag(isArrow),
    });
    console.log(
      `[bind] ${c.name}: fired=${counters.mark_hits > 0} execIsArrow=${flag(isArrow)} ` +
        `fnPos=${JSON.stringify(vec3(ctx))}`,
    );
    await batch(["kill @e[tag=bind]", "kill @e[tag=dwspike_exec]"]);
  }
  return rows;
}

// ============================================================== B. block damage
// "Does not break blocks" is measured, never assumed from a name. The box is
// SOLID glass (blast resistance 0.3 — about the most fragile full block there
// is) with a four-cell shaft for the arrow. After the shot,
// `fill … replace minecraft:air` answers with the number of air cells, which is
// the shaft plus whatever the explosion took, and rebuilds the box for the next
// trial in the same breath.
const BOX = { x0: 107, y0: -63, z0: -3, x1: 113, y1: -57, z1: 3 };
const SHAFT_CELLS = 4; // (110, -60..-57, 0)
async function buildGlassBox() {
  await fill(`fill ${BOX.x0} ${BOX.y0} ${BOX.z0} ${BOX.x1} ${BOX.y1} ${BOX.z1} minecraft:glass`);
  await fill(`fill ${SITES.block} ${SURF} 0 ${SITES.block} ${SURF + 3} 0 minecraft:air`);
}
async function censusAir() {
  const r = await rcon(
    `fill ${BOX.x0} ${BOX.y0} ${BOX.z0} ${BOX.x1} ${BOX.y1} ${BOX.z1} minecraft:glass replace minecraft:air`,
  );
  return filled(r);
}
async function blockDamage() {
  const rows = [];
  for (const id of ["dwspike:blast_none", "dwspike:blast_off_1", "dwspike:blast_dmg", "dwspike:blast_tnt"]) {
    await zeroCounters();
    await buildGlassBox();
    const before = await censusAir(); // rebuilds; must be exactly the shaft
    await buildGlassBox();
    await dropArrow(SITES.block, 0, { weapon: ench(id), tag: "blk" });
    await settle("blk");
    await sleep(800);
    const counters = await readCounters();
    const centre = vec3(
      await rcon("data get entity @e[tag=dwspike_none,limit=1] Pos"),
    ) ?? vec3(await rcon("data get entity @e[tag=dwspike_tnt,limit=1] Pos"));
    const air = await censusAir();
    const destroyed = air - SHAFT_CELLS;
    rows.push({
      enchantment: id,
      box: BOX,
      box_cells: (BOX.x1 - BOX.x0 + 1) * (BOX.y1 - BOX.y0 + 1) * (BOX.z1 - BOX.z0 + 1),
      shaft_cells: SHAFT_CELLS,
      effect_position: centre,
      air_cells_before_shot: before,
      air_cells_after_shot: air,
      glass_blocks_destroyed: destroyed,
      effect_fired: counters.none_hits + counters.tnt_hits + counters.dmg_hits > 0,
      counters,
    });
    console.log(
      `[block] ${id}: fired=${counters.none_hits + counters.tnt_hits + counters.dmg_hits > 0} ` +
        `airBefore=${before} airAfter=${air} destroyed=${destroyed}`,
    );
    await batch(["kill @e[tag=blk]"]);
  }
  await buildGlassBox();
  return rows;
}

// ============================================================== C. entity damage
// Six immobile zombies at 1..6 blocks from the impact cell. NoAI so knockback
// cannot move them out of their own measurement.
/**
 * Damage profile against distance, with a VANILLA PRIMED TNT of the same radius
 * as the calibration row. Targets are immobile, unarmoured and given 400 max
 * health so nothing dies mid-measurement and every reading is a subtraction.
 *
 * `time set midnight` matters: at noon these zombies burn, and burning damage
 * (1.0/s through 2 natural armour = 0.92) is almost exactly the number the
 * unoffset explosion produces, which is how a contaminated first run read as a
 * working explosion.
 */
const DISTS = [1, 2, 3, 4, 6, 8];
async function entityDamage(label, fire, { targetY = SURF } = {}) {
  const x = SITES.entity;
  await fill(`fill ${x - 20} ${SURF - 1} -20 ${x + 20} ${SURF - 1} 20 minecraft:stone`);
  await fill(`fill ${x - 20} ${SURF} -20 ${x + 20} ${SURF + 8} 20 minecraft:air`);
  await killq("@e[type=minecraft:zombie]");
  for (const d of DISTS) {
    await ok(
      `summon minecraft:zombie ${x + 0.5} ${targetY} ${d + 0.5} ` +
        `{NoAI:1b,Silent:1b,PersistenceRequired:1b,NoGravity:1b,Tags:["z${d}"],` +
        `attributes:[{id:"minecraft:armor",base:0.0},{id:"minecraft:max_health",base:400.0}],` +
        `Health:400.0f}`,
    );
  }
  await sleep(1200);
  const before = await batch(DISTS.map((d) => `data get entity @e[tag=z${d},limit=1] Health`));
  await zeroCounters();
  await fire();
  await sleep(4000);
  const after = await batch(DISTS.map((d) => `data get entity @e[tag=z${d},limit=1] Health`));
  const counters = await readCounters();
  const rows = DISTS.map((d, i) => ({
    distance_blocks: d,
    health_before: num(before[i]),
    health_after: num(after[i]),
    damage:
      num(before[i]) === null || num(after[i]) === null
        ? "dead-or-gone"
        : Number((num(before[i]) - num(after[i])).toFixed(2)),
  }));
  console.log(
    `[entity] ${label.padEnd(46)} ` + rows.map((r) => `${r.distance_blocks}b:${r.damage}`).join(" "),
  );
  await killq("@e[type=minecraft:zombie]");
  await killq("@e[type=minecraft:arrow]");
  return { case: label, target_feet_y: targetY, counters, rows };
}
async function entityDamageSuite() {
  const x = SITES.entity;
  const tnt = (y) => async () => ok(`summon minecraft:tnt ${x + 0.5} ${y} 0.5 {fuse:1s}`);
  const shot = (id) => async () => dropArrow(x, 0, { weapon: ench(id), tag: "ent" });
  const out = [];
  out.push(await entityDamage("CONTROL vanilla primed TNT on the floor (radius 4)", tnt(SURF)));
  out.push(await entityDamage("CONTROL vanilla primed TNT one block up", tnt(SURF + 1)));
  out.push(await entityDamage("explode block_interaction=none, default offset", shot("dwspike:blast_none")));
  out.push(await entityDamage("explode none, radius 8, default offset", shot("dwspike:blast_r8")));
  out.push(await entityDamage("explode none, attribute_to_user=false", shot("dwspike:blast_unattr")));
  out.push(await entityDamage("explode none, offset [0,1,0]", shot("dwspike:blast_off_1")));
  out.push(await entityDamage("explode block_interaction=tnt, default offset", shot("dwspike:blast_tnt")));
  out.push(await entityDamage("run_function -> /damage in a radius", shot("dwspike:blast_dmg")));
  // Targets lifted to the explosion's own height: separates OCCLUSION by the
  // floor from the effect's own damage.
  out.push(
    await entityDamage("CONTROL vanilla TNT, targets floating at centre height", tnt(SURF + 1), {
      targetY: SURF + 1,
    }),
  );
  out.push(
    await entityDamage("explode none offset [0,1,0], targets at centre height",
      shot("dwspike:blast_off_1"), { targetY: SURF + 1 }),
  );
  return out;
}

/**
 * The same explosion against a WALL instead of a floor. A fixed world-space
 * `offset` can only point one way; the impact normal is not available to the
 * effect, so this measures what an author gets when the same authored arrow is
 * fired at a vertical surface.
 */
async function orientationSuite() {
  const x = SITES.terrain;
  const out = [];
  const FACE = x + 10; // the wall's -X face
  const DS = [1, 2, 3];
  for (const id of ["dwspike:blast_none", "dwspike:blast_off_1", "dwspike:blast_dmg"]) {
    await fill(`fill ${x - 20} ${SURF - 1} -20 ${x + 20} ${SURF - 1} 20 minecraft:stone`);
    await fill(`fill ${x - 20} ${SURF} -20 ${x + 20} ${SURF + 8} 20 minecraft:air`);
    // A wall 6 blocks thick in +X and 8 tall, so a +Y offset stays inside stone.
    await fill(`fill ${FACE} ${SURF} -6 ${FACE + 5} ${SURF + 8} 6 minecraft:stone`);
    await killq("@e[type=minecraft:zombie]");
    // Targets sit BESIDE the flight line (which runs along z = 0.5), never on
    // it: the first version of this trial put them in front of the wall and
    // measured the arrow's own 5 HP hit instead of an explosion.
    for (const d of DS) {
      await ok(
        `summon minecraft:zombie ${FACE - 0.5} ${SURF + 2} ${d + 0.5} ` +
          `{NoAI:1b,Silent:1b,PersistenceRequired:1b,NoGravity:1b,Tags:["w${d}"],` +
          `attributes:[{id:"minecraft:armor",base:0.0},{id:"minecraft:max_health",base:400.0}],Health:400.0f}`,
      );
    }
    await sleep(1000);
    const before = await batch(DS.map((d) => `data get entity @e[tag=w${d},limit=1] Health`));
    await zeroCounters();
    await ok(
      `summon minecraft:arrow ${x + 2}.5 ${SURF + 2.5} 0.5 ` +
        `{Tags:["wall"],Motion:[2.2d,0.0d,0.0d],weapon:${ench(id)}}`,
    );
    await sleep(4000);
    const after = await batch(DS.map((d) => `data get entity @e[tag=w${d},limit=1] Health`));
    const counters = await readCounters();
    const impact = vec3(await rcon("data get entity @e[tag=wall,limit=1] Pos"));
    // The function's position IS the explosion centre — the number that decides
    // whether the blast is occluded by the surface it hit.
    const centre = vec3(await rcon("data get entity @e[tag=dwspike_none,limit=1] Pos"));
    const rows = DS.map((d, i) => ({
      distance_blocks: d,
      damage: Number(((num(before[i]) ?? 0) - (num(after[i]) ?? 0)).toFixed(2)),
    }));
    console.log(
      `[wall] ${id.padEnd(24)} fired=${counters.none_hits + counters.dmg_hits > 0} ` +
        `impact=${JSON.stringify(impact)} ` + rows.map((r) => `${r.distance_blocks}b:${r.damage}`).join(" "),
    );
    out.push({
      enchantment: id,
      surface: "vertical stone wall 6 blocks thick, arrow fired horizontally, targets beside the flight line",
      fired: counters.none_hits + counters.dmg_hits > 0,
      arrow_rest_position: impact,
      effect_position: centre,
      counters,
      rows,
    });
    await batch(["kill @e[tag=wall]", "kill @e[type=minecraft:zombie]"]);
  }
  return out;
}

// ======================================================== D. decorations / map
// `block_interaction: "none"` is about BLOCKS. An explosion still damages
// ENTITIES, and a box-garden's set dressing is entities. Measured, not assumed.
async function decorationDamage(enchId) {
  const x = SITES.decor;
  await fill(`fill ${x - 8} ${SURF - 1} -8 ${x + 8} ${SURF - 1} 8 minecraft:stone`);
  await fill(`fill ${x - 8} ${SURF} -8 ${x + 8} ${SURF + 14} 8 minecraft:air`);
  await batch([
    "kill @e[type=minecraft:armor_stand]",
    "kill @e[type=minecraft:item_frame]",
    "kill @e[type=minecraft:item]",
    "kill @e[type=minecraft:item_display]",
    "kill @e[type=minecraft:text_display]",
  ]);
  // A wall for the item frame to hang on, two blocks from the impact cell.
  await fill(`fill ${x + 2} ${SURF} 0 ${x + 2} ${SURF} 0 minecraft:stone`);
  await ok(`summon minecraft:armor_stand ${x + 0.5} ${SURF} 1.5 {Tags:["deco_as"],Invulnerable:0b}`);
  await ok(
    `summon minecraft:item_frame ${x + 1} ${SURF} 0 ` +
      `{Tags:["deco_if"],Facing:4b,Item:{id:"minecraft:diamond",count:1}}`,
  );
  await ok(
    `summon minecraft:item ${x + 0.5} ${SURF} -1.5 ` +
      `{Tags:["deco_item"],Item:{id:"minecraft:arrow",count:8},PickupDelay:32767s,Age:-32768s}`,
  );
  await ok(
    `summon minecraft:item_display ${x + 0.5} ${SURF} 2.5 ` +
      `{Tags:["deco_id"],item:{id:"minecraft:lantern",count:1}}`,
  );
  await ok(`summon minecraft:text_display ${x + 0.5} ${SURF + 1} -2.5 {Tags:["deco_td"]}`);
  await sleep(400);
  const names = ["deco_as", "deco_if", "deco_item", "deco_id", "deco_td"];
  const before = await batch(names.map((n) => `execute if entity @e[tag=${n}] ${PROBE}`));
  await zeroCounters();
  await dropArrow(x, 0, { weapon: ench(enchId), tag: "dec" });
  await settle("dec");
  await sleep(1200);
  const after = await batch(names.map((n) => `execute if entity @e[tag=${n}] ${PROBE}`));
  const rows = names.map((n, i) => ({
    entity: n,
    present_before: flag(before[i]),
    present_after: flag(after[i]),
    destroyed: flag(before[i]) && !flag(after[i]),
  }));
  console.log(
    `[decor] ${enchId}: ` + rows.map((r) => `${r.entity}:${r.destroyed ? "DESTROYED" : "ok"}`).join(" "),
  );
  return { enchantment: enchId, rows };
}

// ============================================================== E. the AEC route
// The splash-potion-style half. `run_function` at the impact point summons a
// vanilla `area_effect_cloud`; the question is whether the cloud exists, sits at
// the impact, persists, and reaches EVERY player standing in it, not just the
// shooter.
async function cloudRoute(bots) {
  const x = SITES.cloud;
  await fill(`fill ${x - 8} ${SURF - 1} -8 ${x + 8} ${SURF - 1} 8 minecraft:stone`);
  await fill(`fill ${x - 8} ${SURF} -8 ${x + 8} ${SURF + 14} 8 minecraft:air`);
  await zeroCounters();
  // Both bots stand inside the future cloud; neither of them fired the arrow.
  await batch([
    `gamemode survival ${BOT_A}`,
    `gamemode survival ${BOT_B}`,
    `effect clear ${BOT_A}`,
    `effect clear ${BOT_B}`,
    `tp ${BOT_A} ${x + 1.5} ${SURF} 0.5`,
    `tp ${BOT_B} ${x - 1.5} ${SURF} 0.5`,
    `effect give ${BOT_A} minecraft:instant_health 1 10 true`,
    `effect give ${BOT_B} minecraft:instant_health 1 10 true`,
  ]);
  await sleep(1200);
  const hpBefore = await batch([
    `data get entity ${BOT_A} Health`,
    `data get entity ${BOT_B} Health`,
  ]);
  await dropArrow(x, 0, { weapon: ench("dwspike:cloud"), tag: "cld" });
  await settle("cld");
  await sleep(1500);
  const counters = await readCounters();
  const cloudPos = await rcon("data get entity @e[tag=dwspike_cloud,limit=1] Pos");
  const cloudNbt = await rcon("data get entity @e[tag=dwspike_cloud,limit=1] potion_contents");
  const hpAfter = await batch([
    `data get entity ${BOT_A} Health`,
    `data get entity ${BOT_B} Health`,
  ]);
  const glow = await batch([
    `execute as ${BOT_A} if predicate {"condition":"minecraft:entity_properties","entity":"this","predicate":{"effects":{"minecraft:glowing":{}}}} ${PROBE}`,
    `execute as ${BOT_B} if predicate {"condition":"minecraft:entity_properties","entity":"this","predicate":{"effects":{"minecraft:glowing":{}}}} ${PROBE}`,
  ]);
  await sleep(2500);
  const stillThere = flag(await rcon(`execute if entity @e[tag=dwspike_cloud] ${PROBE}`));
  const out = {
    counters,
    cloud_summoned: counters.cloud_hits > 0,
    cloud_position: vec3(cloudPos),
    cloud_potion_contents: nbt(cloudNbt),
    cloud_alive_after_4s: stillThere,
    players: [
      {
        player: BOT_A, role: "bystander (did not shoot)",
        hp_before: num(hpBefore[0]), hp_after: num(hpAfter[0]),
        damage: Number(((num(hpBefore[0]) ?? 0) - (num(hpAfter[0]) ?? 0)).toFixed(2)),
        glowing_after: flag(glow[0]),
      },
      {
        player: BOT_B, role: "second bystander",
        hp_before: num(hpBefore[1]), hp_after: num(hpAfter[1]),
        damage: Number(((num(hpBefore[1]) ?? 0) - (num(hpAfter[1]) ?? 0)).toFixed(2)),
        glowing_after: flag(glow[1]),
      },
    ],
  };
  console.log(
    `[cloud] summoned=${out.cloud_summoned} pos=${JSON.stringify(out.cloud_position)} ` +
      out.players.map((p) => `${p.player}:dmg=${p.damage},glow=${p.glowing_after}`).join(" "),
  );
  await batch(["kill @e[type=minecraft:area_effect_cloud]", "kill @e[tag=cld]"]);
  return out;
}

// ============================================================== F. the axes
/** Water, slab, and the arrow that hits an ENTITY instead of a block. */
async function terrainAxes(bots) {
  const x = SITES.terrain;
  const rows = [];
  await fill(`fill ${x - 10} ${SURF - 1} -10 ${x + 10} ${SURF - 1} 10 minecraft:stone`);
  await fill(`fill ${x - 10} ${SURF} -10 ${x + 10} ${SURF + 16} 10 minecraft:air`);

  // --- water: a 4-deep column the arrow must swim through before it lands.
  await fill(`fill ${x} ${SURF - 4} 0 ${x} ${SURF - 1} 0 minecraft:stone`);
  await fill(`fill ${x - 1} ${SURF - 4} -1 ${x + 1} ${SURF - 1} 1 minecraft:stone`);
  await fill(`fill ${x} ${SURF - 3} 0 ${x} ${SURF - 1} 0 minecraft:water`);
  await zeroCounters();
  await dropArrow(x, 0, { weapon: ench("dwspike:mark"), tag: "water", from: SURF + 10 });
  await settle("water", 8000);
  await sleep(600);
  rows.push({
    axis: "arrow lands in water (3-deep column)",
    counters: await readCounters(),
    function_position: vec3(await rcon("data get entity @e[tag=dwspike_ctx,limit=1] Pos")),
    arrow_position: vec3(await rcon("data get entity @e[tag=water,limit=1] Pos")),
  });

  // --- bottom slab: a non-full block, top face at y = SURF - 0.5.
  await fill(`fill ${x + 4} ${SURF - 1} 0 ${x + 4} ${SURF - 1} 0 minecraft:stone`);
  await fill(`fill ${x + 4} ${SURF} 0 ${x + 4} ${SURF} 0 minecraft:smooth_stone_slab[type=bottom]`);
  await zeroCounters();
  await dropArrow(x + 4, 0, { weapon: ench("dwspike:mark"), tag: "slab", from: SURF + 10 });
  await settle("slab");
  await sleep(600);
  rows.push({
    axis: "arrow lands on a bottom slab (non-full block)",
    counters: await readCounters(),
    function_position: vec3(await rcon("data get entity @e[tag=dwspike_ctx,limit=1] Pos")),
    arrow_position: vec3(await rcon("data get entity @e[tag=slab,limit=1] Pos")),
  });

  // --- the arrow that hits an ENTITY: hit_block must NOT fire, and the
  //     `post_attack` variant must. This is the shape a player will notice
  //     first — a bomb arrow that does nothing when it hits the monster.
  for (const [id, label, byPlayer] of [
    ["dwspike:blast_none", "hit_block only, summoned arrow", false],
    ["dwspike:blast_both", "hit_block + post_attack, summoned arrow", false],
    ["dwspike:blast_both", "hit_block + post_attack, arrow OWNED by a player", true],
  ]) {
    await killq("@e[type=minecraft:zombie]");
    await ok(
      `summon minecraft:zombie ${x + 8.5} ${SURF} 0.5 ` +
        `{NoAI:1b,Silent:1b,PersistenceRequired:1b,NoGravity:1b,Tags:["target"],` +
        `attributes:[{id:"minecraft:armor",base:0.0},{id:"minecraft:max_health",base:400.0}],Health:400.0f}`,
    );
    // Bystanders beside the target, off the flight line: the gameplay question
    // is not "does the arrow hurt what it hits" but "does hitting a monster set
    // off the blast on the ones around it".
    for (const d of [1, 2, 3]) {
      await ok(
        `summon minecraft:zombie ${x + 8.5} ${SURF} ${d + 0.5} ` +
          `{NoAI:1b,Silent:1b,PersistenceRequired:1b,NoGravity:1b,Tags:["by${d}"],` +
          `attributes:[{id:"minecraft:armor",base:0.0},{id:"minecraft:max_health",base:400.0}],Health:400.0f}`,
      );
    }
    await sleep(700);
    const hpBefore = num(await rcon("data get entity @e[tag=target,limit=1] Health"));
    const byBefore = await batch([1, 2, 3].map((d) => `data get entity @e[tag=by${d},limit=1] Health`));
    await zeroCounters();
    // Fired horizontally into the zombie's hitbox so the FIRST thing it touches
    // is the entity, not the floor. A SUMMONED arrow has no owner, so
    // `post_attack` (which resolves `attacker`) may have nothing to bind to —
    // hence the player-fired repeat.
    if (byPlayer) {
      // `post_attack` resolves an `attacker`; a summoned arrow has no owner, so
      // the same shot is repeated with the bot's UUID installed as `Owner`.
      // Deterministic, unlike aiming a bot at a hitbox.
      const uuid = nbt(await rcon(`data get entity ${BOT_A} UUID`));
      await ok(
        `summon minecraft:arrow ${x + 4.5} ${SURF + 1} 0.5 ` +
          `{Tags:["ehit"],Motion:[2.0d,0.0d,0.0d],weapon:${ench(id)},Owner:${uuid}}`,
      );
    } else {
      await ok(
        `summon minecraft:arrow ${x + 4.5} ${SURF + 1} 0.5 ` +
          `{Tags:["ehit"],Motion:[2.0d,0.0d,0.0d],weapon:${ench(id)}}`,
      );
    }
    await sleep(3000);
    const hpAfter = num(await rcon("data get entity @e[tag=target,limit=1] Health"));
    const byAfter = await batch([1, 2, 3].map((d) => `data get entity @e[tag=by${d},limit=1] Health`));
    const counters = await readCounters();
    const centre = vec3(await rcon("data get entity @e[tag=dwspike_none,limit=1] Pos"));
    rows.push({
      axis: `arrow hits an ENTITY (${label})`,
      enchantment: id,
      target_health_before: hpBefore,
      target_health_after: hpAfter,
      target_damage: Number(((hpBefore ?? 0) - (hpAfter ?? 0)).toFixed(3)),
      bystanders: [1, 2, 3].map((d, i) => ({
        distance_blocks: d,
        damage: Number(((num(byBefore[i]) ?? 0) - (num(byAfter[i]) ?? 0)).toFixed(2)),
      })),
      effect_position: centre,
      counters,
      explosion_fired: counters.none_hits > 0,
    });
    console.log(
      `[axis] entity-hit ${label}: fired=${counters.none_hits > 0} target ` +
        `${(hpBefore - hpAfter).toFixed(2)} bystanders ` +
        [1, 2, 3].map((d, i) => `${d}b:${(num(byBefore[i]) - num(byAfter[i])).toFixed(2)}`).join(" "),
    );
    await batch(["kill @e[tag=ehit]", "kill @e[type=minecraft:zombie]"]);
  }

  // --- shot by a MOB: a skeleton holding the enchanted bow.
  // The floor has to reach the bot: the first version put it at x+14 over a
  // floor that ended at x+10 and the bot fell out of the world instead of being
  // shot at.
  await fill(`fill ${x - 4} ${SURF - 1} -8 ${x + 24} ${SURF - 1} 8 minecraft:stone`);
  await fill(`fill ${x - 4} ${SURF} -8 ${x + 24} ${SURF + 8} 8 minecraft:air`);
  await zeroCounters();
  await ok(
    `summon minecraft:skeleton ${x} ${SURF} 0.5 {Tags:["sk"],PersistenceRequired:1b,` +
      // COMPONENT-ERA `equipment`, not legacy `HandItems`: 1.21.11 silently
      // ignores `HandItems`/`HandDropChances` on `/summon`, so the first
      // version of this trial armed the skeleton with nothing and read as
      // "a mob-shot arrow does not fire the enchantment". The engine already
      // emits the component form (crates/compiler/src/emit.rs default_equipment).
      `equipment:{mainhand:${ench("dwspike:blast_none")}},drop_chances:{mainhand:0.0f},` +
      `attributes:[{id:"minecraft:follow_range",base:64.0}]}`,
  );
  await ok(`gamemode survival ${BOT_A}`);
  // `natural_health_regeneration` is off for the whole run, so the bot is still
  // carrying the area-effect trial's 9 damage unless it is healed here.
  await ok(`effect give ${BOT_A} minecraft:instant_health 1 10 true`);
  await ok(`effect give ${BOT_A} minecraft:resistance 120 4 true`);
  await ok(`tp ${BOT_A} ${x + 9.5} ${SURF} 0.5`);
  await ok("difficulty hard");
  await sleep(1500);
  // Waiting for a skeleton to notice a motionless bot is not a measurement, it
  // is a hope. Provoking it with an attributed `/damage` makes the retaliation
  // deterministic — and retaliation still goes through the mob's ordinary
  // ranged attack, which is the thing under test.
  await ok(`damage @e[tag=sk] 1 minecraft:player_attack by ${BOT_A}`);
  await ok("difficulty hard");
  const skEquip = nbt(await rcon(`data get entity @e[tag=sk,limit=1] equipment`));
  let mobFired = null;
  let skArrowSeen = null;
  for (let i = 0; i < 60; i++) {
    await sleep(1000);
    if (!skArrowSeen) {
      const w = await rcon("data get entity @e[type=minecraft:arrow,limit=1] weapon");
      if (nbt(w) !== null) skArrowSeen = nbt(w);
    }
    const c = await readCounters();
    if (c.none_hits > 0) {
      mobFired = c;
      break;
    }
    if (i % 10 === 9) await ok(`damage @e[tag=sk] 1 minecraft:player_attack by ${BOT_A}`);
  }
  const mobCounters = mobFired ?? (await readCounters());
  const skArrow = await rcon("data get entity @e[type=minecraft:arrow,limit=1] weapon");
  // A skeleton on hard difficulty rarely misses a stationary bot, so its arrows
  // hit an ENTITY and `hit_block` legitimately does not fire. The remaining half
  // of the axis — does a MOB-OWNED arrow whose `weapon` is the enchanted bow set
  // the effect off when it lands on a block — is measured directly here, with
  // the skeleton itself as the owner.
  const skUuid = nbt(await rcon("data get entity @e[tag=sk,limit=1] UUID"));
  await zeroCounters();
  await dropArrow(x, 6, {
    weapon: ench("dwspike:blast_none"),
    tag: "skdrop",
    from: SURF + 12,
  });
  await settle("skdrop");
  await sleep(600);
  const skDropPlain = (await readCounters()).none_hits > 0;
  await zeroCounters();
  await ok(
    `summon minecraft:arrow ${x + 0.5} ${SURF + 12} 6.5 ` +
      `{Tags:["skdrop2"],Motion:[0.0d,-2.2d,0.0d],weapon:${ench("dwspike:blast_none")},Owner:${skUuid}}`,
  );
  await settle("skdrop2");
  await sleep(600);
  const skDropOwned = (await readCounters()).none_hits > 0;
  const botAlive = flag(await rcon(`execute if entity @a[name=${BOT_A},nbt={Health:20.0f}] ${PROBE}`));
  rows.push({
    axis: "arrow shot by a MOB (skeleton holding the enchanted bow)",
    counters: mobCounters,
    fired: mobCounters.none_hits > 0,
    skeleton_arrow_weapon_field: nbt(skArrow) ?? skArrowSeen,
    skeleton_arrow_weapon_field_first_seen: skArrowSeen,
    skeleton_equipment_after_summon: skEquip,
    mob_owned_arrow_landing_on_a_block_fires: skDropOwned,
    unowned_arrow_landing_on_a_block_fires: skDropPlain,
    skeleton_still_present: flag(await rcon(`execute if entity @e[tag=sk] ${PROBE}`)),
    target_bot_at_full_health: botAlive,
  });
  console.log(
    `[axis] mob-shot: skeleton arrow weapon=${(nbt(skArrow) ?? skArrowSeen) ? "ENCHANTED BOW" : "-"} ` +
      `hit_block-on-block(mob-owned)=${skDropOwned} (unowned)=${skDropPlain}`,
  );
  await batch([`kill @e[tag=sk]`, `effect clear ${BOT_A}`, "kill @e[type=minecraft:arrow]"]);

  // --- shot by a DISPENSER: no weapon item exists, so nothing should fire.
  for (const [ammo, label] of [
    ['{Slot:0b,id:"minecraft:arrow",count:16}', "ordinary arrows"],
    [
      '{Slot:0b,id:"minecraft:arrow",count:16,components:{"minecraft:enchantments":{"dwspike:mark":1}}}',
      "ENCHANTED arrows (the enchantment on the ammunition itself)",
    ],
  ]) {
    await fill(`fill ${x - 4} ${SURF} -8 ${x + 24} ${SURF + 8} 8 minecraft:air`);
    await ok(`setblock ${x} ${SURF} 0 minecraft:dispenser[facing=east]{Items:[${ammo}]}`);
    await fill(`fill ${x + 6} ${SURF} -2 ${x + 6} ${SURF + 4} 2 minecraft:stone`);
    await zeroCounters();
    await ok(`setblock ${x} ${SURF + 1} 0 minecraft:redstone_block`);
    await sleep(3000);
    const c = await readCounters();
    const arrows = flag(await rcon(`execute if entity @e[type=minecraft:arrow] ${PROBE}`));
    console.log(`[axis] dispenser (${label}): fired=${c.mark_hits > 0} arrowSpawned=${arrows}`);
    rows.push({
      axis: `arrow shot by a DISPENSER — ${label}`,
      counters: c,
      fired: c.mark_hits > 0,
      an_arrow_entity_existed: arrows,
    });
    await batch([
      `setblock ${x} ${SURF + 1} 0 minecraft:air`,
      `setblock ${x} ${SURF} 0 minecraft:air`,
      "kill @e[type=minecraft:arrow]",
    ]);
  }
  return rows;
}

// ============================================== G. the player-fired path
// Everything above summons arrows. This fires one from a real bow held by a real
// client, which is the only way to learn what the `weapon` field is populated
// with on the path the player actually takes — and whether the AMMUNITION's own
// components survive to the impact, which is what decides whether a scavenged
// arrow can be told apart from an ordinary one.
async function playerShot(bots) {
  const x = SITES.player;
  await fill(`fill ${x - 4} ${SURF - 1} -4 ${x + 40} ${SURF - 1} 4 minecraft:stone`);
  await fill(`fill ${x - 4} ${SURF} -4 ${x + 40} ${SURF + 10} 4 minecraft:air`);
  await fill(`fill ${x + 30} ${SURF} -4 ${x + 30} ${SURF + 6} 4 minecraft:stone`);
  const rows = [];
  const trials = [
    {
      name: "enchanted bow + ordinary arrow",
      bow: `minecraft:bow[minecraft:enchantments={"dwspike:mark":1}]`,
      arrow: "minecraft:arrow",
      counter: "mark_hits",
    },
    {
      name: "ORDINARY bow + enchanted arrow",
      bow: "minecraft:bow",
      arrow: `minecraft:arrow[minecraft:enchantments={"dwspike:mark":1}]`,
      counter: "mark_hits",
    },
    {
      name: "generic bow (dwspike:ammo) + arrow tagged with custom_data",
      bow: `minecraft:bow[minecraft:enchantments={"dwspike:ammo":1}]`,
      arrow: `minecraft:arrow[minecraft:custom_data={dw_bomb:1b}]`,
      counter: "ammo_hits",
    },
    {
      name: "generic bow (dwspike:ammo) + UNTAGGED arrow",
      bow: `minecraft:bow[minecraft:enchantments={"dwspike:ammo":1}]`,
      arrow: "minecraft:arrow",
      counter: "ammo_hits",
    },
  ];
  for (const t of trials) {
    await zeroCounters();
    await batch([
      `gamemode survival ${BOT_A}`,
      `clear ${BOT_A}`,
      `tp ${BOT_A} ${x + 0.5} ${SURF} 0.5 90 0`,
      `give ${BOT_A} ${t.bow}`,
      `give ${BOT_A} ${t.arrow} 8`,
    ]);
    await sleep(900);
    const shot = await fireBow(bots.a);
    await sleep(2500);
    const counters = await readCounters();
    const arrowWeapon = await rcon("data get entity @e[type=minecraft:arrow,limit=1] weapon");
    const arrowItem = await rcon("data get entity @e[type=minecraft:arrow,limit=1] item");
    rows.push({
      trial: t.name,
      bow_given: t.bow,
      arrow_given: t.arrow,
      shot: shot,
      fired: counters[t.counter] > 0,
      ammo_matched: counters.ammo_matched,
      counters,
      arrow_entity_weapon_field: nbt(arrowWeapon),
      arrow_entity_item_field: nbt(arrowItem),
    });
    console.log(
      `[player] ${t.name}: fired=${counters[t.counter] > 0} matched=${counters.ammo_matched} ` +
        `weapon=${nbt(arrowWeapon) ?? "-"}`,
    );
    await killq("@e[type=minecraft:arrow]");
  }
  return rows;
}
/**
 * Draw and release a bow, and REPORT what happened rather than assuming it. A
 * survival bow with no arrows draws and fires nothing, which is
 * indistinguishable from "the enchantment did not work" unless the arrow count
 * and the resulting arrow entity are both recorded.
 */
async function fireBow(bot, yaw = Math.PI / 2, pitch = -0.15) {
  const held = () => bot.inventory.items().concat(bot.inventory.slots.filter(Boolean));
  const bow = held().find((i) => i.name === "bow");
  const arrows = held().filter((i) => i.name === "arrow").reduce((a, i) => a + i.count, 0);
  if (!bow) return { drew: false, reason: "no bow in inventory", arrows };
  await bot.equip(bow, "hand");
  await bot.look(yaw, pitch, true);
  bot.activateItem();
  await sleep(1500);
  bot.deactivateItem();
  await sleep(500);
  const spawned = flag(await rcon(`execute if entity @e[type=minecraft:arrow] ${PROBE}`));
  return { drew: true, arrows, an_arrow_entity_appeared: spawned };
}

// ============================================== H. the loot chest (phase 1 half)
// The reload axis: the delve's premise is that this item SITS IN A CHEST until
// someone finds it. Phase 1 plants the chest; run.sh restarts the server; phase
// 2 re-reads it and re-fires.
async function plantChest() {
  const x = SITES.chest;
  await fill(`fill ${x - 4} ${SURF - 1} -4 ${x + 40} ${SURF - 1} 4 minecraft:stone`);
  await fill(`fill ${x - 4} ${SURF} -4 ${x + 40} ${SURF + 10} 4 minecraft:air`);
  await fill(`fill ${x + 30} ${SURF} -4 ${x + 30} ${SURF + 6} 4 minecraft:stone`);
  await ok(`setblock ${x} ${SURF} 0 minecraft:chest`);
  await ok(
    `item replace block ${x} ${SURF} 0 container.0 with ` +
      `minecraft:bow[minecraft:enchantments={"dwspike:ammo":1},minecraft:item_name='"Scavenged Launcher"']`,
  );
  await ok(
    `item replace block ${x} ${SURF} 0 container.1 with ` +
      `minecraft:arrow[minecraft:custom_data={dw_bomb:1b},minecraft:item_name='"Blasting Bolt"'] 4`,
  );
  const contents = await rcon(`data get block ${x} ${SURF} 0 Items`);
  console.log(`[chest] planted at ${x},${SURF},0`);
  return { position: [x, SURF, 0], contents_after_planting: contents };
}
/** Phase 2: the same chest, after a full server restart. */
async function readChestAndFire(bots) {
  const x = SITES.chest;
  const contents = await rcon(`data get block ${x} ${SURF} 0 Items`);
  await zeroCounters();
  await batch([
    `gamemode creative ${BOT_A}`,
    `clear ${BOT_A}`,
    `gamemode survival ${BOT_A}`,
    `tp ${BOT_A} ${x + 0.5} ${SURF} 0.5 90 0`,
    // Take the loot out of the chest the way a player would: move it, don't
    // re-issue it, so what is fired is the item that survived the restart.
    `item replace entity ${BOT_A} hotbar.0 from block ${x} ${SURF} 0 container.0`,
    `item replace entity ${BOT_A} hotbar.8 from block ${x} ${SURF} 0 container.1`,
  ]);
  await sleep(2500);
  const heldBow = await rcon(`data get entity ${BOT_A} equipment.mainhand`);
  const shot = await fireBow(bots.a);
  await sleep(2500);
  const counters = await readCounters();
  const out = {
    chest_contents_after_restart: contents,
    bow_in_hand_after_taking_it_from_the_chest: nbt(heldBow),
    shot,
    counters,
    fired: counters.ammo_hits > 0,
    ammo_matched: counters.ammo_matched,
  };
  console.log(`[phase2] chest survived, fired=${out.fired} matched=${out.ammo_matched}`);
  return out;
}

// ------------------------------------------------------------------------ main
async function main() {
  proc.stdin.write("scoreboard objectives add dw.sig dummy\n");
  await readLines(1);

  const version = await rcon("version");
  const datapacks = await rcon("datapack list enabled");
  console.log(`[spike] phase ${PHASE}: ${version}`);
  console.log(`[spike] ${datapacks}`);
  if (!/dw-spike/.test(datapacks)) throw new Error(`spike datapack not enabled: ${datapacks}`);

  const mk = async (name) => {
    const bot = mineflayer.createBot({
      host: "127.0.0.1", port: PORT, username: name, auth: "offline", respawn: true,
    });
    await new Promise((res, rej) => {
      bot.once("spawn", res);
      bot.once("kicked", (r) => rej(new Error(`kicked: ${JSON.stringify(r)}`)));
      bot.once("error", rej);
    });
    return bot;
  };
  const bots = { a: await mk(BOT_A), b: await mk(BOT_B) };
  console.log(`[spike] bots joined (protocol ${bots.a.version})`);
  await sleep(1500);
  {
    const [t, f] = await batch([
      `execute if entity ${BOT_A} ${PROBE}`,
      `execute if entity @e[type=minecraft:creeper] ${PROBE}`,
    ]);
    if (flag(t) !== true) throw new Error("probe self-check: a true condition printed nothing");
    if (flag(f) !== false) throw new Error("probe self-check: a false condition printed something");
  }

  for (const g of [
    "gamerule spawn_mobs false",
    "gamerule advance_time false",
    "gamerule advance_weather false",
    "gamerule keep_inventory true",
    "gamerule natural_health_regeneration false",
    "gamerule mob_griefing true", // deliberately ON: block preservation must not
                                  // come from a global gamerule
    "gamerule fall_damage false",
  ]) {
    await ok(g);
  }
  await ok("difficulty hard");
  // MIDNIGHT, not noon: zombies burn in daylight and 0.92 damage/second is
  // indistinguishable from the number the unoffset explosion produces.
  await ok("time set midnight");
  await ok("weather clear");
  for (const x of Object.values(SITES)) {
    await ok(`forceload add ${x - 48} -48 ${x + 48} 48`);
  }
  await batch([`gamemode survival ${BOT_A}`, `gamemode survival ${BOT_B}`,
    `tp ${BOT_A} ${SITES.player + 0.5} ${SURF} 0.5`, `tp ${BOT_B} ${SITES.cloud - 1.5} ${SURF} 0.5`]);

  const prev = existsSync(OUT) && PHASE === 2 ? JSON.parse(readFileSync(OUT, "utf8")) : {};
  const out = {
    ...prev,
    meta: {
      ...(prev.meta ?? {}),
      version_response: version,
      datapack_list: datapacks,
      mineflayer: require("mineflayer/package.json").version,
      container: CONTAINER,
      [`phase${PHASE}_ran_at_gametime`]: await rcon("time query gametime"),
    },
  };

  const flush = () => writeFileSync(OUT, JSON.stringify(out, null, 1));
  if (PHASE === 1) {
    out.a_binding = await bindingMatrix();
    flush();
    out.b_block_damage = await blockDamage();
    flush();
    out.c_entity_damage = await entityDamageSuite();
    flush();
    flush();
    out.c2_orientation = await orientationSuite();
    flush();
    out.d_decorations = [await decorationDamage("dwspike:blast_none")];
    out.e_cloud = await cloudRoute(bots);
    flush();
    out.f_axes = await terrainAxes(bots);
    flush();
    out.g_player_shot = await playerShot(bots);
    flush();
    out.h_chest_planted = await plantChest();
    flush();
  } else {
    out.i_after_restart = await readChestAndFire(bots);
    out.i_after_restart.binding_recheck = await bindingMatrix();
  }

  writeFileSync(OUT, JSON.stringify(out, null, 1));
  console.log(`[spike] raw observations -> ${OUT}`);
  bots.a.end();
  bots.b.end();
  proc.stdin.end();
  process.exit(0);
}

main().catch((e) => {
  console.error("[spike] FAILED:", e);
  process.exit(1);
});
