//! The horizon model (spec-0026): the one place a campaign's resolved stage-1
//! `horizon` becomes **declared physical facts** the rest of the compiler
//! reads. Nothing outside this module matches on
//! [`HorizonBase`](delvewright_dsl::HorizonBase) to decide world physics — a
//! consumer asks here, or asks
//! [`horizon_base`](delvewright_dsl::horizon_base) for the base and nothing
//! else.
//!
//! # The two kinds of horizon, and why the difference is structural
//!
//! `void` and `ocean` are **generator settings**: the world outside the placed
//! geometry is an analytic fact, one superflat layer stack, and the compiler
//! models it as [`nav::Ambient`](crate::compiler::nav::Ambient) — a per-column answer
//! computed rather than stored.
//!
//! `valley` is **built terrain**. Its ground is real blocks in real structure
//! templates, generated by [`crate::compiler::surround`] and placed by the same bootstrap
//! that places every other piece. Its ambient is therefore `void`: there is
//! nothing analytic out there, because everything out there was built.
//!
//! That difference is the whole design. A surround that entered as a new
//! `Ambient` variant would owe a new branch to gravity settling, the occupancy
//! model, relight, boundary safety, the fluid model and the snapshot renderer,
//! and each of those branches would be a second model of the same ground that
//! could disagree with the first. A surround that enters as **placed blocks**
//! owes none of them: every proof already knows how to read a placed block.
//!
//! # Where the surround stands
//!
//! Around the map, never inside it — and *the map* is a fact the campaign
//! states, not one the surround derives from the parts it finds. For a
//! campaign with a site plan that is the plan's `region`, the whole map's one
//! region and its design of record; for a campaign that places areas by hand
//! it is the union of the placed footprints, which is the only statement of
//! extent such a campaign has. See [`crate::compiler::plan::surround_rect`].
//!
//! Reading the region rather than the placed pieces is deliberate and is the
//! ordering spec-0049 exists to hold: a box may never grow the region
//! (`DW0826`), so a surround keyed to the region can never be pushed outward by
//! a part, and the space a plan reserved and did not fill stays reserved
//! instead of being eaten by terrain.

use delvewright_dsl::{Campaign, HorizonBase, ResolvedHorizon, horizon_base, resolved_horizon};

/// The resolved horizon of a campaign — defaults applied, `void` when absent.
pub fn of_campaign(campaign: &Campaign) -> ResolvedHorizon {
    resolved_horizon(&campaign.world.content.horizon)
}

/// The resolved base of a campaign's horizon.
pub fn base_of(campaign: &Campaign) -> HorizonBase {
    horizon_base(&campaign.world.content.horizon)
}

/// Sea level of the `ocean` superflat: the pinned bedrock/stone/water layer
/// stack (1 + 118 + 8 from the −64 build floor) tops the water at y=62.
/// Emission pins the same stack in `generator-settings`.
pub const SEA_LEVEL: i32 = crate::compiler::plan::SEA_LEVEL;

/// The top solid block of a `valley`'s **gap floor** — the flat ground between
/// the map's edge and the foot of the inner slopes.
///
/// Pinned one block under [`crate::compiler::plan::BASE_Y`], which makes
/// `BASE_Y` the y a body's feet occupy standing on it. The gap floor **is a
/// walk plane**, and [`VALLEY_WALK_REF_Y`] is that same number under the name
/// the seating rule reads it by.
pub const VALLEY_GAP_FLOOR_TOP_Y: i32 = crate::compiler::plan::BASE_Y - 1;

/// **The world y a `valley` world's walk plane stands at**: one block above the
/// gap floor, which is [`crate::compiler::plan::BASE_Y`].
///
/// The relationship [`OCEAN_WALK_REF_Y`] states about a beach, stated about
/// ground. A body standing on the valley's own floor has its feet here, so a
/// piece seated on this base puts its own walk plane here — its floor is the
/// floor outside it, and a party can walk from one onto the other.
pub const VALLEY_WALK_REF_Y: i32 = VALLEY_GAP_FLOOR_TOP_Y + 1;

/// **The world y an `ocean` world's walk plane stands at**: one block above the
/// sea (spec-0060 §3.1).
///
/// This is the vanilla-normal beach relationship — a body standing on a shore is
/// one block above the water it can swim in, so it can climb out — and it is the
/// datum an ocean area's origin is DERIVED from, rather than a datum for the
/// origin itself. spec-0013's "areas sit at y=64+" is retired by that ruling and
/// not reinterpreted: under it an island's walk plane would stand four blocks
/// above its own shore.
pub const OCEAN_WALK_REF_Y: i32 = SEA_LEVEL + 1;

/// **The walk-plane datum of a base**, where it has one.
///
/// `Some` for a base that **has ground of its own outside the piece** — and the
/// number an area's origin is then derived from:
/// `origin.y = walk_ref_y - walk_y`.
///
/// `ocean` and `valley` both have one: a sea to climb out of, and a gap floor
/// to walk on. `None` is `void` alone, and that is a decision rather than an
/// omission — `void` declares nothing outside the placed geometry, so there is
/// no outside relationship for a walk plane to be held against, and its areas
/// stand on the fixed [`crate::compiler::plan::BASE_Y`] datum.
///
/// **`valley`'s entry corrects a claim that bound to nothing.** The constant's
/// note used to argue that a valley relocates nothing because *a `walk_y = 0`
/// piece placed at `BASE_Y` stands exactly on this floor* — true, and true of
/// no piece: the pinned library declares `walk_y` 1, 2 or 3 and never 0, so
/// every piece a valley could seat stood one to three courses proud of the
/// ground it was supposed to stand beside. For a site — a piece that brings its
/// own island, moat and banks out to its own box edge — that difference is the
/// whole thing: seated by its walk plane the bank runs into the gap floor, and
/// seated on `BASE_Y` it is a cliff the party drops off and cannot climb back.
pub fn walk_ref_y(base: HorizonBase) -> Option<i32> {
    match base {
        HorizonBase::Ocean => Some(OCEAN_WALK_REF_Y),
        HorizonBase::Valley => Some(VALLEY_WALK_REF_Y),
        HorizonBase::Void => None,
    }
}

/// The seed stream the valley surround draws from (ADR-0006 named streams).
/// Fixed here rather than at the call site so a re-seeding of one build cannot
/// silently become a re-seeding of a different one.
pub const VALLEY_STREAM: &str = "horizon/valley";

#[cfg(test)]
mod tests {
    use super::*;

    /// The relationship the module doc claims, asserted rather than described:
    /// a valley's gap floor tops exactly one block under the void datum, so a
    /// piece placed at `BASE_Y` stands on it.
    #[test]
    fn a_valley_relocates_nothing() {
        assert_eq!(VALLEY_GAP_FLOOR_TOP_Y + 1, crate::compiler::plan::BASE_Y);
    }

    /// `has_surround` is the question every consumer asks, and it must answer
    /// for the whole enum rather than for the base that happens to build
    /// terrain today.
    #[test]
    fn only_valley_builds_terrain() {
        assert!(!HorizonBase::Void.has_surround());
        assert!(!HorizonBase::Ocean.has_surround());
        assert!(HorizonBase::Valley.has_surround());
    }

    /// The ocean's datum is the beach relationship, stated as a number: a body
    /// standing on the walk plane is exactly one block above the water it can
    /// swim in, so it can climb out (spec-0060 §3.1).
    #[test]
    fn the_ocean_walk_plane_is_one_block_above_the_sea() {
        assert_eq!(OCEAN_WALK_REF_Y, SEA_LEVEL + 1);
        assert_eq!(walk_ref_y(HorizonBase::Ocean), Some(SEA_LEVEL + 1));
    }

    /// **A base has a walk-plane datum exactly when it has ground of its own**,
    /// answered for the whole enum rather than for the bases that have one
    /// today: `ocean`'s sea and `valley`'s gap floor are both something outside
    /// the piece that a body stands on or climbs out of, and `void` is by
    /// definition the base that has nothing out there.
    #[test]
    fn a_base_seats_by_a_walk_plane_exactly_when_it_has_ground_of_its_own() {
        assert!(walk_ref_y(HorizonBase::Void).is_none());
        assert_eq!(walk_ref_y(HorizonBase::Valley), Some(VALLEY_WALK_REF_Y));
        assert!(walk_ref_y(HorizonBase::Ocean).is_some());
    }

    /// The valley's datum is the same relationship the ocean's is, stated about
    /// ground: a body standing on the gap floor has its feet one block above
    /// its top solid course, so a piece seated by its own `walk_y` puts its
    /// floor level with the floor outside it — no step up, no cliff down.
    #[test]
    fn the_valley_walk_plane_stands_on_the_gap_floor() {
        assert_eq!(VALLEY_WALK_REF_Y, VALLEY_GAP_FLOOR_TOP_Y + 1);
        assert_eq!(VALLEY_WALK_REF_Y, crate::compiler::plan::BASE_Y);
        // The library's real numbers rather than an invented one: every pinned
        // piece declares `walk_y` 1, 2 or 3, so seating on `BASE_Y` stood each
        // of them that many courses proud of the ground it was meant to stand
        // beside, and the derivation is what removes the step.
        for walk_y in [1, 2, 3] {
            let origin = VALLEY_WALK_REF_Y - walk_y;
            assert_eq!(origin + walk_y, VALLEY_GAP_FLOOR_TOP_Y + 1);
        }
    }

    /// The two numbers spec-0060 §3.2 states as worked examples, derived rather
    /// than restated: a keep interior (`walk_y` 1) is seated at 62 and stands
    /// dry at 63; an island piece (`walk_y` 3) is seated at 60.
    #[test]
    fn the_origin_is_derived_from_the_piece_and_not_from_the_world() {
        let r = walk_ref_y(HorizonBase::Ocean).expect("the ocean has a walk-plane datum");
        assert_eq!(r - 1, 62);
        assert_eq!(r - 3, 60);
        assert!(r > SEA_LEVEL, "a walk plane above the sea is the point");
    }
}
