//! The horizon model (spec-0026): the one place a campaign's resolved stage-1
//! `horizon` becomes **declared physical facts** the rest of the compiler
//! reads. Nothing outside this module matches on
//! [`HorizonBase`](delvewright_dsl::HorizonBase) to decide world physics — a
//! consumer asks here, or asks
//! [`horizon_base`](delvewright_dsl::horizon_base) for the base and nothing
//! else.
//!
//! # The two kinds of horizon, and why the difference is structural
//!
//! `void` and `ocean` are **generator settings**: the world outside the placed
//! geometry is an analytic fact, one superflat layer stack, and the compiler
//! models it as [`nav::Ambient`](crate::compiler::nav::Ambient) — a per-column answer
//! computed rather than stored.
//!
//! `valley` is **built terrain**. Its ground is real blocks in real structure
//! templates, generated by [`crate::compiler::surround`] and placed by the same bootstrap
//! that places every other piece. Its ambient is therefore `void`: there is
//! nothing analytic out there, because everything out there was built.
//!
//! That difference is the whole design. A surround that entered as a new
//! `Ambient` variant would owe a new branch to gravity settling, the occupancy
//! model, relight, boundary safety, the fluid model and the snapshot renderer,
//! and each of those branches would be a second model of the same ground that
//! could disagree with the first. A surround that enters as **placed blocks**
//! owes none of them: every proof already knows how to read a placed block.
//!
//! # Where the surround stands
//!
//! Around the map, never inside it — and *the map* is a fact the campaign
//! states, not one the surround derives from the parts it finds. For a
//! campaign with a site plan that is the plan's `region`, the whole map's one
//! region and its design of record; for a campaign that places areas by hand
//! it is the union of the placed footprints, which is the only statement of
//! extent such a campaign has. See [`crate::compiler::plan::surround_rect`].
//!
//! Reading the region rather than the placed pieces is deliberate and is the
//! ordering spec-0049 exists to hold: a box may never grow the region
//! (`DW0826`), so a surround keyed to the region can never be pushed outward by
//! a part, and the space a plan reserved and did not fill stays reserved
//! instead of being eaten by terrain.

use std::collections::BTreeMap;

use delvewright_dsl::{Campaign, HorizonBase, ResolvedHorizon, horizon_base, resolved_horizon};

/// The resolved horizon of a campaign — defaults applied, `void` when absent.
pub fn of_campaign(campaign: &Campaign) -> ResolvedHorizon {
    resolved_horizon(&campaign.world.content.horizon)
}

/// The resolved base of a campaign's horizon.
pub fn base_of(campaign: &Campaign) -> HorizonBase {
    horizon_base(&campaign.world.content.horizon)
}

/// Sea level of the `ocean` superflat: the pinned bedrock/stone/water layer
/// stack (1 + 118 + 8 from the −64 build floor) tops the water at y=62.
/// Emission pins the same stack in `generator-settings`.
pub const SEA_LEVEL: i32 = crate::compiler::plan::SEA_LEVEL;

/// The top solid block of a `valley`'s **gap floor** — the flat ground between
/// the map's edge and the foot of the inner slopes.
///
/// Pinned one block under [`crate::compiler::plan::BASE_Y`], which makes
/// `BASE_Y` the y a body's feet occupy standing on it. The gap floor **is a
/// walk plane**, and [`VALLEY_WALK_REF_Y`] is that same number under the name
/// the seating rule reads it by.
pub const VALLEY_GAP_FLOOR_TOP_Y: i32 = crate::compiler::plan::BASE_Y - 1;

/// **The world y a `valley` world's walk plane stands at**: one block above the
/// gap floor, which is [`crate::compiler::plan::BASE_Y`].
///
/// The relationship [`OCEAN_WALK_REF_Y`] states about a beach, stated about
/// ground. A body standing on the valley's own floor has its feet here, so a
/// piece seated on this base puts its own walk plane here — its floor is the
/// floor outside it, and a party can walk from one onto the other.
pub const VALLEY_WALK_REF_Y: i32 = VALLEY_GAP_FLOOR_TOP_Y + 1;

/// **The world y an `ocean` world's walk plane stands at**: one block above the
/// sea (spec-0060 §3.1).
///
/// This is the vanilla-normal beach relationship — a body standing on a shore is
/// one block above the water it can swim in, so it can climb out — and it is the
/// datum an ocean area's origin is DERIVED from, rather than a datum for the
/// origin itself. spec-0013's "areas sit at y=64+" is retired by that ruling and
/// not reinterpreted: under it an island's walk plane would stand four blocks
/// above its own shore.
pub const OCEAN_WALK_REF_Y: i32 = SEA_LEVEL + 1;

/// **The walk-plane datum of a base**, where it has one.
///
/// `Some` for a base that **has ground of its own outside the piece** — and the
/// number an area's origin is then derived from:
/// `origin.y = walk_ref_y - walk_y`.
///
/// `ocean` and `valley` both have one: a sea to climb out of, and a gap floor
/// to walk on. `None` is `void` alone, and that is a decision rather than an
/// omission — `void` declares nothing outside the placed geometry, so there is
/// no outside relationship for a walk plane to be held against, and its areas
/// stand on the fixed [`crate::compiler::plan::BASE_Y`] datum.
///
/// **`valley`'s entry corrects a claim that bound to nothing.** The constant's
/// note used to argue that a valley relocates nothing because *a `walk_y = 0`
/// piece placed at `BASE_Y` stands exactly on this floor* — true, and true of
/// no piece: the pinned library declares `walk_y` 1, 2 or 3 and never 0, so
/// every piece a valley could seat stood one to three courses proud of the
/// ground it was supposed to stand beside. For a site — a piece that brings its
/// own island, moat and banks out to its own box edge — that difference is the
/// whole thing: seated by its walk plane the bank runs into the gap floor, and
/// seated on `BASE_Y` it is a cliff the party drops off and cannot climb back.
pub fn walk_ref_y(base: HorizonBase) -> Option<i32> {
    match base {
        HorizonBase::Ocean => Some(OCEAN_WALK_REF_Y),
        HorizonBase::Valley => Some(VALLEY_WALK_REF_Y),
        HorizonBase::Void => None,
    }
}

/// The seed stream the valley surround draws from (ADR-0006 named streams).
/// Fixed here rather than at the call site so a re-seeding of one build cannot
/// silently become a re-seeding of a different one.
pub const VALLEY_STREAM: &str = "horizon/valley";

/// The path, under the delve's own namespace, of the biome a non-ocean
/// generator lays under every column: `<ns>:void`, emitted at
/// `data/<ns>/worldgen/biome/void.json`.
pub const VOID_BIOME_PATH: &str = "void";

/// Whether declared rain falls in the delve's own void biome. It does: this is
/// the one field that biome exists to change.
///
/// **A declared weather is the weather the party stands in.** Vanilla draws
/// rain, counts a body as "in rain" and aims lightning only where
/// `Level.isRainingAt` holds — raining, sky visible, **and the biome at the cell
/// precipitates rain**. Vanilla's `minecraft:the_void` has
/// `has_precipitation: false`, so a void delve generated in it kept a declared
/// `rain`/`thunder` in its level data and never let it reach the ground the
/// party plays on: undead at `dusk` under declared rain burned, and the sky
/// only rained over a painted horizon.
///
/// The fix is a datapack biome — a first-class vanilla primitive — that is
/// `minecraft:the_void` field for field, read from the pinned 1.21.11 jar
/// (`data/minecraft/worldgen/biome/the_void.json`), except for this one flag.
/// [`crate::compiler::daylight`] reads the same constant, so the weather the
/// build proves against and the biome the build ships are one fact.
pub const VOID_BIOME_PRECIPITATES: bool = true;

/// The vanilla biome tag `minecraft:the_void` belongs to, and so the delve's
/// own void biome joins it: the only tag membership of `the_void` in the
/// pinned jar (`data/minecraft/tags/worldgen/biome/`), and the only runtime
/// reference to it by identity besides the flat generator's default-biome
/// fallback. Without it a wandering trader could be offered the play area.
pub const VOID_BIOME_TAGS: [&str; 1] = ["without_wandering_trader_spawns"];

/// `has_precipitation` of every vanilla biome the compiler lays under a
/// column or paints over one, read from the pinned 1.21.11 server jar
/// (`data/minecraft/worldgen/biome/<name>.json`, `versions.toml` `[minecraft]`
/// `server_jar_sha256` `f83b8e09…dd1726`).
const VANILLA_PRECIPITATION: [(&str, bool); 4] = [
    ("minecraft:cherry_grove", true),
    ("minecraft:ocean", true),
    ("minecraft:the_void", false),
    ("minecraft:windswept_forest", true),
];

/// Whether declared rain (or snow) falls in a vanilla biome the compiler
/// names; `None` for a biome it does not name.
pub fn vanilla_precipitates(biome: &str) -> Option<bool> {
    VANILLA_PRECIPITATION
        .iter()
        .find(|(id, _)| *id == biome)
        .map(|&(_, p)| p)
}

/// The biome every column a surround does not paint stands in: the one the
/// `generator-settings` lays, and so the one the play area stands in.
pub struct GroundBiome {
    /// The namespaced biome id `generator-settings` names.
    pub id: String,
    /// Whether declared rain falls in it.
    pub precipitates: bool,
    /// The biome's datapack definition, when the delve ships its own.
    pub definition: Option<serde_json::Value>,
}

/// The ground biome of a campaign whose datapack namespace is `ns`.
///
/// `ocean` keeps vanilla's `minecraft:ocean`, which rains. Every other base
/// generates void, and lays the delve's own void biome ([`VOID_BIOME_PATH`]):
/// `minecraft:the_void` with [`VOID_BIOME_PRECIPITATES`].
fn ground_biome(campaign: &Campaign, ns: &str) -> GroundBiome {
    if base_of(campaign) == HorizonBase::Ocean {
        let id = "minecraft:ocean";
        return GroundBiome {
            id: id.to_string(),
            precipitates: vanilla_precipitates(id).expect("ocean is a named biome"),
            definition: None,
        };
    }
    GroundBiome {
        id: format!("{ns}:{VOID_BIOME_PATH}"),
        precipitates: VOID_BIOME_PRECIPITATES,
        definition: Some(void_biome_definition()),
    }
}

/// `minecraft:the_void` as the pinned jar defines it, with `has_precipitation`
/// set to [`VOID_BIOME_PRECIPITATES`]. Temperature 0.5 never falls below the
/// 0.15 snow line inside the build height, so what falls is rain.
pub(crate) fn void_biome_definition() -> serde_json::Value {
    serde_json::json!({
        "attributes": { "minecraft:visual/sky_color": "#7ba4ff" },
        "carvers": [],
        "downfall": 0.5,
        "effects": { "water_color": "#3f76e4" },
        "features": [[], [], [], [], [], [], [], [], [], [], ["minecraft:void_start_platform"]],
        "has_precipitation": VOID_BIOME_PRECIPITATES,
        "spawn_costs": {},
        "spawners": {
            "ambient": [],
            "axolotls": [],
            "creature": [],
            "misc": [],
            "monster": [],
            "underground_water_creature": [],
            "water_ambient": [],
            "water_creature": []
        },
        "temperature": 0.5
    })
}

// ---------------------------------------------------------------------------
// The biome map (spec-0080 §4): the one answer to which biome is where
// ---------------------------------------------------------------------------

/// What laid a paint in the [`BiomeMap`].
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum PaintSource {
    /// A valley surround's band (spec-0026), outside the map by construction.
    Band,
    /// A place carrying an atmosphere (spec-0080 §3.2): an `area/…` or a
    /// site-plan box's `node/…`, and the atmosphere it carries.
    Place {
        /// The place id.
        place: String,
        /// The atmosphere id.
        atmosphere: String,
    },
}

/// One paint over the ground biome.
#[derive(Clone, Debug)]
pub struct Paint {
    /// The block box the bootstrap `fillbiome` names.
    pub fill: ([i32; 3], [i32; 3]),
    /// The cells it paints: the enclosing 4-aligned box.
    pub cells: ([i32; 3], [i32; 3]),
    /// The namespaced biome id.
    pub biome: String,
    /// Whether declared rain or snow falls in it.
    pub precipitates: bool,
    /// What laid it.
    pub source: PaintSource,
}

impl Paint {
    fn covers(&self, cell: [i32; 3]) -> bool {
        (0..3).all(|i| self.cells.0[i] <= cell[i] && cell[i] <= self.cells.1[i])
    }
}

/// **Which biome every cell stands in at the first tick**: the paints in the
/// order the bootstrap runs them — the valley's bands, then every carried place
/// in declaration order — over the ground biome. A later paint wins a cell, as
/// a later `fillbiome` does.
///
/// A cell is answered by the 4-cell it lies in. Vanilla's own reading
/// (`BiomeManager.getBiome`) jitters the sample point, so a block within two of
/// a 4-cell face may read its neighbour; a block whose coordinates are all 2
/// mod 4 always reads its own cell, which is where the runtime proofs sample.
pub struct BiomeMap {
    /// The paints, in bootstrap order.
    pub paints: Vec<Paint>,
    /// The biome every unpainted column stands in — the one the
    /// `generator-settings` lays.
    pub ground: GroundBiome,
    /// Every declared atmosphere's biome id, and whether rain falls in it.
    atmospheres: BTreeMap<String, bool>,
    /// The delve's datapack namespace.
    namespace: String,
}

impl BiomeMap {
    /// The biome `cell` stands in at the first tick, and whether rain falls
    /// there.
    pub fn at(&self, cell: [i32; 3]) -> (&str, bool) {
        self.paints
            .iter()
            .rev()
            .find(|p| p.covers(cell))
            .map_or((self.ground.id.as_str(), self.ground.precipitates), |p| {
                (p.biome.as_str(), p.precipitates)
            })
    }

    /// The paints a carried place laid, in bootstrap order.
    pub fn places(&self) -> impl Iterator<Item = &Paint> {
        self.paints
            .iter()
            .filter(|p| matches!(p.source, PaintSource::Place { .. }))
    }
}

impl BiomeMap {
    /// Whether declared rain falls in `biome`: a vanilla biome the compiler
    /// names, an atmosphere the campaign declares, or the ground biome. **The
    /// one function** every precipitation question goes through.
    pub fn precipitates(&self, biome: &str) -> bool {
        if let Some(p) = vanilla_precipitates(biome) {
            return p;
        }
        if let Some(p) = self.atmospheres.get(biome) {
            return *p;
        }
        assert_eq!(
            self.ground.id, biome,
            "the compiler paints `{biome}`, whose precipitation is unrecorded"
        );
        self.ground.precipitates
    }

    /// The biome an atmosphere reference paints: the declared atmosphere's, or
    /// the ground biome for `None` (`atmosphere: null`).
    pub fn biome_of(&self, atmosphere: Option<&str>) -> String {
        match atmosphere {
            Some(id) => crate::compiler::atmosphere::biome_id(&self.namespace, id),
            None => self.ground.id.clone(),
        }
    }
}

/// A place's world box: an area's placed bounds, or a site-plan box's play
/// space — the volume its `atmosphere` paints at setup and a `set-atmosphere`
/// with `place` repaints. Handed by the placement, typed by nobody.
pub fn place_bounds(
    plan: &crate::compiler::plan::Plan,
    place: &str,
) -> Option<([i32; 3], [i32; 3])> {
    if let Some(a) = plan.areas.iter().find(|a| a.area_id == place) {
        return Some(a.bounds());
    }
    let mut reads = delvewright_dsl::metrics::Reads::new();
    delvewright_dsl::placed_boxes(plan.campaign, &mut reads)
        .iter()
        .find(|b| b.node.as_str() == place)
        .map(|b| {
            let (lo, hi) = b.space();
            (
                [lo[0] as i32, lo[1] as i32, lo[2] as i32],
                [hi[0] as i32, hi[1] as i32, hi[2] as i32],
            )
        })
}

/// The block box a `set-atmosphere` repaints: its `region` through
/// [`crate::compiler::plan::Plan::zone_box`], or its `place`'s bounds.
pub fn repaint_volume(
    plan: &crate::compiler::plan::Plan,
    eff: &delvewright_dsl::QuestEffect,
) -> Option<([i32; 3], [i32; 3])> {
    match &eff.verb {
        delvewright_dsl::Verb::SetAtmosphere {
            region: Some(zone),
            place: None,
            ..
        } => plan.zone_box(zone),
        delvewright_dsl::Verb::SetAtmosphere {
            region: None,
            place: Some(place),
            ..
        } => place_bounds(plan, place),
        _ => None,
    }
}

/// The places of a campaign that can carry an atmosphere, in declaration
/// order: `(place id, atmosphere)` for each area, or each site-plan box.
pub fn carried_places(campaign: &Campaign) -> Vec<(String, Option<String>)> {
    if let Some(sp) = &campaign.site_plan {
        return sp
            .content
            .boxes
            .iter()
            .map(|b| {
                (
                    b.node.as_str().to_string(),
                    b.atmosphere.as_ref().map(|a| a.as_str().to_string()),
                )
            })
            .collect();
    }
    campaign
        .world
        .content
        .areas
        .iter()
        .map(|a| {
            (
                a.id.as_str().to_string(),
                a.atmosphere.as_ref().map(|a| a.as_str().to_string()),
            )
        })
        .collect()
}

/// The biome map of a planned campaign (spec-0080 §4.1).
pub fn biome_map(plan: &crate::compiler::plan::Plan) -> BiomeMap {
    let c = plan.campaign;
    let ns = &plan.namespace;
    let mut map = BiomeMap {
        paints: Vec::new(),
        ground: ground_biome(c, ns),
        atmospheres: c
            .world
            .content
            .atmospheres
            .iter()
            .map(|a| {
                (
                    crate::compiler::atmosphere::biome_id(ns, a.id.as_str()),
                    crate::compiler::atmosphere::precipitates(a),
                )
            })
            .collect(),
        namespace: ns.clone(),
    };
    let mut paints: Vec<Paint> = Vec::new();
    if let Some(surround) = &plan.surround {
        for r in &surround.biome {
            paints.push(Paint {
                fill: (r.min, r.max),
                cells: crate::compiler::atmosphere::painted_box(r.min, r.max),
                biome: r.biome.to_string(),
                precipitates: map.precipitates(r.biome),
                source: PaintSource::Band,
            });
        }
    }
    for (place, atmosphere) in carried_places(c) {
        let Some(atmosphere) = atmosphere else {
            continue;
        };
        let Some((min, max)) = place_bounds(plan, &place) else {
            continue;
        };
        let biome = crate::compiler::atmosphere::biome_id(ns, &atmosphere);
        paints.push(Paint {
            fill: (min, max),
            cells: crate::compiler::atmosphere::painted_box(min, max),
            precipitates: map.precipitates(&biome),
            biome,
            source: PaintSource::Place { place, atmosphere },
        });
    }
    map.paints = paints;
    map
}

/// The lowest and highest block a `fillbiome` can reach: the overworld's
/// build height (`dimension_type/overworld.json`, `min_y` −64, `height` 384).
pub const BUILD_MIN_Y: i32 = -64;
/// See [`BUILD_MIN_Y`].
pub const BUILD_MAX_Y: i32 = 319;

/// The map's extent in columns: the rectangle a surround rings when the
/// campaign states one ([`crate::compiler::plan::surround_rect`]), else the
/// union of the placed pieces' footprints — the columns world setup
/// force-loads. A `fillbiome` outside it reaches a chunk nothing loads, which
/// is the same silent no-op an unloaded `place template` is.
fn extent_columns(plan: &crate::compiler::plan::Plan) -> Vec<[i32; 4]> {
    if let Some((r, _)) = crate::compiler::plan::surround_rect(plan.campaign, &plan.areas) {
        return vec![[r.min_x, r.min_z, r.max_x, r.max_z]];
    }
    plan.areas
        .iter()
        .flat_map(|a| a.pieces.iter())
        .map(|p| {
            let (lo, hi) = p.bbox();
            [lo[0], lo[2], hi[0], hi[2]]
        })
        .collect()
}

/// The first two carried places whose painted 4-cells meet under different
/// biomes, in bootstrap order.
fn meeting_places(map: &BiomeMap) -> Option<(&Paint, &Paint)> {
    let places: Vec<&Paint> = map.places().collect();
    for (i, a) in places.iter().enumerate() {
        for b in &places[i + 1..] {
            let meet = (0..3).all(|k| a.cells.0[k] <= b.cells.1[k] && b.cells.0[k] <= a.cells.1[k]);
            if meet && a.biome != b.biome {
                return Some((a, b));
            }
        }
    }
    None
}

/// `DW0929`'s build arms: two carried places whose painted cells meet with
/// different atmospheres, and a repaint volume with a cell outside the map's
/// extent.
pub fn check_paints(
    plan: &crate::compiler::plan::Plan,
    map: &BiomeMap,
) -> Result<(), crate::compiler::failure::Failure> {
    let code = crate::compiler::atmosphere::DW_ATMOSPHERE_PAINT;
    if let Some((a, b)) = meeting_places(map) {
        if let (PaintSource::Place { place: pa, .. }, PaintSource::Place { place: pb, .. }) =
            (&a.source, &b.source)
        {
            return Err(crate::compiler::failure::Failure {
                code,
                message: format!(
                    "`{pa}` carries `{}` and `{pb}` carries `{}`, and the 4-cells they paint meet ({:?}..{:?} and {:?}..{:?}). A biome cell is 4×4×4, so a cell they share would belong to whichever `fillbiome` ran last — an order, not a declaration. Give the two places one atmosphere, or move them apart so that a whole 4-cell separates them.",
                    a.biome, b.biome, a.cells.0, a.cells.1, b.cells.0, b.cells.1
                ),
            });
        }
    }
    let columns = extent_columns(plan);
    for (_, path, eff) in crate::compiler::atmosphere::set_atmospheres(plan.campaign) {
        let Some((min, max)) = repaint_volume(plan, eff) else {
            continue;
        };
        let (lo, hi) = crate::compiler::atmosphere::painted_box(min, max);
        let inside = |x: i32, z: i32| {
            columns
                .iter()
                .any(|r| r[0] <= x && x <= r[2] && r[1] <= z && z <= r[3])
        };
        // Every column of the volume, sampled on a 4-block grid and at its far
        // faces: a statement of extent is a union of rectangles, so no corner
        // test alone answers it.
        let xs: Vec<i32> = (min[0]..=max[0]).step_by(4).chain([max[0]]).collect();
        let zs: Vec<i32> = (min[2]..=max[2]).step_by(4).chain([max[2]]).collect();
        let column_out = xs.iter().any(|&x| zs.iter().any(|&z| !inside(x, z)));
        let y_out = min[1] < BUILD_MIN_Y || max[1] > BUILD_MAX_Y;
        if column_out || y_out {
            return Err(crate::compiler::failure::Failure {
                code,
                message: format!(
                    "the `set-atmosphere` at quests {path} repaints {min:?}..{max:?} (the 4-cells {lo:?}..{hi:?}), which reaches past the map's extent {}. `fillbiome` into a chunk nothing loads is a silent no-op, so part of the volume would keep its old sky with every proof green. Shrink the region's `extent`, or move its anchor, so the whole volume stands inside the map.",
                    if y_out {
                        format!("(the build height, y {BUILD_MIN_Y}..{BUILD_MAX_Y})")
                    } else {
                        format!("(columns {columns:?})")
                    }
                ),
            });
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The relationship the module doc claims, asserted rather than described:
    /// a valley's gap floor tops exactly one block under the void datum, so a
    /// piece placed at `BASE_Y` stands on it.
    /// The void biome's shipped definition and the fact the proofs read are
    /// one value, and it rains.
    #[test]
    fn the_void_biome_ships_the_precipitation_the_proofs_read() {
        let def = void_biome_definition();
        assert_eq!(
            def["has_precipitation"],
            serde_json::json!(VOID_BIOME_PRECIPITATES)
        );
        assert_eq!(vanilla_precipitates("minecraft:the_void"), Some(false));
    }

    #[test]
    fn a_valley_relocates_nothing() {
        assert_eq!(VALLEY_GAP_FLOOR_TOP_Y + 1, crate::compiler::plan::BASE_Y);
    }

    /// `has_surround` is the question every consumer asks, and it must answer
    /// for the whole enum rather than for the base that happens to build
    /// terrain today.
    #[test]
    fn only_valley_builds_terrain() {
        assert!(!HorizonBase::Void.has_surround());
        assert!(!HorizonBase::Ocean.has_surround());
        assert!(HorizonBase::Valley.has_surround());
    }

    /// The ocean's datum is the beach relationship, stated as a number: a body
    /// standing on the walk plane is exactly one block above the water it can
    /// swim in, so it can climb out (spec-0060 §3.1).
    #[test]
    fn the_ocean_walk_plane_is_one_block_above_the_sea() {
        assert_eq!(OCEAN_WALK_REF_Y, SEA_LEVEL + 1);
        assert_eq!(walk_ref_y(HorizonBase::Ocean), Some(SEA_LEVEL + 1));
    }

    /// **A base has a walk-plane datum exactly when it has ground of its own**,
    /// answered for the whole enum rather than for the bases that have one
    /// today: `ocean`'s sea and `valley`'s gap floor are both something outside
    /// the piece that a body stands on or climbs out of, and `void` is by
    /// definition the base that has nothing out there.
    #[test]
    fn a_base_seats_by_a_walk_plane_exactly_when_it_has_ground_of_its_own() {
        assert!(walk_ref_y(HorizonBase::Void).is_none());
        assert_eq!(walk_ref_y(HorizonBase::Valley), Some(VALLEY_WALK_REF_Y));
        assert!(walk_ref_y(HorizonBase::Ocean).is_some());
    }

    /// The valley's datum is the same relationship the ocean's is, stated about
    /// ground: a body standing on the gap floor has its feet one block above
    /// its top solid course, so a piece seated by its own `walk_y` puts its
    /// floor level with the floor outside it — no step up, no cliff down.
    #[test]
    fn the_valley_walk_plane_stands_on_the_gap_floor() {
        assert_eq!(VALLEY_WALK_REF_Y, VALLEY_GAP_FLOOR_TOP_Y + 1);
        assert_eq!(VALLEY_WALK_REF_Y, crate::compiler::plan::BASE_Y);
        // The library's real numbers rather than an invented one: every pinned
        // piece declares `walk_y` 1, 2 or 3, so seating on `BASE_Y` stood each
        // of them that many courses proud of the ground it was meant to stand
        // beside, and the derivation is what removes the step.
        for walk_y in [1, 2, 3] {
            let origin = VALLEY_WALK_REF_Y - walk_y;
            assert_eq!(origin + walk_y, VALLEY_GAP_FLOOR_TOP_Y + 1);
        }
    }

    /// The two numbers spec-0060 §3.2 states as worked examples, derived rather
    /// than restated: a keep interior (`walk_y` 1) is seated at 62 and stands
    /// dry at 63; an island piece (`walk_y` 3) is seated at 60.
    #[test]
    fn the_origin_is_derived_from_the_piece_and_not_from_the_world() {
        let r = walk_ref_y(HorizonBase::Ocean).expect("the ocean has a walk-plane datum");
        assert_eq!(r - 1, 62);
        assert_eq!(r - 3, 60);
        assert!(r > SEA_LEVEL, "a walk plane above the sea is the point");
    }
}
